param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "../../..")),
  [ValidateSet('f210','f200','f110','f100')][string]$Target = 'f210',
  [switch]$Check
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $repo 'tools/lib/validation/CurrentTargetPackage.ps1')
$targetPackage = New-MIR4CurrentTargetPackageContext -RepoRoot $repo -Target $Target
. (Join-Path $repo "tools\lib\validation\TargetProfiles.ps1")

function ConvertTo-MIRLuaString {
  param([string]$Value)
  $escaped = $Value.Replace("\", "\\").Replace('"', '\"').Replace("`r", "\r").Replace("`n", "\n")
  return '"' + $escaped + '"'
}

function ConvertTo-MIRLuaLiteral {
  param(
    [AllowNull()]$Value,
    [int]$Indent = 0
  )

  if ($null -eq $Value) { return "nil" }
  if ($Value -is [bool]) { return $(if ($Value) { "true" } else { "false" }) }
  if ($Value -is [string]) { return ConvertTo-MIRLuaString -Value $Value }
  if ($Value -is [byte] -or $Value -is [int16] -or $Value -is [int32] -or $Value -is [int64] -or $Value -is [single] -or $Value -is [double] -or $Value -is [decimal]) {
    return [string]::Format([Globalization.CultureInfo]::InvariantCulture, "{0}", $Value)
  }

  $padding = " " * $Indent
  $childPadding = " " * ($Indent + 2)
  if ($Value -is [System.Collections.IEnumerable] -and $Value -isnot [pscustomobject]) {
    $items = @($Value)
    if ($items.Count -eq 0) { return "{}" }
    $rendered = @($items | ForEach-Object { $childPadding + (ConvertTo-MIRLuaLiteral -Value $_ -Indent ($Indent + 2)) })
    return "{`n" + ($rendered -join ",`n") + "`n$padding}"
  }

  $properties = @($Value.PSObject.Properties)
  if ($properties.Count -eq 0) { return "{}" }
  $rows = foreach ($property in $properties) {
    $key = if ($property.Name -match '^[A-Za-z_][A-Za-z0-9_]*$') {
      $property.Name
    } else {
      "[" + (ConvertTo-MIRLuaString -Value $property.Name) + "]"
    }
    $childPadding + $key + " = " + (ConvertTo-MIRLuaLiteral -Value $property.Value -Indent ($Indent + 2))
  }
  return "{`n" + ($rows -join ",`n") + "`n$padding}"
}

$manifest = Get-MIRTargetManifest -RepoRoot $repo
$info = Get-MIR4CurrentTargetPackageOutputText -Context $targetPackage -RelativePath 'info.json' | ConvertFrom-Json
$null = Get-MIRTargetProfile -RepoRoot $repo -FactorioVersion $info.factorio_version

$profilesLua = ConvertTo-MIRLuaLiteral -Value $manifest.profiles -Indent 2
$outputPath = Resolve-MIR4CurrentTargetPackageOutputPath -Context $targetPackage -RelativePath 'prototypes/mir/platform/factorio/target_profiles.lua'
$sharedBaseAdapter = [IO.Path]::GetFullPath((Join-Path $repo 'source/adapters/platform/base-version-profile/target_profiles.lua'))
if ([IO.Path]::GetFullPath($outputPath) -ceq $sharedBaseAdapter) {
  # This adapter selects its line from mods.base or script.active_mods. Its
  # authored selector must survive generation, and only its existing reduced
  # representation belongs here; the modern profile catalogue is not copied.
  $existing = [IO.File]::ReadAllText($outputPath).Replace("`r`n", "`n")
  $prefix = [regex]::Match($existing, '(?s)\A(?<prefix>.*?)(?:local function reduced_profile\(|local M\s*=\s*\{)')
  $suffix = [regex]::Match($existing, '(?s)\nfunction M\.current\(\).*\z')
  if (-not $prefix.Success -or -not $suffix.Success -or
      -not $prefix.Groups['prefix'].Value.Contains('local function current_factorio_line()')) {
    throw 'Shared base-version adapter selector is missing; preserve the source before recovery.'
  }
  $fields = @('factorio_version','support_class','validation_status','runtime_state_backend',
    'science_family','reduced_legacy','legacy_factorio_2_0','supports_space_age',
    'weapon_overlap_default','technology_overlay_policy','profile_schema','prototype_shapes',
    'emitter_families','asset_policy','expected_stream_count','features','supported_required_mods',
    'supported_effect_types','required_validation_groups')
  $shapeFields = @('recipe_category','science_pack_prototype_kinds','product_probability_fields',
    'technology_formula','quality','surface_conditions','mod_data')
  $sharedProfiles = [ordered]@{}
  foreach ($line in @('1.1','1.0')) {
    $authority = Get-MIRTargetProfile -RepoRoot $repo -FactorioVersion $line
    $profile = [ordered]@{}
    foreach ($field in $fields) { $profile[$field] = $authority.$field }
    $shapes = [ordered]@{}
    foreach ($field in $shapeFields) { $shapes[$field] = $authority.prototype_shapes.$field }
    $profile['prototype_shapes'] = [pscustomobject]$shapes
    $sharedProfiles[$line] = [pscustomobject]$profile
  }
  $profilesLua = ConvertTo-MIRLuaLiteral -Value ([pscustomobject]$sharedProfiles) -Indent 2
  $content = $prefix.Groups['prefix'].Value + @"
local M = {
  schema = $($manifest.schema),
  current_factorio_version = current_factorio_line(),
  profiles = $profilesLua
}
"@ + $suffix.Value
} else {
$content = @"
-- Generated by scripts/Sync-MIRTargetProfiles.ps1 from .mir/targets.json.
-- Do not edit this file directly.
local M = {
  schema = $($manifest.schema),
  current_factorio_version = "$($info.factorio_version)",
  profiles = $profilesLua
}

function M.current()
  local profile = M.profiles[M.current_factorio_version]
  if not profile then
    error("MIR target profile is missing for Factorio " .. tostring(M.current_factorio_version) .. ".", 2)
  end
  return profile
end

return M
"@
}
$content = $content.Replace("`r`n", "`n").TrimEnd() + "`n"

if ($Check) {
  if (-not (Test-Path -LiteralPath $outputPath -PathType Leaf)) {
    throw "Generated target profile Lua is missing: $outputPath"
  }
  $existing = (Get-Content -Raw -LiteralPath $outputPath).Replace("`r`n", "`n")
  if ($existing -ne $content) {
    throw "Generated target profile Lua is stale. Run tools/commands/targets/Sync-MIRTargetProfiles.ps1."
  }
  Write-Host "[ok] MIR target profile Lua matches .mir/targets.json and $Target composition."
  exit 0
}

[IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $outputPath"
