-- Generated by scripts/Update-MIRTechnologyGovernance.ps1. Do not edit by hand.
return {
  applicability_envelopes = {},
  approvals = {},
  authority = "mir-technology-governance-v1",
  authorizations = {
    {
      applicability_envelope = {
        fixture = "assert-compiler-contracts"
      },
      authorization_id = "mir.reviewed.compiler-contract-fixture-v1",
      family = "assembling-machine-manufacturing",
      pack = "pack-operational",
      provider_version = "family-rule-v3",
      stream = "research_auto_assembling_machine",
      trust_class = "mir-reviewed"
    },
    {
      applicability_envelope = {
        mod = "mir-fixture-semantic-family-attach",
        version = "0.1.0"
      },
      authorization_id = "mir.reviewed.semantic-family-fixture-v1",
      family = "assembling-machine-manufacturing",
      pack = "semantic-family-fixture",
      provider_version = "family-rule-v3",
      stream = "research_auto_assembling_machine",
      trust_class = "mir-reviewed"
    },
    {
      applicability_envelope = {
        mod = "mir-fixture-assert-upgrade-3-1-9-to-3-2-0",
        version = "0.1.0"
      },
      authorization_id = "mir.reviewed.upgrade-automatic-family-v1",
      family = "assembling-machine-manufacturing",
      pack = "mir-upgrade-automatic-family",
      provider_version = "family-rule-v3",
      stream = "research_auto_assembling_machine",
      trust_class = "mir-reviewed"
    }
  },
  migrations = {},
  promotions = {},
  schema = 1
}
