# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$BobModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-a06-bob-aluminium-qualification'
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path;$engine=(Resolve-Path -LiteralPath $FactorioBin).Path;$bobMods=(Resolve-Path -LiteralPath $BobModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot));$buildRoot=[IO.Path]::GetFullPath((Join-Path $repo 'build'))+[IO.Path]::DirectorySeparatorChar;if(-not $output.StartsWith($buildRoot,[StringComparison]::OrdinalIgnoreCase)){throw 'A06 Bob Aluminium qualification outputs must be under build.'}
$engineSha='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$archives=[ordered]@{'boblibrary_3.0.0.zip'='49EAE2D4D8E58EBD28BAFDB7E71D5307CBCE2077E0642440ED7EC527D466FFC4';'bobores_3.0.0.zip'='7F8E33E35F59BB3F2CD72E3AB2FED30D1C2AE9C117E3731324AC307D9965082B';'bobplates_3.0.1.zip'='503D7BF6E88DA1F99463AC00CEC959C2003B2701D80DC4A564CF2EC3920AC8AF'}
function Assert-A06([bool]$Condition,[string]$Message){if(-not $Condition){throw "[mir-a06-bob-aluminium-qualification] $Message"}}
function Get-A06Sha([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash}
function Get-A06Artifact([string]$Path){$full=(Resolve-Path -LiteralPath $Path).Path;Assert-A06 ($full.StartsWith($repo+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)) "artifact outside repository $full";[ordered]@{path=$full.Substring($repo.Length+1).Replace('\','/');bytes=(Get-Item -LiteralPath $full).Length;raw_sha256=Get-A06Sha $full}}
function Assert-Exact([string]$Name,$Actual,$Expected){if($null -eq $Actual -and $null -eq $Expected){return};if($null -eq $Actual -or $null -eq $Expected -or $Actual -cne $Expected){throw "$Name differs: expected '$Expected', actual '$Actual'."}}
function Read-A06Data([string]$Text){$m=[regex]::Matches($Text,'\[mir-a06-bob-aluminium-qualification\] DATA recipe=(?<recipe>[^\s]+) machine=(?<machine>[^\s]+) category=(?<category>[^\s]+) owner=(?<owner>[0-9]+) change=(?<change>[0-9.]+) prerequisites=(?<prerequisites>[^\s]+) science=(?<science>[^\s]+) lab=(?<lab>[^\s]+) raw=(?<raw>[0-9]+) imported=(?<imported>[0-9]+) effective=(?<effective>[0-9]+)');Assert-A06 ($m.Count -eq 1) "expected one data record, observed $($m.Count)";$v=$m[0];[pscustomobject]@{recipe=$v.Groups['recipe'].Value;machine=$v.Groups['machine'].Value;category=$v.Groups['category'].Value;owner=[int]$v.Groups['owner'].Value;change=[double]::Parse($v.Groups['change'].Value,[Globalization.CultureInfo]::InvariantCulture);prerequisites=@($v.Groups['prerequisites'].Value.Split(','));science=@($v.Groups['science'].Value.Split(','));lab=$v.Groups['lab'].Value;raw=[int]$v.Groups['raw'].Value;imported=[int]$v.Groups['imported'].Value;effective=[int]$v.Groups['effective'].Value}}
function Read-A06States([string]$Text){$matches=[regex]::Matches($Text,'\[mir-a06-bob-aluminium-qualification\] STATE stage=(?<stage>[^\s]+) generation=(?<generation>-?[0-9]+) predecessor=(?<predecessor>-?[0-9]+) stable=(?<stable>[^\r\n]+)');$rows=@();foreach($m in $matches){$rows+=,[pscustomobject]@{stage=$m.Groups['stage'].Value;generation=[int]$m.Groups['generation'].Value;predecessor=[int]$m.Groups['predecessor'].Value;stable=$m.Groups['stable'].Value}};$rows}
function Read-A06Production([string]$Text){$m=[regex]::Matches($Text,'\[mir-a06-bob-aluminium-qualification\] PRODUCTION raw=(?<raw>[0-9]+) imported=(?<imported>[0-9]+) effective=(?<effective>[0-9]+) no-level-4=(?<no4>true|false) input-alumina=(?<alumina>[0-9]+) input-carbon=(?<carbon>[0-9]+) levels=(?<levels>[^\s]+) inputs-exhausted=(?<exhausted>true|false) output-drained=(?<drained>true|false)');Assert-A06 ($m.Count -eq 1) "expected one production record, observed $($m.Count)";$levels=@();foreach($part in $m[0].Groups['levels'].Value.Split(',')){if($part -notmatch '^(?<level>[0-9]+):(?<output>[0-9]+):(?<bonus>[0-9]+)$'){throw "malformed production level $part"};$levels+=,[pscustomobject]@{completed_level=[int]$Matches.level;output=[int]$Matches.output;bonus=[int]$Matches.bonus}};[pscustomobject]@{raw=[int]$m[0].Groups['raw'].Value;imported=[int]$m[0].Groups['imported'].Value;effective=[int]$m[0].Groups['effective'].Value;no_level_four=($m[0].Groups['no4'].Value -ceq 'true');alumina=[int]$m[0].Groups['alumina'].Value;carbon=[int]$m[0].Groups['carbon'].Value;levels=$levels;inputs_exhausted=($m[0].Groups['exhausted'].Value -ceq 'true');output_drained=($m[0].Groups['drained'].Value -ceq 'true')}}
Assert-A06 ((Get-A06Sha $engine) -ceq $engineSha) 'requires exact Steam Factorio 2.1.17 binary.';$version=(& $engine --version|Out-String);Assert-A06 ($LASTEXITCODE -eq 0 -and $version -match 'Version: 2[.]1[.]17') 'requires Factorio 2.1.17.';$engineVersion=([regex]::Match($version,'Version:\s+2[.]1[.]17[^\r\n]*').Value).Trim()
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim();$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim();Assert-A06 ($sourceCommit -match '^[0-9a-f]{40}$' -and $sourceTree -match '^[0-9a-f]{40}$') 'requires source commit/tree identities.';$sourceChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod);$allowedDirtySources=@('src/mod/families/modern/prototypes/streams/productivity.lua','src/mod/package-source.json');$sourceChangePaths=@($sourceChanges|ForEach-Object{$_.Substring(3).Replace('\','/')}|Sort-Object -CaseSensitive);$sourceRootClean=($sourceChangePaths.Count -eq 0);$boundedDirtyA06Sources=(($sourceChangePaths -join '|') -ceq ($allowedDirtySources -join '|'));Assert-A06 ($sourceRootClean -or $boundedDirtyA06Sources) "requires a clean src/mod root or exactly the A06 certificate and refreshed source binding changes: $($sourceChanges -join '; ')"
$fixture=Join-Path $repo 'fixtures/assert-a06-bob-aluminium-qualification';$dossierPath=Join-Path $fixture 'qualification-dossier.json';$dossier=Get-Content -Raw -LiteralPath $dossierPath|ConvertFrom-Json;Assert-Exact dossier.kind $dossier.kind 'MIR4A06BobAluminiumQualificationV1';Assert-Exact dossier.continuity.kind $dossier.continuity.kind 'fresh-current-candidate-serialized-reload';Assert-Exact dossier.continuity.upgrade $dossier.continuity.predecessor_upgrade_status 'unresolved-no-authentic-predecessor-package'
Assert-Exact dossier.certificate.id $dossier.certificate.id 'A06-Bob-Aluminium-F210-2.1.17-v1';Assert-Exact dossier.certificate.evidence_id $dossier.certificate.evidence_id 'A06-Bob-Aluminium-F210-locked-current-v1';Assert-Exact dossier.certificate.risk $dossier.certificate.canonical_risk_fingerprint 'mir32-fd133af7';Assert-A06 (@($dossier.certificate.hard_flags).Count -eq 0 -and @($dossier.certificate.review_flags).Count -eq 0 -and @($dossier.certificate.shared_input_output).Count -eq 0) 'dossier certificate requires empty hard/review/shared flags.';Assert-Exact dossier.certificate.confidence ([int]$dossier.certificate.evidence_confidence) 1;Assert-A06 ([double]$dossier.certificate.maximum_productivity -eq 3.0) 'dossier certificate maximum productivity differs.'
Assert-Exact dossier.certificate.source_class $dossier.certificate.source_class 'ordinary';Assert-Exact dossier.certificate.hidden ([bool]$dossier.certificate.hidden) $false;Assert-Exact dossier.certificate.declared_allow_productivity ([bool]$dossier.certificate.declared_allow_productivity) $true;Assert-Exact dossier.certificate.effective_allow_productivity ([bool]$dossier.certificate.effective_allow_productivity) $true
. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1');. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1');. (Join-Path $repo 'tools/lib/validation/SettingsOverrides.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)){$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('A06-BOB-ALUMINIUM-QUALIFICATION-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/a06-bob-aluminium-qualification/packages';$CandidateZip=[string]$candidate.archive_path};$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try{$forbidden=@($zip.Entries|Where-Object{$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "candidate contains package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';$userdata=Join-Path $run 'userdata';New-Item -ItemType Directory -Force -Path $mods,$userdata,(Join-Path $userdata 'saves')|Out-Null;Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveArtifacts=@();foreach($entry in $archives.GetEnumerator()){$source=Join-Path $bobMods $entry.Key;Assert-A06 (Test-Path -LiteralPath $source -PathType Leaf) "missing exact Bob archive $($entry.Key)";Assert-A06 ((Get-A06Sha $source) -ceq $entry.Value) "Bob archive hash differs $($entry.Key)";Copy-Item -LiteralPath $source -Destination $mods;$archiveArtifacts+=Get-A06Artifact (Join-Path $mods $entry.Key)}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-a06-bob-aluminium-qualification' -Version '0.1.0' -ModsDir $mods|Out-Null;Initialize-MIRSettingsOverrideMod -ModsDir $mods -FactorioVersion '2.1';Set-CopiedStartupSettingDefaults -ModsDir $mods -Overrides @{'ips-enable-research_material_aluminium'=$true;'ips-max-level-research_material_aluminium'=2};Set-CopiedMIRSettingsProfileDefault -ModsDir $mods -Settings @{'ips-enable-research_material_aluminium'=$true;'ips-max-level-research_material_aluminium'=3};Complete-MIRSettingsOverrideMod -ModsDir $mods
$modList=[ordered]@{mods=@('base','elevated-rails','quality','recycler','space-age','more-infinite-research','boblibrary','bobores','bobplates','mir-fixture-assert-a06-bob-aluminium-qualification','mir-validation-settings-overrides')|ForEach-Object{[ordered]@{name=$_;enabled=$true}}};[IO.File]::WriteAllText((Join-Path $mods 'mod-list.json'),(($modList|ConvertTo-Json -Depth 8)+"`n"),[Text.UTF8Encoding]::new($false));$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false));@{name='MIR A06 qualification';description='';tags=@();max_players=1;visibility=@{public=$false;lan=$false};require_user_verification=$false;auto_pause=$false}|ConvertTo-Json -Depth 6|Set-Content -LiteralPath (Join-Path $run 'server-settings.json') -Encoding utf8
function Invoke-A06Engine([string]$Name,[string[]]$Arguments){$factorioLog=Join-Path $userdata 'factorio-current.log';if(Test-Path -LiteralPath $factorioLog){Remove-Item -LiteralPath $factorioLog -Force};$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';foreach($arg in @('--config',(Join-Path $run 'config.ini'),'--no-log-rotation','--disable-audio','--mod-directory',$mods)+$Arguments){$start.ArgumentList.Add($arg)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(120000)){$process.Kill($true);throw "engine timeout during $Name"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run "engine-$Name.log"),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "engine failed during $Name`n$($text.Substring([Math]::Max(0,$text.Length-2500)))"}}finally{$process.Dispose()};Assert-A06 (Test-Path -LiteralPath $factorioLog -PathType Leaf) "Factorio log absent after $Name";$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
function Invoke-A06ServerSave([string]$Name,[string]$InputSave,[string]$ExpectedSave){$factorioLog=Join-Path $userdata 'factorio-current.log';if(Test-Path -LiteralPath $factorioLog){Remove-Item -LiteralPath $factorioLog -Force};$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';foreach($arg in @('--config',(Join-Path $run 'config.ini'),'--no-log-rotation','--disable-audio','--mod-directory',$mods,'--server-settings',(Join-Path $run 'server-settings.json'),'--start-server',$InputSave)){$start.ArgumentList.Add($arg)};$process=[Diagnostics.Process]::Start($start);$ready=$false;try{$deadline=[DateTime]::UtcNow.AddSeconds(45);while([DateTime]::UtcNow -lt $deadline){if($process.HasExited){throw "server exited before $Name save"};if((Test-Path -LiteralPath $factorioLog) -and (Test-Path -LiteralPath $ExpectedSave)){$text=Get-Content -Raw -LiteralPath $factorioLog;if($text.Contains('[mir-a06-bob-aluminium-qualification] STATE stage=cycle') -and $text.Contains('Saving finished')){$ready=$true;break}};Start-Sleep -Milliseconds 200};if(-not $ready){throw "server did not create $Name successor"}}finally{if(-not $process.HasExited){try{$process.Kill($true)}catch{$process.Kill()}};$process.WaitForExit();$process.Dispose()};$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
$initialSave=Join-Path $run 'initial-current-candidate.zip';$createLog=Invoke-A06Engine create @('--create',$initialSave);Assert-A06 (Test-Path -LiteralPath $initialSave -PathType Leaf) 'initial current-candidate save absent.';$createText=Get-Content -Raw -LiteralPath $createLog;$expectedAdmission="[more-infinite-research] Material route admitted recipe=$($dossier.route.recipe) reason=reviewed-forward-route:$($dossier.certificate.id)";$admissionCount=[regex]::Matches($createText,[regex]::Escape($expectedAdmission)).Count;Assert-A06 ($admissionCount -eq 1) "expected one exact certificate admission record, observed $admissionCount";$data=Read-A06Data $createText;$initial=@(Read-A06States $createText|Where-Object{$_.stage -ceq 'initial'});Assert-A06 ($initial.Count -eq 1) 'initial state record differs.'
$cycleOneSave=Join-Path $userdata 'saves/mir-a06-bob-aluminium-cycle-1.zip';$cycleOneLog=Invoke-A06ServerSave cycle-one $initialSave $cycleOneSave;$cycleOne=@(Read-A06States (Get-Content -Raw -LiteralPath $cycleOneLog)|Where-Object{$_.stage -ceq 'cycle'});Assert-A06 ($cycleOne.Count -eq 1) 'cycle-one state record differs.'
$cycleTwoSave=Join-Path $userdata 'saves/mir-a06-bob-aluminium-cycle-2.zip';$cycleTwoLog=Invoke-A06ServerSave cycle-two $cycleOneSave $cycleTwoSave;$cycleTwo=@(Read-A06States (Get-Content -Raw -LiteralPath $cycleTwoLog)|Where-Object{$_.stage -ceq 'cycle'});Assert-A06 ($cycleTwo.Count -eq 1) 'cycle-two state record differs.'
$terminalLog=Invoke-A06Engine terminal @('--benchmark',$cycleTwoSave,'--benchmark-ticks','30000','--benchmark-runs','1','--benchmark-sanitize');$terminalText=Get-Content -Raw -LiteralPath $terminalLog;$terminal=@(Read-A06States $terminalText|Where-Object{$_.stage -ceq 'terminal'});Assert-A06 ($terminal.Count -eq 1) 'terminal state record differs.';$production=Read-A06Production $terminalText
Assert-Exact data.recipe $data.recipe $dossier.route.recipe;Assert-Exact data.machine $data.machine $dossier.route.machine;Assert-Exact data.category $data.category $dossier.route.category;Assert-Exact data.owner $data.owner $dossier.owner.exact_owner_count;Assert-Exact data.change $data.change $dossier.owner.effect_change_per_completed_level;Assert-Exact data.prerequisites ($data.prerequisites -join ',') (@($dossier.progression.prerequisites) -join ',');Assert-Exact data.science ($data.science -join ',') (@($dossier.progression.science) -join ',');Assert-Exact data.lab $data.lab $dossier.progression.lab
Assert-Exact production.raw $production.raw $dossier.cap_transport.raw_direct;Assert-Exact production.imported $production.imported $dossier.cap_transport.mirset1_imported;Assert-Exact production.effective $production.effective $dossier.cap_transport.effective;Assert-Exact production.no4 $production.no_level_four $dossier.cap_transport.no_level_four;Assert-Exact production.alumina $production.alumina $dossier.production.input.'bob-alumina';Assert-Exact production.carbon $production.carbon $dossier.production.input.carbon;Assert-A06 ($production.inputs_exhausted -and $production.output_drained) 'production did not exhaust inputs and drain output.';for($i=0;$i -lt 4;$i++){$actual=@($production.levels)[$i];$expected=@($dossier.production.levels)[$i];Assert-Exact "production level $i" $actual.completed_level $expected.completed_level;Assert-Exact "production output $i" $actual.output $expected.expected_output;Assert-Exact "production bonus $i" $actual.bonus $expected.expected_bonus}
$states=@($initial[0],$cycleOne[0],$cycleTwo[0],$terminal[0]);$expectedGenerations=@(@(0,-1),@(1,0),@(2,1),@(2,1));for($i=0;$i -lt $states.Count;$i++){Assert-Exact "state generation $i" $states[$i].generation $expectedGenerations[$i][0];Assert-Exact "state predecessor $i" $states[$i].predecessor $expectedGenerations[$i][1];Assert-Exact "state bytes $i" $states[$i].stable $states[0].stable};Assert-A06 ($states[0].stable -match 'completed=2\|current-level=3\|current=recipe-prod-research_material_aluminium-1\|queue=recipe-prod-research_material_aluminium-1\|progress=0[.]42\|effect=0[.]02\|earned=0[.]04\|raw=2\|imported=3\|effective=3$') 'serialized state bytes omit the required level-three state.'
$lineage=@([ordered]@{generation=0;save=Get-A06Artifact $initialSave;predecessor=$null},[ordered]@{generation=1;save=Get-A06Artifact $cycleOneSave;predecessor_sha256=(Get-A06Sha $initialSave)},[ordered]@{generation=2;save=Get-A06Artifact $cycleTwoSave;predecessor_sha256=(Get-A06Sha $cycleOneSave)});Assert-Exact lineage.one $lineage[1].predecessor_sha256 $lineage[0].save.raw_sha256;Assert-Exact lineage.two $lineage[2].predecessor_sha256 $lineage[1].save.raw_sha256
$fixtureFiles=@('info.json','data-final-fixes.lua','control.lua','qualification-dossier.json');$result=[ordered]@{schema=1;kind='MIR4A06BobAluminiumQualificationResultV1';status='passed-current-candidate-reload-only';continuity=$dossier.continuity;engine=[ordered]@{version=$engineVersion;executable_sha256=Get-A06Sha $engine};source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=Get-A06Sha (Join-Path $repo 'src/mod/package-source.json');package_source_roots_clean=$sourceRootClean;bounded_dirty_a06_sources=$boundedDirtyA06Sources;dirty_source_paths=$sourceChangePaths};candidate=Get-A06Artifact $candidateZip;mod_archives=$archiveArtifacts;fixture=[ordered]@{path='fixtures/assert-a06-bob-aluminium-qualification';files=@($fixtureFiles|ForEach-Object{Get-A06Artifact (Join-Path $fixture $_)})};harness=Get-A06Artifact $PSCommandPath;settings_override=Get-A06Artifact (Join-Path $mods 'mir-validation-settings-overrides_0.1.0.zip');data=$data;production=$production;state_bytes=$states[0].stable;state_records=$states;save_lineage=$lineage;logs=[ordered]@{create=Get-A06Artifact $createLog;cycle_one=Get-A06Artifact $cycleOneLog;cycle_two=Get-A06Artifact $cycleTwoLog;terminal=Get-A06Artifact $terminalLog};non_claims=@($dossier.explicit_non_claims)};$resultPath=Join-Path $run 'result.json';[IO.File]::WriteAllText($resultPath,(($result|ConvertTo-Json -Depth 30)+"`n"),[Text.UTF8Encoding]::new($false));$result|ConvertTo-Json -Depth 30;Write-Output "Evidence: $run"
