# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$AngelModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-angel-tin-final-state-audit'
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path
$engine=(Resolve-Path -LiteralPath $FactorioBin).Path
$modsRoot=(Resolve-Path -LiteralPath $AngelModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot))
if(-not $output.StartsWith((Join-Path $repo 'build')+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)) { throw 'Test outputs must be under build.' }
$expectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$engineSha256=(Get-FileHash -LiteralPath $engine -Algorithm SHA256).Hash
if($engineSha256 -cne $expectedEngineSha256) { throw "Angel Tin final-state audit requires exact F210 engine SHA-256 $expectedEngineSha256." }
$version=(& $engine --version|Out-String)
if($LASTEXITCODE -ne 0 -or $version -notmatch 'Version: 2[.]1[.]17') { throw 'Angel Tin final-state audit requires Steam F210 2.1.17.' }
$engineVersion=([regex]::Match($version,'Version:\s+2[.]1[.]17[^\r\n]*').Value).Trim()
if([string]::IsNullOrWhiteSpace($engineVersion)) { throw 'Angel Tin final-state audit could not bind the exact F210 engine version.' }
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim()
$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim()
if($sourceCommit -notmatch '^[0-9a-f]{40}$' -or $sourceTree -notmatch '^[0-9a-f]{40}$') { throw 'Angel Tin audit requires nonempty 40-hex source commit and tree bindings.' }
$sourceChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod)
if($sourceChanges.Count -ne 0) { throw "Angel Tin audit refuses a changed package-source root: $($sourceChanges -join '; ')" }
$packageSource=Join-Path $repo 'src/mod/package-source.json'
$fixture=Join-Path $repo 'fixtures/assert-angel-tin-final-state-audit'
$dossier=Join-Path $fixture 'route-dossier.json'
$expectedArchives=[ordered]@{
  'angelsrefining_2.1.2.zip'='AF5E79E35E591F68D52F13EDA082950E10AC98A4B7722B3F568D0211E3FEB813'
  'angelsrefininggraphics_2.1.0.zip'='79F373BC628F619EDE3B1875827172390D2C3F5EAB56310F6F1572C4553CB6EF'
  'angelspetrochem_2.1.2.zip'='9B4CC14156CF16C9F41784108CCA5E767180A7330B1AF23A387231653CE10A49'
  'angelspetrochemgraphics_2.1.0.zip'='DECDC2FCD5BBBDEF70784943C142C30FAA7294B98E814296C5D44D09A9DE4790'
  'angelssmelting_2.1.1.zip'='1DFCDD77D075FD545CFEE74BD8A6443E7E90B133D3832FDD47649C84892243A9'
  'angelssmeltinggraphics_2.1.0.zip'='EBEF8D1F6F13F84B242DF295CE9FAB9618ED90B4C52852A0B4345908A88D5D35'
}
function Assert-Exact([string]$Name,$Actual,$Expected) { if($Actual -cne $Expected) { throw "Angel Tin dossier $Name differs: expected '$Expected', actual '$Actual'." } }
function Assert-Props([string]$Name,$Object,[string[]]$Expected) {
  if($null -eq $Object) { throw "Angel Tin dossier $Name is absent." }
  $actual=@($Object.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object)
  if($actual.Count -ne $wanted.Count -or (@(Compare-Object -CaseSensitive $actual $wanted)).Count -ne 0) { throw "Angel Tin dossier $Name properties differ." }
}
function Assert-Array([string]$Name,$Actual,[string[]]$Expected) {
  $actual=@($Actual|ForEach-Object {[string]$_});if($actual.Count -ne $Expected.Count -or (@(Compare-Object -CaseSensitive $actual $Expected)).Count -ne 0) { throw "Angel Tin dossier $Name differs." }
}
try {$record=Get-Content -Raw -LiteralPath $dossier|ConvertFrom-Json -ErrorAction Stop} catch { throw "Angel Tin dossier is not valid JSON: $($_.Exception.Message)" }
Assert-Props root $record @('schema','kind','scope','target','archive_closure','no_bob_mods','source_emission_target','final_output_identities','final_plate_recipes','declared_tin_transformations','declared_transformation_state','ordinary_acquisition_routes','ordinary_acquisition_disposition','category','conditional_crafting_category_capability','productivity','side_paths','science_lab_frontier','observed_disposition','evidence_role','explicit_non_claims')
Assert-Exact schema $record.schema 1;Assert-Exact kind $record.kind 'MIR4AngelTinFinalStateAuditV1';Assert-Exact scope $record.scope 'F210 Angel-only final Tin state diagnostic audit; package-excluded evidence'
Assert-Props target $record.target @('factorio_line','factorio_version','engine_sha256');Assert-Exact target.factorio_line $record.target.factorio_line '2.1';Assert-Exact target.factorio_version $record.target.factorio_version '2.1.17';Assert-Exact target.engine_sha256 $record.target.engine_sha256 $expectedEngineSha256
if(@($record.archive_closure).Count -ne $expectedArchives.Count) { throw 'Angel Tin dossier archive closure count differs.' }
foreach($entry in @($record.archive_closure)) { Assert-Props archive $entry @('name','version','sha256');$file=($expectedArchives.Keys|Where-Object {$_ -like "$($entry.name)_$($entry.version).zip"});if(@($file).Count -ne 1) {throw "Angel Tin dossier archive identity differs $($entry.name)"};Assert-Exact "archive.$($entry.name).sha256" $entry.sha256 $expectedArchives[$file] }
Assert-Exact no_bob_mods $record.no_bob_mods $true;Assert-Exact source_emission_target $record.source_emission_target 'bob-tin-plate';Assert-Array final_output_identities $record.final_output_identities @('angels-plate-tin');Assert-Array final_plate_recipes $record.final_plate_recipes @('angels-plate-tin','angels-plate-tin-2');$transformations=@('angels-processed-tin','angels-pellet-tin','angels-ingot-tin','angels-ingot-tin-2','angels-ingot-tin-3','angels-liquid-molten-tin','angels-roll-tin','angels-roll-tin-2','angels-plate-tin','angels-plate-tin-2');Assert-Array declared_tin_transformations $record.declared_tin_transformations $transformations;Assert-Props declared_transformation_state $record.declared_transformation_state @('recipes','enabled','hidden','category','category_disposition','auto_recycle');Assert-Array declared_transformation_state.recipes $record.declared_transformation_state.recipes $transformations;Assert-Exact declared_transformation_state.enabled $record.declared_transformation_state.enabled $false;Assert-Exact declared_transformation_state.hidden $record.declared_transformation_state.hidden $true;if($null -ne $record.declared_transformation_state.category){throw 'Angel Tin dossier explicit route category must be null.'};Assert-Exact declared_transformation_state.category_disposition $record.declared_transformation_state.category_disposition 'implicit-crafting';Assert-Exact declared_transformation_state.auto_recycle $record.declared_transformation_state.auto_recycle $false;Assert-Array ordinary_acquisition_routes $record.ordinary_acquisition_routes @();Assert-Exact ordinary_acquisition_disposition $record.ordinary_acquisition_disposition 'unsupported-no-producer-for-angels-tin-ore';Assert-Exact category $record.category 'implicit-crafting';Assert-Props conditional_crafting_category_capability $record.conditional_crafting_category_capability @('category','entities','not_a_reachable_route');Assert-Exact conditional_crafting_category_capability.category $record.conditional_crafting_category_capability.category 'implicit-crafting';Assert-Array conditional_crafting_category_capability.entities $record.conditional_crafting_category_capability.entities @('assembling-machine-1','assembling-machine-2','assembling-machine-3');Assert-Exact conditional_crafting_category_capability.not_a_reachable_route $record.conditional_crafting_category_capability.not_a_reachable_route $true
Assert-Props productivity $record.productivity @('permission_recipes','native_owner_technologies','mir_owner_technology','disposition');Assert-Array productivity.permission_recipes $record.productivity.permission_recipes @('angels-plate-tin','angels-plate-tin-2');Assert-Array productivity.native_owner_technologies $record.productivity.native_owner_technologies @();if($null -ne $record.productivity.mir_owner_technology) {throw 'Angel Tin dossier MIR owner must be null.'};Assert-Exact productivity.disposition $record.productivity.disposition 'permission-present-without-native-or-mir-owner'
Assert-Props side_paths $record.side_paths @('plate_to_ore_recycling_or_return_paths','catalyst_paths','transformation_byproducts');Assert-Array side_paths.plate_to_ore_recycling_or_return_paths $record.side_paths.plate_to_ore_recycling_or_return_paths @();Assert-Array side_paths.catalyst_paths $record.side_paths.catalyst_paths @();if(@($record.side_paths.transformation_byproducts).Count -ne 1){throw 'Angel Tin dossier transformation byproduct count differs.'};$byproduct=@($record.side_paths.transformation_byproducts)[0];Assert-Props side_paths.transformation_byproducts $byproduct @('recipe','product','amount');Assert-Exact byproduct.recipe $byproduct.recipe 'angels-roll-tin-2';Assert-Exact byproduct.product $byproduct.product 'angels-liquid-coolant-used';Assert-Exact byproduct.amount $byproduct.amount 40
Assert-Props science_lab_frontier $record.science_lab_frontier @('technology','science','lab','enabled','hidden','reachable');Assert-Exact science_lab_frontier.technology $record.science_lab_frontier.technology 'angels-tin-smelting-1';Assert-Array science_lab_frontier.science $record.science_lab_frontier.science @('automation-science-pack');Assert-Exact science_lab_frontier.lab $record.science_lab_frontier.lab 'lab';Assert-Exact science_lab_frontier.enabled $record.science_lab_frontier.enabled $false;Assert-Exact science_lab_frontier.hidden $record.science_lab_frontier.hidden $true;Assert-Exact science_lab_frontier.reachable $record.science_lab_frontier.reachable $false;Assert-Exact evidence_role $record.evidence_role 'bounded diagnostic input to A06 BA-07 A17 and PROG-01; not completion authority';Assert-Exact observed_disposition $record.observed_disposition 'diagnostic-unsupported-no-ordinary-acquisition-or-productivity-owner';Assert-Array explicit_non_claims $record.explicit_non_claims @('Bob-plus-Angel','F200','Angel-productivity-support-or-admission','PIPE-01','infinite-continuation','weighted-balance','full-BA-07-or-PROG-01','release-readiness','upgrade-or-persisted-save-recovery')
. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1')
. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)) {$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('ANGEL-TIN-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/angel-tin-audit/packages';$CandidateZip=[string]$candidate.archive_path}
$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try {$forbidden=@($zip.Entries|Where-Object {$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "Candidate includes package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';New-Item -ItemType Directory -Force -Path $mods,(Join-Path $run 'userdata')|Out-Null
Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveHashes=[ordered]@{};foreach($entry in $expectedArchives.GetEnumerator()) {$path=Join-Path $modsRoot $entry.Key;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Angel archive missing $path"};$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;if($hash -cne $entry.Value){throw "Angel archive hash differs $($entry.Key)"};$archiveHashes[$entry.Key]=$hash;Copy-Item -LiteralPath $path -Destination $mods}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-angel-tin-final-state-audit' -Version '0.1.0' -ModsDir $mods|Out-Null
@{mods=@(@{name='base';enabled=$true},@{name='space-age';enabled=$false},@{name='elevated-rails';enabled=$false},@{name='quality';enabled=$false},@{name='recycler';enabled=$false},@{name='more-infinite-research';enabled=$true},@{name='angelsrefining';enabled=$true},@{name='angelsrefininggraphics';enabled=$true},@{name='angelspetrochem';enabled=$true},@{name='angelspetrochemgraphics';enabled=$true},@{name='angelssmelting';enabled=$true},@{name='angelssmeltinggraphics';enabled=$true},@{name='mir-fixture-assert-angel-tin-final-state-audit';enabled=$true})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $mods 'mod-list.json') -Encoding utf8
$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false))
$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--mod-directory',$mods,'--create',(Join-Path $run 'audit.zip'))){$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(120000)){$process.Kill($true);throw "Angel Tin audit timed out $run"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run 'engine.log'),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "Angel Tin audit engine failed: $run`n$($text.Substring([Math]::Max(0,$text.Length-2500)))"}}finally{$process.Dispose()}
$log=Join-Path $run 'userdata/factorio-current.log';if(-not(Test-Path -LiteralPath $log -PathType Leaf)){throw 'Angel Tin audit Factorio log is absent.'};$logText=Get-Content -Raw -LiteralPath $log;if($logText -notmatch [regex]::Escape('[mir-angel-tin-audit] DATA PASS final=angels-plate-tin ordinary-acquisition=0 productivity-owner=none frontier-reachable=false')){throw 'Angel Tin audit data assertion is absent.'};if($logText -notmatch [regex]::Escape('[mir-angel-tin-audit] RUNTIME PASS diagnostic-only-no-owner')){throw 'Angel Tin audit runtime assertion is absent.'}
$result=[ordered]@{schema=1;status='passed';scope='F210 Angel-only final Tin state diagnostic audit';target='F210';engine_version=$engineVersion;engine_sha256=$engineSha256;source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=(Get-FileHash -LiteralPath $packageSource -Algorithm SHA256).Hash;package_source_roots_clean=$true};candidate_sha256=(Get-FileHash -LiteralPath $candidateZip -Algorithm SHA256).Hash;candidate_package_excludes_fixture_test_docs_mir_build_dist=$true;angel_archive_sha256=$archiveHashes;dossier_sha256=(Get-FileHash -LiteralPath $dossier -Algorithm SHA256).Hash;fixture_hashes=[ordered]@{info=(Get-FileHash (Join-Path $fixture 'info.json') -Algorithm SHA256).Hash;dossier=(Get-FileHash $dossier -Algorithm SHA256).Hash;data_final_fixes=(Get-FileHash (Join-Path $fixture 'data-final-fixes.lua') -Algorithm SHA256).Hash;control=(Get-FileHash (Join-Path $fixture 'control.lua') -Algorithm SHA256).Hash};harness_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;observed_disposition=[string]$record.observed_disposition;ordinary_acquisition_routes=@();productivity_owner=[ordered]@{native=@();mir=$null};log_sha256=(Get-FileHash -LiteralPath $log -Algorithm SHA256).Hash;non_claims=@($record.explicit_non_claims)}
$result|ConvertTo-Json -Depth 10|Set-Content -LiteralPath (Join-Path $run 'result.json') -Encoding utf8;$result|ConvertTo-Json -Depth 10;Write-Output "Evidence: $run"
