# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$BobModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-bob-tin-progression-frontier',
  [switch]$Probe
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path
$engine=(Resolve-Path -LiteralPath $FactorioBin).Path
$bobMods=(Resolve-Path -LiteralPath $BobModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot))
if(-not $output.StartsWith((Join-Path $repo 'build')+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Bob Tin progression-frontier outputs must be under build.'}
$expectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$expectedArchives=[ordered]@{
  boblibrary=[ordered]@{file='boblibrary_3.0.0.zip';version='3.0.0';sha256='49EAE2D4D8E58EBD28BAFDB7E71D5307CBCE2077E0642440ED7EC527D466FFC4'}
  bobores=[ordered]@{file='bobores_3.0.0.zip';version='3.0.0';sha256='7F8E33E35F59BB3F2CD72E3AB2FED30D1C2AE9C117E3731324AC307D9965082B'}
  bobplates=[ordered]@{file='bobplates_3.0.1.zip';version='3.0.1';sha256='503D7BF6E88DA1F99463AC00CEC959C2003B2701D80DC4A564CF2EC3920AC8AF'}
}
$expectedOfficialMods=@('base','elevated-rails','quality','recycler','space-age')
$expectedNonClaims=@('companion-stable-id-allocation-or-emission','infinite-continuation-support','progression-completion','migration-or-save-state-transfer','F200','Angel-or-combined-Bob-Angel-admission','multiplayer','research-browser','full-cross-target-parity','full-BA-07-or-PROG-01','release-readiness')
function Assert-Exact([string]$Name,$Actual,$Expected){if($null -eq $Actual -and $null -eq $Expected){return};if($null -eq $Actual -or $null -eq $Expected -or $Actual -cne $Expected){throw "Bob Tin progression-frontier $Name differs: expected '$Expected', actual '$Actual'."}}
function Assert-Props([string]$Name,$Object,[string[]]$Expected){if($null -eq $Object){throw "Bob Tin progression-frontier $Name is absent."};$actual=@($Object.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object);if(($actual -join "`n") -cne ($wanted -join "`n")){throw "Bob Tin progression-frontier $Name properties differ."}}
function Assert-Array([string]$Name,$Actual,[string[]]$Expected){$values=@($Actual|ForEach-Object{[string]$_});if(($values -join "`n") -cne ($Expected -join "`n")){throw "Bob Tin progression-frontier $Name differs."}}
function ConvertTo-CanonicalValue($Value){
  if($null -eq $Value){return $null}
  if($Value -is [System.Collections.IDictionary]){$out=[ordered]@{};foreach($key in @($Value.Keys|ForEach-Object {[string]$_}|Sort-Object)){$out[$key]=ConvertTo-CanonicalValue $Value[$key]};return $out}
  if($Value -is [pscustomobject]){$out=[ordered]@{};foreach($property in @($Value.PSObject.Properties.Name|Sort-Object)){$out[$property]=ConvertTo-CanonicalValue $Value.$property};return $out}
  if($Value -is [System.Collections.IEnumerable] -and -not ($Value -is [string])){return @($Value|ForEach-Object {ConvertTo-CanonicalValue $_})}
  return $Value
}
function ConvertTo-CanonicalJson($Value){return (ConvertTo-CanonicalValue $Value|ConvertTo-Json -Depth 50 -Compress)}
function Assert-Canonical([string]$Name,$Actual,$Expected){if((ConvertTo-CanonicalJson $Actual) -cne (ConvertTo-CanonicalJson $Expected)){throw "Bob Tin progression-frontier $Name differs."}}
function Get-FrontierObservation([string]$Text,[string]$Kind){
  $found=[regex]::Matches($Text,"\[mir-bob-tin-progression-frontier\] $Kind JSON (?<json>\{[^`r`n]+\})")
  if($found.Count -ne 1){throw "Bob Tin progression-frontier requires exactly one $Kind JSON record; observed $($found.Count)."}
  try{return ($found[0].Groups['json'].Value|ConvertFrom-Json -ErrorAction Stop)}catch{throw "Bob Tin progression-frontier $Kind JSON is invalid: $($_.Exception.Message)"}
}
function Assert-Dossier($Record){
  Assert-Props root $Record @('schema','kind','scope','target','official_mod_closure','archive_closure','anchor','runtime_binding','science_lab_frontier','companion_continuation','evidence_role','explicit_non_claims')
  Assert-Exact schema $Record.schema 1;Assert-Exact kind $Record.kind 'MIR4BobTinProgressionFrontierV1';Assert-Exact scope $Record.scope 'F210 exact Bob-only Tin science and lab progression-frontier diagnostic; package-excluded evidence';Assert-Exact evidence_role $Record.evidence_role 'bounded diagnostic input to A17 X04 BA-07 and PROG-01; not progression or continuation completion authority';Assert-Array explicit_non_claims $Record.explicit_non_claims $expectedNonClaims
  Assert-Props target $Record.target @('factorio_line','factorio_version','engine_sha256');Assert-Exact target.factorio_line $Record.target.factorio_line '2.1';Assert-Exact target.factorio_version $Record.target.factorio_version '2.1.17';Assert-Exact target.engine_sha256 $Record.target.engine_sha256 $expectedEngineSha256
  if(@($Record.official_mod_closure).Count -ne $expectedOfficialMods.Count){throw 'Bob Tin progression-frontier official closure count differs.'};for($index=0;$index -lt $expectedOfficialMods.Count;$index++){Assert-Props "official_mod_closure[$index]" @($Record.official_mod_closure)[$index] @('name','enabled');Assert-Exact "official_mod_closure[$index].name" @($Record.official_mod_closure)[$index].name $expectedOfficialMods[$index];Assert-Exact "official_mod_closure[$index].enabled" @($Record.official_mod_closure)[$index].enabled $true}
  if(@($Record.archive_closure).Count -ne $expectedArchives.Count){throw 'Bob Tin progression-frontier archive closure count differs.'};$seen=@{};foreach($entry in @($Record.archive_closure)){Assert-Props archive $entry @('name','version','sha256');if(-not $expectedArchives.Contains($entry.name) -or $seen.Contains($entry.name)){throw "Bob Tin progression-frontier archive identity differs $($entry.name)"};$seen[$entry.name]=$true;Assert-Exact "archive.$($entry.name).version" $entry.version $expectedArchives[$entry.name].version;Assert-Exact "archive.$($entry.name).sha256" $entry.sha256 $expectedArchives[$entry.name].sha256};if($seen.Count -ne $expectedArchives.Count){throw 'Bob Tin progression-frontier archive closure is incomplete.'}
  Assert-Props anchor $Record.anchor @('stream_key','technology','effect_type','effect_recipe','effect_change_per_completed_level','exact_owner_count','prototype_max_level','prerequisites','science_ingredients','cap_transport');Assert-Exact anchor.stream_key $Record.anchor.stream_key 'research_material_tin';Assert-Exact anchor.technology $Record.anchor.technology 'recipe-prod-research_material_tin-1';Assert-Exact anchor.effect_type $Record.anchor.effect_type 'change-recipe-productivity';Assert-Exact anchor.effect_recipe $Record.anchor.effect_recipe 'bob-tin-plate';Assert-Exact anchor.effect_change $Record.anchor.effect_change_per_completed_level 0.02;Assert-Exact anchor.owner_count $Record.anchor.exact_owner_count 1;Assert-Exact anchor.max_level $Record.anchor.prototype_max_level 'infinite';Assert-Props anchor.cap_transport $Record.anchor.cap_transport @('raw_direct_max_level','mirset1_imported_max_level','effective_max_level');Assert-Exact anchor.cap.raw $Record.anchor.cap_transport.raw_direct_max_level 2;Assert-Exact anchor.cap.imported $Record.anchor.cap_transport.mirset1_imported_max_level 3;Assert-Exact anchor.cap.effective $Record.anchor.cap_transport.effective_max_level 3
  Assert-Props runtime_binding $Record.runtime_binding @('native_infinite_max_level_sentinel','maximum_level_policy_binding_count');Assert-Exact runtime_binding.native_infinite_max_level_sentinel $Record.runtime_binding.native_infinite_max_level_sentinel 4294967295;Assert-Exact runtime_binding.maximum_level_policy_binding_count $Record.runtime_binding.maximum_level_policy_binding_count 1;Assert-Props science_lab_frontier $Record.science_lab_frontier @('candidate_selection_rule','raw_recipe_enabled_semantics','candidate_science_packs','present_non_hidden_lab_prototypes','anchor_compatible_present_non_hidden_lab_ids');Assert-Exact science_lab_frontier.candidate_selection_rule $Record.science_lab_frontier.candidate_selection_rule 'all-final-technology-unit-ingredients-with-exact-item-or-tool-prototype-binding';Assert-Exact science_lab_frontier.raw_recipe_enabled_semantics $Record.science_lab_frontier.raw_recipe_enabled_semantics 'enabled-not-false';foreach($pack in @($Record.science_lab_frontier.candidate_science_packs)){Assert-Props candidate_science_pack $pack @('name','prototype_type','producer_recipe_ids','default_enabled_producer_recipe_ids','direct_unlock_technology_ids');if([string]::IsNullOrWhiteSpace($pack.name) -or $pack.prototype_type -notin @('item','tool')){throw 'Bob Tin progression-frontier candidate technology-unit ingredient identity differs.'}};foreach($lab in @($Record.science_lab_frontier.present_non_hidden_lab_prototypes)){Assert-Props present_non_hidden_lab $lab @('id','inputs');if([string]::IsNullOrWhiteSpace($lab.id)){throw 'Bob Tin progression-frontier present lab identity differs.'}};Assert-Props companion_continuation $Record.companion_continuation @('stable_id_allocation','emission','reason');Assert-Exact companion.stable_id_allocation $Record.companion_continuation.stable_id_allocation 'blocked';Assert-Exact companion.emission $Record.companion_continuation.emission 'blocked';Assert-Exact companion.reason $Record.companion_continuation.reason 'diagnostic-establishes-inputs-only'
}
function Assert-Observation($Data,$Runtime,$Record){
  Assert-Props data $Data @('anchor','science_lab_frontier','companion_continuation');Assert-Canonical observed.anchor $Data.anchor $Record.anchor;Assert-Canonical observed.science_lab_frontier $Data.science_lab_frontier $Record.science_lab_frontier;Assert-Canonical observed.companion_continuation $Data.companion_continuation $Record.companion_continuation
  Assert-Props runtime $Runtime @('technology','prototype_max_level','native_prototype_max_level','raw_direct_max_level','mirset1_imported_max_level','effective_max_level','policy_technology','policy_setting','policy_selected','policy_binding_count','force_next_level');Assert-Exact runtime.technology $Runtime.technology $Record.anchor.technology;Assert-Exact runtime.prototype_max_level $Runtime.prototype_max_level $Record.anchor.prototype_max_level;Assert-Exact runtime.native_prototype_max_level $Runtime.native_prototype_max_level $Record.runtime_binding.native_infinite_max_level_sentinel;Assert-Exact runtime.raw $Runtime.raw_direct_max_level $Record.anchor.cap_transport.raw_direct_max_level;Assert-Exact runtime.imported $Runtime.mirset1_imported_max_level $Record.anchor.cap_transport.mirset1_imported_max_level;Assert-Exact runtime.effective $Runtime.effective_max_level $Record.anchor.cap_transport.effective_max_level;Assert-Exact runtime.policy_technology $Runtime.policy_technology $Record.anchor.technology;Assert-Exact runtime.policy_setting $Runtime.policy_setting ('ips-max-level-'+$Record.anchor.stream_key);Assert-Exact runtime.policy_selected $Runtime.policy_selected $Record.anchor.cap_transport.effective_max_level;Assert-Exact runtime.policy_binding_count $Runtime.policy_binding_count $Record.runtime_binding.maximum_level_policy_binding_count;if([int]$Runtime.force_next_level -lt 1){throw 'Bob Tin progression-frontier runtime force level is invalid.'}
}
function Assert-DriftNegatives($Data,$Runtime,$Record){
  $drift=$Data|ConvertTo-Json -Depth 50|ConvertFrom-Json;$drift.anchor.effect_change_per_completed_level=0.03;$caught=$false;try{Assert-Observation $drift $Runtime $Record}catch{$caught=$true};if(-not $caught){throw 'Bob Tin progression-frontier accepted stale data observation.'}
  $frontierDrift=$Data|ConvertTo-Json -Depth 50|ConvertFrom-Json;$frontierDrift.science_lab_frontier.candidate_science_packs[0].direct_unlock_technology_ids=@('frontier-drift');$caught=$false;try{Assert-Observation $frontierDrift $Runtime $Record}catch{$caught=$true};if(-not $caught){throw 'Bob Tin progression-frontier accepted stale nested science-frontier observation.'}
  $driftRuntime=$Runtime|ConvertTo-Json -Depth 50|ConvertFrom-Json;$driftRuntime.policy_selected=4;$caught=$false;try{Assert-Observation $Data $driftRuntime $Record}catch{$caught=$true};if(-not $caught){throw 'Bob Tin progression-frontier accepted stale runtime observation.'}
  $fixtureSource=Get-Content -Raw -LiteralPath (Join-Path $repo 'fixtures/assert-bob-tin-progression-frontier/data-final-fixes.lua');if($fixtureSource -match 'recipe[.]enabled\s*==\s*true' -or $fixtureSource -notmatch 'recipe[.]enabled\s*~=\s*false'){throw 'Bob Tin progression-frontier raw default-enabled normalization drifted.'};if($fixtureSource -match 'string[.]match\(name, "%-science%-pack[$]"\)' -or $fixtureSource -notmatch 'all-final-technology-unit-ingredients-with-exact-item-or-tool-prototype-binding'){throw 'Bob Tin progression-frontier technology-unit ingredient selection rule drifted.'};$controlSource=Get-Content -Raw -LiteralPath (Join-Path $repo 'fixtures/assert-bob-tin-progression-frontier/control.lua');$cardinalityGuard='if #tin_bindings ~= 1 then fail("Tin maximum-level policy binding cardinality differs " .. tostring(#tin_bindings)) end';$consistencyGuard='if binding.technology ~= anchor_name or binding.setting ~= setting_name or binding.selected ~= effective or binding.selected ~= imported then';foreach($guard in @($cardinalityGuard,$consistencyGuard)){$withoutGuard=$controlSource.Replace($guard,'');$caught=$false;try{if($withoutGuard -notmatch [regex]::Escape($guard)){throw 'Bob Tin progression-frontier missing maximum-level policy guard.'}}catch{$caught=$true};if(-not $caught){throw 'Bob Tin progression-frontier accepted missing maximum-level policy guard.'};if($controlSource -notmatch [regex]::Escape($guard)){throw 'Bob Tin progression-frontier maximum-level policy guard drifted.'}};$source=Get-Content -Raw -LiteralPath $PSCommandPath;if($source -match "candidate_science_packs=@\(" -or $source -match "present_non_hidden_lab_prototypes=@\("){throw 'Bob Tin progression-frontier receipt must derive frontier observations from runtime logs.'}
}

$engineSha256=(Get-FileHash -LiteralPath $engine -Algorithm SHA256).Hash
if($engineSha256 -cne $expectedEngineSha256){throw "Bob Tin progression-frontier requires exact F210 engine SHA-256 $expectedEngineSha256."}
$version=(& $engine --version|Out-String);if($LASTEXITCODE -ne 0 -or $version -notmatch 'Version: 2[.]1[.]17'){throw 'Bob Tin progression-frontier requires exact Steam F210 2.1.17.'}
$engineVersion=([regex]::Match($version,'Version:\s+2[.]1[.]17[^\r\n]*').Value).Trim();if([string]::IsNullOrWhiteSpace($engineVersion)){throw 'Bob Tin progression-frontier could not bind engine version.'}
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim();$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim();if($sourceCommit -notmatch '^[0-9a-f]{40}$' -or $sourceTree -notmatch '^[0-9a-f]{40}$'){throw 'Bob Tin progression-frontier requires exact source commit/tree bindings.'}
$sourceChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod);if($sourceChanges.Count -ne 0){throw "Bob Tin progression-frontier refuses a changed package-source root: $($sourceChanges -join '; ')"}
$fixture=Join-Path $repo 'fixtures/assert-bob-tin-progression-frontier';$dossier=Join-Path $fixture 'progression-frontier-dossier.json';$packageSource=Join-Path $repo 'src/mod/package-source.json'
try{$record=Get-Content -Raw -LiteralPath $dossier|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Tin progression-frontier dossier JSON is invalid: $($_.Exception.Message)"};Assert-Dossier $record

. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1')
. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1')
. (Join-Path $repo 'tools/lib/validation/SettingsOverrides.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)){$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('BOB-TIN-PROGRESSION-FRONTIER-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/bob-tin-progression-frontier/packages';$CandidateZip=[string]$candidate.archive_path}
$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try{$forbidden=@($zip.Entries|Where-Object {$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "Candidate includes package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';New-Item -ItemType Directory -Force -Path $mods,(Join-Path $run 'userdata')|Out-Null;Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveHashes=[ordered]@{};foreach($name in $expectedArchives.Keys){$path=Join-Path $bobMods $expectedArchives[$name].file;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Bob Tin progression-frontier archive is absent $path"};$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;if($hash -cne $expectedArchives[$name].sha256){throw "Bob Tin progression-frontier archive hash differs $name"};$archiveHashes[$name]=$hash;Copy-Item -LiteralPath $path -Destination $mods}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-bob-tin-progression-frontier' -Version '0.1.0' -ModsDir $mods|Out-Null
Initialize-MIRSettingsOverrideMod -ModsDir $mods -FactorioVersion '2.1';Set-CopiedStartupSettingDefaults -ModsDir $mods -Overrides @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=2};Set-CopiedMIRSettingsProfileDefault -ModsDir $mods -Settings @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=3};Complete-MIRSettingsOverrideMod -ModsDir $mods
@{mods=@(@{name='base';enabled=$true},@{name='space-age';enabled=$true},@{name='elevated-rails';enabled=$true},@{name='quality';enabled=$true},@{name='recycler';enabled=$true},@{name='more-infinite-research';enabled=$true},@{name='boblibrary';enabled=$true},@{name='bobores';enabled=$true},@{name='bobplates';enabled=$true},@{name='mir-fixture-assert-bob-tin-progression-frontier';enabled=$true},@{name='mir-validation-settings-overrides';enabled=$true})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $mods 'mod-list.json') -Encoding utf8
$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false))
function Invoke-FrontierEngine([string]$Name,[string[]]$Arguments){$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--mod-directory',$mods)+$Arguments){[void]$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(120000)){$process.Kill($true);throw "Bob Tin progression-frontier engine timeout: $run"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run "engine-$Name.log"),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "Bob Tin progression-frontier engine failed during ${Name}: $run`n$($text.Substring([Math]::Max(0,$text.Length-2500)))"}}finally{$process.Dispose()};$factorioLog=Join-Path $run 'userdata/factorio-current.log';if(-not(Test-Path -LiteralPath $factorioLog -PathType Leaf)){throw "Bob Tin progression-frontier Factorio log is absent after $Name."};$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
$save=Join-Path $run 'bob-tin-progression-frontier.zip';$createLog=Invoke-FrontierEngine -Name create -Arguments @('--create',$save);if(-not(Test-Path -LiteralPath $save -PathType Leaf)){throw 'Bob Tin progression-frontier save was not created.'};$data=Get-FrontierObservation (Get-Content -Raw -LiteralPath $createLog) 'DATA'
if($Probe){$data|ConvertTo-Json -Depth 50;Write-Output "Evidence: $run";return}
$runtimeLog=Invoke-FrontierEngine -Name runtime -Arguments @('--benchmark',$save,'--benchmark-ticks','60','--benchmark-runs','1');$runtime=Get-FrontierObservation (Get-Content -Raw -LiteralPath $runtimeLog) 'RUNTIME';Assert-Observation $data $runtime $record;Assert-DriftNegatives $data $runtime $record
$receipt=[ordered]@{schema=1;status='passed';scope=$record.scope;target='F210';engine_version=$engineVersion;engine_sha256=$engineSha256;source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=(Get-FileHash -LiteralPath $packageSource -Algorithm SHA256).Hash;package_source_roots_clean=$true};candidate_sha256=(Get-FileHash -LiteralPath $candidateZip -Algorithm SHA256).Hash;candidate_package_excludes_fixture_test_docs_mir_build_dist=$true;official_mod_closure=$record.official_mod_closure;bob_archive_sha256=$archiveHashes;dossier_sha256=(Get-FileHash -LiteralPath $dossier -Algorithm SHA256).Hash;fixture_hashes=[ordered]@{info=(Get-FileHash (Join-Path $fixture 'info.json') -Algorithm SHA256).Hash;dossier=(Get-FileHash $dossier -Algorithm SHA256).Hash;data_final_fixes=(Get-FileHash (Join-Path $fixture 'data-final-fixes.lua') -Algorithm SHA256).Hash;control=(Get-FileHash (Join-Path $fixture 'control.lua') -Algorithm SHA256).Hash};harness_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;anchor=$data.anchor;science_lab_frontier=$data.science_lab_frontier;companion_continuation=$data.companion_continuation;runtime=$runtime;logs=[ordered]@{create=(Get-FileHash -LiteralPath $createLog -Algorithm SHA256).Hash;runtime=(Get-FileHash -LiteralPath $runtimeLog -Algorithm SHA256).Hash};non_claims=$expectedNonClaims}
$receipt|ConvertTo-Json -Depth 50|Set-Content -LiteralPath (Join-Path $run 'result.json') -Encoding utf8;$receipt|ConvertTo-Json -Depth 50;Write-Output "Evidence: $run"
