# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$CombinedModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-bob-angel-tin-final-state-audit'
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path
$engine=(Resolve-Path -LiteralPath $FactorioBin).Path
$modsRoot=(Resolve-Path -LiteralPath $CombinedModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot))
if(-not $output.StartsWith((Join-Path $repo 'build')+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)) { throw 'Test outputs must be under build.' }
$expectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$expectedArchives=[ordered]@{
  'boblibrary_3.0.0.zip'='49EAE2D4D8E58EBD28BAFDB7E71D5307CBCE2077E0642440ED7EC527D466FFC4'
  'bobores_3.0.0.zip'='7F8E33E35F59BB3F2CD72E3AB2FED30D1C2AE9C117E3731324AC307D9965082B'
  'bobplates_3.0.1.zip'='503D7BF6E88DA1F99463AC00CEC959C2003B2701D80DC4A564CF2EC3920AC8AF'
  'angelsrefining_2.1.2.zip'='AF5E79E35E591F68D52F13EDA082950E10AC98A4B7722B3F568D0211E3FEB813'
  'angelsrefininggraphics_2.1.0.zip'='79F373BC628F619EDE3B1875827172390D2C3F5EAB56310F6F1572C4553CB6EF'
  'angelspetrochem_2.1.2.zip'='9B4CC14156CF16C9F41784108CCA5E767180A7330B1AF23A387231653CE10A49'
  'angelspetrochemgraphics_2.1.0.zip'='DECDC2FCD5BBBDEF70784943C142C30FAA7294B98E814296C5D44D09A9DE4790'
  'angelssmelting_2.1.1.zip'='1DFCDD77D075FD545CFEE74BD8A6443E7E90B133D3832FDD47649C84892243A9'
  'angelssmeltinggraphics_2.1.0.zip'='EBEF8D1F6F13F84B242DF295CE9FAB9618ED90B4C52852A0B4345908A88D5D35'
}
$expectedRecipes=@('angels-ingot-tin','angels-ingot-tin-2','angels-ingot-tin-3','angels-ingot-tin-recycling','angels-liquid-molten-brass-2','angels-liquid-molten-bronze','angels-liquid-molten-bronze-2','angels-liquid-molten-bronze-3','angels-liquid-molten-gunmetal','angels-liquid-molten-solder','angels-liquid-molten-solder-2','angels-liquid-molten-solder-3','angels-liquid-molten-tin','angels-liquid-molten-titanium-4','angels-ore-crushed-mix4-processing','angels-ore3-chunk-processing','angels-ore3-crystal-processing','angels-ore3-pure-processing','angels-ore6-chunk-processing','angels-ore6-crushed-processing','angels-ore6-crystal-processing','angels-ore6-pure-processing','angels-ore9-crushed-processing','angels-ore9-crystal-processing','angels-ore9-dust-processing','angels-ore9-powder-processing','angels-pellet-tin','angels-pellet-tin-recycling','angels-plate-glass-3','angels-plate-tin','angels-plate-tin-2','angels-plate-tin-recycling','angels-powder-tin','angels-powder-tin-recycling','angels-processed-tin','angels-processed-tin-recycling','angels-roll-tin','angels-roll-tin-2','angels-roll-tin-recycling','angels-tin-ore-recycling','angels-wire-coil-tin','angels-wire-coil-tin-2','angels-wire-coil-tin-recycling','angels-wire-tin','angels-wire-tin-2','angels-wire-tin-recycling','bob-bronze-alloy','bob-gunmetal-alloy','bob-tin-ore-recycling','bob-tin-plate','bob-tin-plate-recycling')
$expectedOreProducers=@('angels-ore-crushed-mix4-processing','angels-ore3-chunk-processing','angels-ore3-crystal-processing','angels-ore3-pure-processing','angels-ore6-chunk-processing','angels-ore6-crushed-processing','angels-ore6-crystal-processing','angels-ore6-pure-processing','angels-ore9-crushed-processing','angels-ore9-crystal-processing','angels-ore9-dust-processing','angels-ore9-powder-processing')
$expectedPermissions=@('angels-ore-crushed-mix4-processing','angels-ore3-chunk-processing','angels-ore3-crystal-processing','angels-ore3-pure-processing','angels-ore6-chunk-processing','angels-ore6-crushed-processing','angels-ore6-crystal-processing','angels-ore6-pure-processing','angels-ore9-crushed-processing','angels-ore9-crystal-processing','angels-ore9-dust-processing','angels-ore9-powder-processing','angels-plate-glass-3','angels-plate-tin','angels-plate-tin-2','angels-wire-tin-2','bob-bronze-alloy','bob-gunmetal-alloy','bob-tin-plate')
$expectedHiddenRecipes=@('angels-ingot-tin-recycling','angels-liquid-molten-solder','angels-liquid-molten-solder-2','angels-liquid-molten-solder-3','angels-pellet-tin-recycling','angels-plate-tin-recycling','angels-powder-tin','angels-powder-tin-recycling','angels-processed-tin-recycling','angels-roll-tin-recycling','angels-tin-ore-recycling','angels-wire-coil-tin','angels-wire-coil-tin-2','angels-wire-coil-tin-recycling','angels-wire-tin','angels-wire-tin-2','angels-wire-tin-recycling','bob-bronze-alloy','bob-gunmetal-alloy','bob-tin-ore-recycling','bob-tin-plate','bob-tin-plate-recycling')
$expectedAllDeclaredFinalPlateProducers=@('angels-plate-tin','angels-plate-tin-2','angels-plate-tin-recycling','angels-wire-tin-recycling','bob-tin-plate','bob-tin-plate-recycling')
$expectedNonRecyclingFinalPlateTransformations=@('angels-plate-tin','angels-plate-tin-2','bob-tin-plate')
$expectedRecyclingFinalPlateProducers=@('angels-plate-tin-recycling','angels-wire-tin-recycling','bob-tin-plate-recycling')
$expectedOfficialMods=@('base','elevated-rails','quality','recycler','space-age')
$expectedNonClaims=@('combined-productivity-admission','MIR-emission','F200','gameplay-progression-or-reachability','upgrade-or-persisted-save-recovery','balance-or-process-safety','PIPE-01','infinite-continuation','full-BA-07-or-PROG-01','release-readiness')
function Assert-Exact([string]$Name,$Actual,$Expected) { if($Actual -cne $Expected) { throw "Bob Angel Tin dossier $Name differs: expected '$Expected', actual '$Actual'." } }
function Assert-Array([string]$Name,$Actual,[string[]]$Expected) { $actualValues=@($Actual|ForEach-Object {[string]$_});if(($actualValues -join "`n") -cne ($Expected -join "`n")){throw "Bob Angel Tin dossier $Name differs."} }
function Assert-Props([string]$Name,$Object,[string[]]$Expected) { if($null -eq $Object){throw "Bob Angel Tin dossier $Name is absent."};$actual=@($Object.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object);if(($actual -join "`n") -cne ($wanted -join "`n")){throw "Bob Angel Tin dossier $Name properties differ."} }
function Assert-Map([string]$Name,$Values,[hashtable]$Expected) { Assert-Props $Name $Values @('type','name','amount');Assert-Exact "$Name.type" $Values.type $Expected.type;Assert-Exact "$Name.name" $Values.name $Expected.name;Assert-Exact "$Name.amount" $Values.amount $Expected.amount }
$engineSha256=(Get-FileHash -LiteralPath $engine -Algorithm SHA256).Hash
if($engineSha256 -cne $expectedEngineSha256){throw "Bob Angel Tin audit requires exact F210 engine SHA-256 $expectedEngineSha256."}
$version=(& $engine --version|Out-String)
if($LASTEXITCODE -ne 0 -or $version -notmatch 'Version: 2[.]1[.]17'){throw 'Bob Angel Tin audit requires Steam F210 2.1.17.'}
$engineVersion=([regex]::Match($version,'Version:\s+2[.]1[.]17[^\r\n]*').Value).Trim()
if([string]::IsNullOrWhiteSpace($engineVersion)){throw 'Bob Angel Tin audit could not bind the exact F210 engine version.'}
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim();$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim()
if($sourceCommit -notmatch '^[0-9a-f]{40}$' -or $sourceTree -notmatch '^[0-9a-f]{40}$'){throw 'Bob Angel Tin audit requires nonempty 40-hex source commit and tree bindings.'}
$sourceChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod)
if($sourceChanges.Count -ne 0){throw "Bob Angel Tin audit refuses a changed package-source root: $($sourceChanges -join '; ')"}
$packageSource=Join-Path $repo 'src/mod/package-source.json';$fixture=Join-Path $repo 'fixtures/assert-bob-angel-tin-final-state-audit';$dossier=Join-Path $fixture 'route-dossier.json'
try{$record=Get-Content -Raw -LiteralPath $dossier|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Angel Tin dossier is not valid JSON: $($_.Exception.Message)"}
Assert-Props root $record @('schema','kind','scope','target','official_mod_closure','archive_closure','final_identity','raw_recipe_state','all_declared_final_plate_producer_recipe_ids','non_recycling_final_plate_transformations','conditional_crafting_category_capability','ordinary_ore_producers','catalyst_route','route_graph','final_plate_consumers','side_paths','productivity','science_lab_frontier','observed_disposition','evidence_role','explicit_non_claims')
Assert-Exact schema $record.schema 1;Assert-Exact kind $record.kind 'MIR4BobAngelTinFinalStateAuditV1';Assert-Exact scope $record.scope 'F210 exact combined Bob plus Angel Tin final-state diagnostic audit; package-excluded evidence';Assert-Exact evidence_role $record.evidence_role 'bounded diagnostic input to A06 BA-07 A17 and PROG-01; not completion authority';Assert-Exact observed_disposition $record.observed_disposition 'diagnostic-combined-route-present-without-native-or-mir-productivity-owner';Assert-Array explicit_non_claims $record.explicit_non_claims $expectedNonClaims
Assert-Props target $record.target @('factorio_line','factorio_version','engine_sha256');Assert-Exact target.factorio_line $record.target.factorio_line '2.1';Assert-Exact target.factorio_version $record.target.factorio_version '2.1.17';Assert-Exact target.engine_sha256 $record.target.engine_sha256 $expectedEngineSha256
if(@($record.official_mod_closure).Count -ne $expectedOfficialMods.Count){throw 'Bob Angel Tin dossier official mod closure count differs.'};for($index=0;$index -lt $expectedOfficialMods.Count;$index++){Assert-Props "official_mod_closure[$index]" @($record.official_mod_closure)[$index] @('name','enabled');Assert-Exact "official_mod_closure[$index].name" @($record.official_mod_closure)[$index].name $expectedOfficialMods[$index];Assert-Exact "official_mod_closure[$index].enabled" @($record.official_mod_closure)[$index].enabled $true}
if(@($record.archive_closure).Count -ne $expectedArchives.Count){throw 'Bob Angel Tin dossier archive closure count differs.'};$archiveSeen=@{};foreach($entry in @($record.archive_closure)){Assert-Props archive $entry @('name','version','sha256');$archiveName="$($entry.name)_$($entry.version).zip";if(-not $expectedArchives.Contains($archiveName) -or $archiveSeen.Contains($archiveName)){throw "Bob Angel Tin dossier archive differs $($entry.name)"};$archiveSeen[$archiveName]=$true;Assert-Exact "archive.$($entry.name).sha256" $entry.sha256 $expectedArchives[$archiveName]};if($archiveSeen.Count -ne $expectedArchives.Count){throw 'Bob Angel Tin dossier archive closure identities differ.'}
Assert-Props final_identity $record.final_identity @('item','hidden_angel_alias','alias_hidden');Assert-Exact final_identity.item $record.final_identity.item 'bob-tin-plate';Assert-Exact final_identity.hidden_angel_alias $record.final_identity.hidden_angel_alias 'angels-plate-tin';Assert-Exact final_identity.alias_hidden $record.final_identity.alias_hidden $true
Assert-Props raw_recipe_state $record.raw_recipe_state @('recipe_ids','enabled','category','category_disposition','hidden_recipe_ids','automatic_recycling_present');Assert-Array raw_recipe_state.recipe_ids $record.raw_recipe_state.recipe_ids $expectedRecipes;Assert-Exact raw_recipe_state.enabled $record.raw_recipe_state.enabled $false;if($null -ne $record.raw_recipe_state.category){throw 'Bob Angel Tin dossier raw category must be null.'};Assert-Exact raw_recipe_state.category_disposition $record.raw_recipe_state.category_disposition 'implicit-crafting';Assert-Array raw_recipe_state.hidden_recipe_ids $record.raw_recipe_state.hidden_recipe_ids $expectedHiddenRecipes;Assert-Exact raw_recipe_state.automatic_recycling_present $record.raw_recipe_state.automatic_recycling_present $false
Assert-Array all_declared_final_plate_producer_recipe_ids $record.all_declared_final_plate_producer_recipe_ids $expectedAllDeclaredFinalPlateProducers;if(@($record.non_recycling_final_plate_transformations).Count -ne $expectedNonRecyclingFinalPlateTransformations.Count){throw 'Bob Angel Tin dossier non-recycling final plate transformation count differs.'};$final=@{};foreach($row in @($record.non_recycling_final_plate_transformations)){Assert-Props "final.$($row.recipe)" $row @('recipe','hidden','ingredients','products','allow_productivity','auto_recycle');if($final.ContainsKey([string]$row.recipe)){throw "Bob Angel Tin dossier duplicate non-recycling final transformation $($row.recipe)"};$final[[string]$row.recipe]=$row};foreach($name in $expectedNonRecyclingFinalPlateTransformations){if(-not $final.ContainsKey($name)){throw "Bob Angel Tin dossier non-recycling final transformation absent $name"}};Assert-Exact final.bob.hidden $final['bob-tin-plate'].hidden $true;Assert-Exact final.angels.hidden $final['angels-plate-tin'].hidden $null;Assert-Exact final.angels2.hidden $final['angels-plate-tin-2'].hidden $null;foreach($row in $final.Values){Assert-Exact "final.$($row.recipe).allow_productivity" $row.allow_productivity $true;Assert-Exact "final.$($row.recipe).auto_recycle" $row.auto_recycle $false;if(@($row.ingredients).Count -ne 1 -or @($row.products).Count -ne 1){throw "Bob Angel Tin dossier non-recycling final transformation cardinality differs $($row.recipe)"}}
Assert-Map 'angels-plate-tin input' @($final['angels-plate-tin'].ingredients)[0] @{type='fluid';name='angels-liquid-molten-tin';amount=40};Assert-Map 'angels-plate-tin output' @($final['angels-plate-tin'].products)[0] @{type='item';name='bob-tin-plate';amount=4};Assert-Map 'angels-plate-tin-2 input' @($final['angels-plate-tin-2'].ingredients)[0] @{type='item';name='angels-roll-tin';amount=1};Assert-Map 'angels-plate-tin-2 output' @($final['angels-plate-tin-2'].products)[0] @{type='item';name='bob-tin-plate';amount=4};Assert-Map 'bob-tin-plate input' @($final['bob-tin-plate'].ingredients)[0] @{type='item';name='bob-tin-ore';amount=1};Assert-Map 'bob-tin-plate output' @($final['bob-tin-plate'].products)[0] @{type='item';name='bob-tin-plate';amount=1}
Assert-Props conditional_crafting_category_capability $record.conditional_crafting_category_capability @('category','machine_type','machine_ids','route_or_reachability_claimed');Assert-Exact conditional.category $record.conditional_crafting_category_capability.category 'crafting';Assert-Exact conditional.machine_type $record.conditional_crafting_category_capability.machine_type 'assembling-machine';Assert-Array conditional.machine_ids $record.conditional_crafting_category_capability.machine_ids @('assembling-machine-1','assembling-machine-2','assembling-machine-3');Assert-Exact conditional.route_or_reachability_claimed $record.conditional_crafting_category_capability.route_or_reachability_claimed $false
Assert-Array ordinary_ore_producers $record.ordinary_ore_producers $expectedOreProducers;Assert-Props catalyst_route $record.catalyst_route @('recipe','catalyst','amount','products');Assert-Exact catalyst_route.recipe $record.catalyst_route.recipe 'angels-ore-crushed-mix4-processing';Assert-Exact catalyst_route.catalyst $record.catalyst_route.catalyst 'angels-catalysator-brown';Assert-Exact catalyst_route.amount $record.catalyst_route.amount 1;Assert-Map catalyst_route.product @($record.catalyst_route.products)[0] @{type='item';name='bob-tin-ore';amount=4}
Assert-Props route_graph $record.route_graph @('nodes','edges');Assert-Array route_graph.nodes $record.route_graph.nodes @('bob-tin-ore','angels-processed-tin','angels-pellet-tin','angels-ingot-tin','angels-liquid-molten-tin','angels-roll-tin','bob-tin-plate');Assert-Array route_graph.edges $record.route_graph.edges @('bob-tin-ore->angels-processed-tin','angels-processed-tin->angels-pellet-tin','angels-pellet-tin->angels-ingot-tin','angels-ingot-tin->angels-liquid-molten-tin','angels-liquid-molten-tin->bob-tin-plate','angels-liquid-molten-tin->angels-roll-tin->bob-tin-plate');Assert-Array final_plate_consumers $record.final_plate_consumers @('angels-plate-tin-recycling','angels-wire-tin','bob-bronze-alloy','bob-gunmetal-alloy','bob-tin-plate-recycling')
Assert-Props side_paths $record.side_paths @('coolant_byproducts','recycling_technology','recycling_prerequisite','declared_recycling_final_plate_producer_recipe_ids','direct_plate_to_ore_recipe_edges','mir_potential_return_omission');Assert-Exact side_paths.recycling_technology $record.side_paths.recycling_technology 'recycling';Assert-Exact side_paths.recycling_prerequisite $record.side_paths.recycling_prerequisite 'planet-discovery-fulgora';Assert-Array side_paths.declared_recycling_final_plate_producer_recipe_ids $record.side_paths.declared_recycling_final_plate_producer_recipe_ids $expectedRecyclingFinalPlateProducers;Assert-Array side_paths.direct_plate_to_ore_recipe_edges $record.side_paths.direct_plate_to_ore_recipe_edges @();Assert-Props side_paths.mir_potential_return_omission $record.side_paths.mir_potential_return_omission @('recipe','reason','stream','stream_disposition','return_graph_reconstructed');Assert-Exact side_paths.mir_omission.recipe $record.side_paths.mir_potential_return_omission.recipe 'bob-tin-plate';Assert-Exact side_paths.mir_omission.reason $record.side_paths.mir_potential_return_omission.reason 'potential-return-path:bob-tin-ore';Assert-Exact side_paths.mir_omission.stream $record.side_paths.mir_potential_return_omission.stream 'research_material_tin';Assert-Exact side_paths.mir_omission.stream_disposition $record.side_paths.mir_potential_return_omission.stream_disposition 'no_matching_recipes';Assert-Exact side_paths.mir_omission.return_graph_reconstructed $record.side_paths.mir_potential_return_omission.return_graph_reconstructed $false;if(@($record.side_paths.coolant_byproducts).Count -ne 2){throw 'Bob Angel Tin dossier coolant byproduct count differs.'};foreach($byproduct in @($record.side_paths.coolant_byproducts)){Assert-Props coolant_byproduct $byproduct @('recipe','product','amount')};Assert-Exact coolant.first.recipe @($record.side_paths.coolant_byproducts)[0].recipe 'angels-roll-tin-2';Assert-Exact coolant.first.product @($record.side_paths.coolant_byproducts)[0].product 'angels-liquid-coolant-used';Assert-Exact coolant.first.amount @($record.side_paths.coolant_byproducts)[0].amount 40;Assert-Exact coolant.second.recipe @($record.side_paths.coolant_byproducts)[1].recipe 'angels-wire-coil-tin-2';Assert-Exact coolant.second.product @($record.side_paths.coolant_byproducts)[1].product 'angels-liquid-coolant-used';Assert-Exact coolant.second.amount @($record.side_paths.coolant_byproducts)[1].amount 40
Assert-Props productivity $record.productivity @('permission_recipe_ids','native_owner_technologies','mir_owner_technology','disposition');Assert-Array productivity.permission_recipe_ids $record.productivity.permission_recipe_ids $expectedPermissions;Assert-Array productivity.native_owner_technologies $record.productivity.native_owner_technologies @();Assert-Exact productivity.mir_owner_technology $record.productivity.mir_owner_technology $null;Assert-Exact productivity.disposition $record.productivity.disposition 'permission-present-without-native-or-mir-owner'
Assert-Props science_lab_frontier $record.science_lab_frontier @('technology','prototype_unlock_graph','unlock_recipe_ids','science','lab','gameplay_reachability_claimed');Assert-Exact science_lab_frontier.technology $record.science_lab_frontier.technology 'angels-tin-smelting-1';Assert-Array science_lab_frontier.prototype_unlock_graph $record.science_lab_frontier.prototype_unlock_graph @('automation','angels-basic-chemistry','angels-ore-crushing','angels-metallurgy-1','angels-tin-smelting-1');Assert-Array science_lab_frontier.unlock_recipe_ids $record.science_lab_frontier.unlock_recipe_ids @('angels-ingot-tin','angels-liquid-molten-tin','angels-plate-tin');Assert-Array science_lab_frontier.science $record.science_lab_frontier.science @('automation-science-pack');Assert-Exact science_lab_frontier.lab $record.science_lab_frontier.lab 'lab';Assert-Exact science_lab_frontier.gameplay_reachability_claimed $record.science_lab_frontier.gameplay_reachability_claimed $false
. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1')
. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)){$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('BOB-ANGEL-TIN-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/bob-angel-tin-audit/packages';$CandidateZip=[string]$candidate.archive_path}
$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try{$forbidden=@($zip.Entries|Where-Object {$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "Candidate includes package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';New-Item -ItemType Directory -Force -Path $mods,(Join-Path $run 'userdata')|Out-Null;Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveHashes=[ordered]@{};foreach($entry in $expectedArchives.GetEnumerator()){$path=Join-Path $modsRoot $entry.Key;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Combined archive missing $path"};$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;if($hash -cne $entry.Value){throw "Combined archive hash differs $($entry.Key)"};$archiveHashes[$entry.Key]=$hash;Copy-Item -LiteralPath $path -Destination $mods}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-bob-angel-tin-final-state-audit' -Version '0.1.0' -ModsDir $mods|Out-Null
@{mods=@(@{name='base';enabled=$true},@{name='space-age';enabled=$true},@{name='elevated-rails';enabled=$true},@{name='quality';enabled=$true},@{name='recycler';enabled=$true},@{name='more-infinite-research';enabled=$true},@{name='boblibrary';enabled=$true},@{name='bobores';enabled=$true},@{name='bobplates';enabled=$true},@{name='angelsrefining';enabled=$true},@{name='angelsrefininggraphics';enabled=$true},@{name='angelspetrochem';enabled=$true},@{name='angelspetrochemgraphics';enabled=$true},@{name='angelssmelting';enabled=$true},@{name='angelssmeltinggraphics';enabled=$true},@{name='mir-fixture-assert-bob-angel-tin-final-state-audit';enabled=$true})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $mods 'mod-list.json') -Encoding utf8
$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false))
$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--mod-directory',$mods,'--create',(Join-Path $run 'audit.zip'))){$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(120000)){$process.Kill($true);throw "Bob Angel Tin audit timed out $run"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run 'engine.log'),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "Bob Angel Tin audit engine failed: $run`n$($text.Substring([Math]::Max(0,$text.Length-2500)))"}}finally{$process.Dispose()}
$log=Join-Path $run 'userdata/factorio-current.log';if(-not(Test-Path -LiteralPath $log -PathType Leaf)){throw 'Bob Angel Tin audit Factorio log is absent.'};$logText=Get-Content -Raw -LiteralPath $log;if($logText -notmatch [regex]::Escape('[mir-bob-angel-tin-audit] DATA PASS final=bob-tin-plate recipes=51 ore-producers=12 productivity-owner=none mir-owner=absent gameplay-reachability=unclaimed')){throw 'Bob Angel Tin audit data assertion is absent.'};if($logText -notmatch [regex]::Escape('[more-infinite-research] Material route omitted recipe=bob-tin-plate reason=potential-return-path:bob-tin-ore')){throw 'Bob Angel Tin audit MIR potential-return omission is absent.'};if($logText -notmatch [regex]::Escape('[more-infinite-research] Skipping stream research_material_tin because no_matching_recipes.')){throw 'Bob Angel Tin audit MIR Tin stream omission is absent.'};if($logText -notmatch [regex]::Escape('[mir-bob-angel-tin-audit] RUNTIME PASS diagnostic-only-no-owner')){throw 'Bob Angel Tin audit runtime assertion is absent.'}
$result=[ordered]@{schema=1;status='passed';scope='F210 exact combined Bob plus Angel Tin final-state diagnostic audit';target='F210';engine_version=$engineVersion;engine_sha256=$engineSha256;official_mod_closure=$record.official_mod_closure;source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=(Get-FileHash -LiteralPath $packageSource -Algorithm SHA256).Hash;package_source_roots_clean=$true};candidate_sha256=(Get-FileHash -LiteralPath $candidateZip -Algorithm SHA256).Hash;candidate_package_excludes_fixture_test_docs_mir_build_dist=$true;archive_sha256=$archiveHashes;dossier_sha256=(Get-FileHash -LiteralPath $dossier -Algorithm SHA256).Hash;fixture_hashes=[ordered]@{info=(Get-FileHash (Join-Path $fixture 'info.json') -Algorithm SHA256).Hash;dossier=(Get-FileHash $dossier -Algorithm SHA256).Hash;data_final_fixes=(Get-FileHash (Join-Path $fixture 'data-final-fixes.lua') -Algorithm SHA256).Hash;control=(Get-FileHash (Join-Path $fixture 'control.lua') -Algorithm SHA256).Hash};harness_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;observed_disposition=[string]$record.observed_disposition;all_declared_final_plate_producer_recipe_count=6;declared_recycling_final_plate_producer_recipe_count=3;declared_recycling_final_plate_producer_recipe_ids=$expectedRecyclingFinalPlateProducers;non_recycling_final_plate_transformation_count=3;ordinary_ore_producer_count=12;direct_plate_to_ore_recipe_edges=@();mir_potential_return_omission=$record.side_paths.mir_potential_return_omission;productivity_owner=[ordered]@{native=@();mir=$null};log_sha256=(Get-FileHash -LiteralPath $log -Algorithm SHA256).Hash;non_claims=$expectedNonClaims}
$result|ConvertTo-Json -Depth 10|Set-Content -LiteralPath (Join-Path $run 'result.json') -Encoding utf8;$result|ConvertTo-Json -Depth 10;Write-Output "Evidence: $run"
