# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$BobModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-bob-tin-production-gain'
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path
$engine=(Resolve-Path -LiteralPath $FactorioBin).Path
$bobMods=(Resolve-Path -LiteralPath $BobModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot))
if(-not $output.StartsWith((Join-Path $repo 'build')+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Bob Tin production-gain outputs must be under build.'}
$expectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$expectedArchives=[ordered]@{
  boblibrary=[ordered]@{file='boblibrary_3.0.0.zip';version='3.0.0';sha256='49EAE2D4D8E58EBD28BAFDB7E71D5307CBCE2077E0642440ED7EC527D466FFC4'}
  bobores=[ordered]@{file='bobores_3.0.0.zip';version='3.0.0';sha256='7F8E33E35F59BB3F2CD72E3AB2FED30D1C2AE9C117E3731324AC307D9965082B'}
  bobplates=[ordered]@{file='bobplates_3.0.1.zip';version='3.0.1';sha256='503D7BF6E88DA1F99463AC00CEC959C2003B2701D80DC4A564CF2EC3920AC8AF'}
}
$expectedNonClaims=@('Angel-or-combined-Bob-Angel-admission','route-safety-completion','F200','science-frontier-or-balance','all-intended-machines-or-stages','vertical-slice-obligation-three-completion','upgrade-or-persisted-save-recovery','multiplayer','research-browser','full-BA-07-or-PROG-01','release-readiness')
$expectedLevels=@(@{level=0;output=100;bonus=0},@{level=1;output=102;bonus=2},@{level=2;output=104;bonus=4},@{level=3;output=106;bonus=6})
function Assert-Exact([string]$Name,$Actual,$Expected){if($null -eq $Actual -and $null -eq $Expected){return};if($null -eq $Actual -or $null -eq $Expected -or $Actual -cne $Expected){throw "Bob Tin production-gain $Name differs."}}
function Assert-Props([string]$Name,$Object,[string[]]$Expected){if($null -eq $Object){throw "Bob Tin production-gain $Name is absent."};$actual=@($Object.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object);if(($actual -join "`n") -cne ($wanted -join "`n")){throw "Bob Tin production-gain $Name properties differ."}}
function Assert-Array([string]$Name,$Actual,[string[]]$Expected){$values=@($Actual|ForEach-Object{[string]$_});if(($values -join "`n") -cne ($Expected -join "`n")){throw "Bob Tin production-gain $Name differs."}}
function Assert-Entry([string]$Name,$Entry,[string]$Type,[string]$Item,[int]$Amount){Assert-Props $Name $Entry @('type','name','amount');Assert-Exact "$Name.type" $Entry.type $Type;Assert-Exact "$Name.name" $Entry.name $Item;Assert-Exact "$Name.amount" $Entry.amount $Amount}
function Convert-BobTinObservedBoolean([string]$Name,[string]$Value){if($Value -ceq 'true'){return $true};if($Value -ceq 'false'){return $false};throw "Bob Tin production-gain $Name is not a boolean observation."}
function Get-BobTinDataObservation([string]$Text){$found=[regex]::Matches($Text,'\[mir-bob-tin-production-gain\] DATA PASS recipe=(?<recipe>[^\s]+) machine=(?<machine>[^\s]+) owner=(?<owner>[0-9]+) change=(?<change>[0-9]+(?:[.][0-9]+)?) raw=(?<raw>[0-9]+) imported=(?<imported>[0-9]+) effective=(?<effective>[0-9]+)');if($found.Count -ne 1){throw "Bob Tin production-gain requires exactly one DATA PASS record; observed $($found.Count)."};$match=$found[0];return [pscustomobject]@{recipe=$match.Groups['recipe'].Value;machine=$match.Groups['machine'].Value;owner=[int]$match.Groups['owner'].Value;change=[double]::Parse($match.Groups['change'].Value,[Globalization.CultureInfo]::InvariantCulture);raw_direct=[int]$match.Groups['raw'].Value;mirset1_imported=[int]$match.Groups['imported'].Value;effective=[int]$match.Groups['effective'].Value}}
function Get-BobTinRuntimeObservation([string]$Text){$found=[regex]::Matches($Text,'\[mir-bob-tin-production-gain\] RUNTIME PASS raw=(?<raw>[0-9]+) imported=(?<imported>[0-9]+) effective=(?<effective>[0-9]+) no-level-4=(?<no4>true|false) input-ore=(?<input>[0-9]+) levels=(?<levels>0:[0-9]+:[0-9]+,1:[0-9]+:[0-9]+,2:[0-9]+:[0-9]+,3:[0-9]+:[0-9]+) input-exhausted=(?<exhausted>true|false) output-drained=(?<drained>true|false)');if($found.Count -ne 1){throw "Bob Tin production-gain requires exactly one RUNTIME PASS record; observed $($found.Count)."};$match=$found[0];$levels=@();foreach($part in $match.Groups['levels'].Value.Split(',')){if($part -notmatch '^(?<level>[0-9]+):(?<output>[0-9]+):(?<bonus>[0-9]+)$'){throw "Bob Tin production-gain runtime level observation is malformed: $part"};$levels+=,[pscustomobject]@{level=[int]$Matches.level;output=[int]$Matches.output;bonus=[int]$Matches.bonus}};return [pscustomobject]@{raw_direct=[int]$match.Groups['raw'].Value;mirset1_imported=[int]$match.Groups['imported'].Value;effective=[int]$match.Groups['effective'].Value;no_level_4=(Convert-BobTinObservedBoolean no_level_4 $match.Groups['no4'].Value);input_ore=[int]$match.Groups['input'].Value;levels=$levels;input_exhausted=(Convert-BobTinObservedBoolean input_exhausted $match.Groups['exhausted'].Value);output_drained=(Convert-BobTinObservedBoolean output_drained $match.Groups['drained'].Value)}}
function Assert-BobTinDataObservation($Observation,$Dossier){Assert-Exact observed.data.recipe $Observation.recipe $Dossier.route.recipe;Assert-Exact observed.data.machine $Observation.machine $Dossier.route.machine;Assert-Exact observed.data.owner $Observation.owner $Dossier.mir_owner.exact_owner_count;Assert-Exact observed.data.change $Observation.change $Dossier.mir_owner.effect_change_per_completed_level;Assert-Exact observed.data.raw $Observation.raw_direct $Dossier.cap_transport.raw_direct_max_level;Assert-Exact observed.data.imported $Observation.mirset1_imported $Dossier.cap_transport.mirset1_imported_max_level;Assert-Exact observed.data.effective $Observation.effective $Dossier.cap_transport.effective_max_level}
function Assert-BobTinRuntimeObservation($Observation,$Dossier){Assert-Exact observed.runtime.raw $Observation.raw_direct $Dossier.cap_transport.raw_direct_max_level;Assert-Exact observed.runtime.imported $Observation.mirset1_imported $Dossier.cap_transport.mirset1_imported_max_level;Assert-Exact observed.runtime.effective $Observation.effective $Dossier.cap_transport.effective_max_level;Assert-Exact observed.runtime.no4 $Observation.no_level_4 $Dossier.cap_transport.no_level_4;Assert-Exact observed.runtime.input $Observation.input_ore $Dossier.production.input_ore_per_level;Assert-Exact observed.runtime.input_exhausted $Observation.input_exhausted $Dossier.production.requires_input_exhaustion;Assert-Exact observed.runtime.output_drained $Observation.output_drained $Dossier.production.drain_output_inventory_each_tick;if(@($Observation.levels).Count -ne @($Dossier.production.levels).Count){throw 'Bob Tin production-gain observed runtime level count differs.'};for($index=0;$index -lt @($Dossier.production.levels).Count;$index++){$actual=@($Observation.levels)[$index];$expected=@($Dossier.production.levels)[$index];Assert-Exact "observed.runtime.levels[$index].level" $actual.level $expected.completed_level;Assert-Exact "observed.runtime.levels[$index].output" $actual.output $expected.expected_output;Assert-Exact "observed.runtime.levels[$index].bonus" $actual.bonus $expected.expected_bonus}}
function Assert-BobTinStaticDriftControls($Dossier){$driftRuntime='[mir-bob-tin-production-gain] RUNTIME PASS raw=2 imported=3 effective=3 no-level-4=true input-ore=100 levels=0:100:0,1:102:2,2:104:4,3:105:5 input-exhausted=true output-drained=true';$caught=$false;try{Assert-BobTinRuntimeObservation (Get-BobTinRuntimeObservation $driftRuntime) $Dossier}catch{$caught=$true};if(-not $caught){throw 'Bob Tin production-gain stale runtime success control was accepted.'};$driftData='[mir-bob-tin-production-gain] DATA PASS recipe=bob-tin-plate machine=stone-furnace owner=1 change=0.03 raw=2 imported=3 effective=3';$caught=$false;try{Assert-BobTinDataObservation (Get-BobTinDataObservation $driftData) $Dossier}catch{$caught=$true};if(-not $caught){throw 'Bob Tin production-gain stale data success control was accepted.'};$source=Get-Content -Raw -LiteralPath $PSCommandPath;if($source -match 'cap_transport=\[ordered\]@\{raw_direct=2;' -or $source -match 'production=@\(\$expectedLevels\|ForEach-Object'){throw 'Bob Tin production-gain refuses a hard-coded runtime receipt.'}}

$engineSha256=(Get-FileHash -LiteralPath $engine -Algorithm SHA256).Hash
if($engineSha256 -cne $expectedEngineSha256){throw "Bob Tin production-gain requires exact F210 engine SHA-256 $expectedEngineSha256."}
$version=(& $engine --version|Out-String)
if($LASTEXITCODE -ne 0 -or $version -notmatch 'Version: 2[.]1[.]17'){throw 'Bob Tin production-gain requires exact Steam F210 2.1.17.'}
$engineVersion=([regex]::Match($version,'Version:\s+2[.]1[.]17[^\r\n]*').Value).Trim()
if([string]::IsNullOrWhiteSpace($engineVersion)){throw 'Bob Tin production-gain could not bind engine version.'}
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim();$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim()
if($sourceCommit -notmatch '^[0-9a-f]{40}$' -or $sourceTree -notmatch '^[0-9a-f]{40}$'){throw 'Bob Tin production-gain requires exact source commit/tree bindings.'}
$sourceChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod)
if($sourceChanges.Count -ne 0){throw "Bob Tin production-gain refuses a changed package-source root: $($sourceChanges -join '; ')"}

$fixture=Join-Path $repo 'fixtures/assert-bob-tin-production-gain'
$dossier=Join-Path $fixture 'production-gain-dossier.json'
$packageSource=Join-Path $repo 'src/mod/package-source.json'
try{$record=Get-Content -Raw -LiteralPath $dossier|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Tin production-gain dossier JSON is invalid: $($_.Exception.Message)"}
Assert-Props root $record @('schema','kind','scope','target','route','mir_owner','cap_transport','production','controls','evidence_role','explicit_non_claims')
Assert-Exact schema $record.schema 1;Assert-Exact kind $record.kind 'MIR4BobTinProductionGainV1';Assert-Exact scope $record.scope 'F210 Bob-only finite Tin quantitative production-gain diagnostic; package-excluded evidence';Assert-Exact evidence_role $record.evidence_role 'bounded quantitative diagnostic input to A06 BA-07 A17 and PROG-01; not completion authority';Assert-Array explicit_non_claims $record.explicit_non_claims $expectedNonClaims
Assert-Props target $record.target @('factorio_line','factorio_version','engine_sha256','boblibrary','bobores','bobplates');Assert-Exact target.line $record.target.factorio_line '2.1';Assert-Exact target.version $record.target.factorio_version '2.1.17';Assert-Exact target.engine $record.target.engine_sha256 $expectedEngineSha256
foreach($name in $expectedArchives.Keys){Assert-Props "target.$name" $record.target.$name @('version','sha256');Assert-Exact "target.$name.version" $record.target.$name.version $expectedArchives[$name].version;Assert-Exact "target.$name.sha256" $record.target.$name.sha256 $expectedArchives[$name].sha256}
Assert-Props route $record.route @('recipe','category','machine','input','output','allow_productivity','auto_recycle');Assert-Exact route.recipe $record.route.recipe 'bob-tin-plate';Assert-Exact route.category $record.route.category 'smelting';Assert-Exact route.machine $record.route.machine 'stone-furnace';Assert-Entry route.input $record.route.input item bob-tin-ore 1;Assert-Entry route.output $record.route.output item bob-tin-plate 1;Assert-Exact route.productivity $record.route.allow_productivity $true;Assert-Exact route.recycle $record.route.auto_recycle $false
Assert-Props mir_owner $record.mir_owner @('stream_key','technology','effect_type','effect_recipe','effect_change_per_completed_level','exact_owner_count','prototype_max_level');Assert-Exact owner.stream $record.mir_owner.stream_key 'research_material_tin';Assert-Exact owner.technology $record.mir_owner.technology 'recipe-prod-research_material_tin-1';Assert-Exact owner.type $record.mir_owner.effect_type 'change-recipe-productivity';Assert-Exact owner.recipe $record.mir_owner.effect_recipe 'bob-tin-plate';Assert-Exact owner.change $record.mir_owner.effect_change_per_completed_level 0.02;Assert-Exact owner.count $record.mir_owner.exact_owner_count 1;Assert-Exact owner.max $record.mir_owner.prototype_max_level 'infinite'
Assert-Props cap_transport $record.cap_transport @('raw_direct_max_level','mirset1_imported_max_level','effective_max_level','no_level_4');Assert-Exact cap.raw $record.cap_transport.raw_direct_max_level 2;Assert-Exact cap.imported $record.cap_transport.mirset1_imported_max_level 3;Assert-Exact cap.effective $record.cap_transport.effective_max_level 3;Assert-Exact cap.no4 $record.cap_transport.no_level_4 $true
Assert-Props production $record.production @('input_ore_per_level','drain_output_inventory_each_tick','requires_input_exhaustion','levels');Assert-Exact production.input $record.production.input_ore_per_level 100;Assert-Exact production.drain $record.production.drain_output_inventory_each_tick $true;Assert-Exact production.exhaustion $record.production.requires_input_exhaustion $true;if(@($record.production.levels).Count -ne 4){throw 'Bob Tin production-gain level count differs.'};for($index=0;$index -lt 4;$index++){$row=@($record.production.levels)[$index];Assert-Props "production.levels[$index]" $row @('completed_level','expected_output','expected_bonus');Assert-Exact "production.levels[$index].level" $row.completed_level $expectedLevels[$index].level;Assert-Exact "production.levels[$index].output" $row.expected_output $expectedLevels[$index].output;Assert-Exact "production.levels[$index].bonus" $row.expected_bonus $expectedLevels[$index].bonus};Assert-Array controls $record.controls @('baseline-level-zero','cap-level-three','no-level-four','output-drain','input-exhaustion')
Assert-BobTinStaticDriftControls $record

. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1')
. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1')
. (Join-Path $repo 'tools/lib/validation/SettingsOverrides.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)){$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('BOB-TIN-PRODUCTION-GAIN-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/bob-tin-production-gain/packages';$CandidateZip=[string]$candidate.archive_path}
$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try{$forbidden=@($zip.Entries|Where-Object {$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "Candidate includes package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';New-Item -ItemType Directory -Force -Path $mods,(Join-Path $run 'userdata')|Out-Null;Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveHashes=[ordered]@{};foreach($name in $expectedArchives.Keys){$path=Join-Path $bobMods $expectedArchives[$name].file;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Bob Tin production-gain archive is absent $path"};$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;if($hash -cne $expectedArchives[$name].sha256){throw "Bob Tin production-gain archive hash differs $name"};$archiveHashes[$name]=$hash;Copy-Item -LiteralPath $path -Destination $mods}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-bob-tin-production-gain' -Version '0.1.0' -ModsDir $mods|Out-Null
Initialize-MIRSettingsOverrideMod -ModsDir $mods -FactorioVersion '2.1'
Set-CopiedStartupSettingDefaults -ModsDir $mods -Overrides @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=2}
Set-CopiedMIRSettingsProfileDefault -ModsDir $mods -Settings @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=3}
Complete-MIRSettingsOverrideMod -ModsDir $mods
@{mods=@(@{name='base';enabled=$true},@{name='space-age';enabled=$false},@{name='elevated-rails';enabled=$false},@{name='quality';enabled=$false},@{name='recycler';enabled=$false},@{name='more-infinite-research';enabled=$true},@{name='boblibrary';enabled=$true},@{name='bobores';enabled=$true},@{name='bobplates';enabled=$true},@{name='mir-fixture-assert-bob-tin-production-gain';enabled=$true},@{name='mir-validation-settings-overrides';enabled=$true})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $mods 'mod-list.json') -Encoding utf8
$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false))
function Invoke-BobTinProductionGainEngine([string]$Name,[string[]]$Arguments){$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--mod-directory',$mods)+$Arguments){[void]$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(120000)){$process.Kill($true);throw "Bob Tin production-gain engine timeout: $run"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run "engine-$Name.log"),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "Bob Tin production-gain engine failed during ${Name}: $run`n$($text.Substring([Math]::Max(0,$text.Length-2500)))"}}finally{$process.Dispose()};$factorioLog=Join-Path $run 'userdata/factorio-current.log';if(-not(Test-Path -LiteralPath $factorioLog -PathType Leaf)){throw "Bob Tin production-gain Factorio log is absent after $Name."};$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
$save=Join-Path $run 'bob-tin-production-gain.zip';$createLog=Invoke-BobTinProductionGainEngine -Name create -Arguments @('--create',$save);if(-not(Test-Path -LiteralPath $save -PathType Leaf)){throw 'Bob Tin production-gain save was not created.'};$dataObservation=Get-BobTinDataObservation (Get-Content -Raw -LiteralPath $createLog);Assert-BobTinDataObservation $dataObservation $record
$runtimeLog=Invoke-BobTinProductionGainEngine -Name runtime -Arguments @('--benchmark',$save,'--benchmark-ticks','30000','--benchmark-runs','1');$runtimeObservation=Get-BobTinRuntimeObservation (Get-Content -Raw -LiteralPath $runtimeLog);Assert-BobTinRuntimeObservation $runtimeObservation $record
$receipt=[ordered]@{schema=1;status='passed';scope='F210 Bob-only finite Tin quantitative production-gain diagnostic';target='F210';engine_version=$engineVersion;engine_sha256=$engineSha256;source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=(Get-FileHash -LiteralPath $packageSource -Algorithm SHA256).Hash;package_source_roots_clean=$true};candidate_sha256=(Get-FileHash -LiteralPath $candidateZip -Algorithm SHA256).Hash;candidate_package_excludes_fixture_test_docs_mir_build_dist=$true;bob_archive_sha256=$archiveHashes;dossier_sha256=(Get-FileHash -LiteralPath $dossier -Algorithm SHA256).Hash;fixture_hashes=[ordered]@{info=(Get-FileHash (Join-Path $fixture 'info.json') -Algorithm SHA256).Hash;dossier=(Get-FileHash $dossier -Algorithm SHA256).Hash;data_final_fixes=(Get-FileHash (Join-Path $fixture 'data-final-fixes.lua') -Algorithm SHA256).Hash;control=(Get-FileHash (Join-Path $fixture 'control.lua') -Algorithm SHA256).Hash};harness_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;machine=$dataObservation.machine;recipe=$dataObservation.recipe;technology=$record.mir_owner.technology;effect_change_per_completed_level=$dataObservation.change;cap_transport=[ordered]@{raw_direct=$runtimeObservation.raw_direct;mirset1_imported=$runtimeObservation.mirset1_imported;effective=$runtimeObservation.effective;no_level_4=$runtimeObservation.no_level_4};production=@($runtimeObservation.levels|ForEach-Object{[ordered]@{completed_level=$_.level;input_ore=$runtimeObservation.input_ore;input_exhausted=$runtimeObservation.input_exhausted;output=$_.output;bonus=$_.bonus;output_drained_each_tick=$runtimeObservation.output_drained}});logs=[ordered]@{create=(Get-FileHash -LiteralPath $createLog -Algorithm SHA256).Hash;runtime=(Get-FileHash -LiteralPath $runtimeLog -Algorithm SHA256).Hash};non_claims=$expectedNonClaims}
$receipt|ConvertTo-Json -Depth 12|Set-Content -LiteralPath (Join-Path $run 'result.json') -Encoding utf8
$receipt|ConvertTo-Json -Depth 12
Write-Output "Evidence: $run"
