# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$BobModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-bob-tin-machine-matrix'
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path
$engine=(Resolve-Path -LiteralPath $FactorioBin).Path
$bobMods=(Resolve-Path -LiteralPath $BobModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot))
if(-not $output.StartsWith((Join-Path $repo 'build')+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Bob Tin machine-matrix outputs must be under build.'}
$expectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$expectedArchives=[ordered]@{
  boblibrary=[ordered]@{file='boblibrary_3.0.0.zip';version='3.0.0';sha256='49EAE2D4D8E58EBD28BAFDB7E71D5307CBCE2077E0642440ED7EC527D466FFC4'}
  bobores=[ordered]@{file='bobores_3.0.0.zip';version='3.0.0';sha256='7F8E33E35F59BB3F2CD72E3AB2FED30D1C2AE9C117E3731324AC307D9965082B'}
  bobplates=[ordered]@{file='bobplates_3.0.1.zip';version='3.0.1';sha256='503D7BF6E88DA1F99463AC00CEC959C2003B2701D80DC4A564CF2EC3920AC8AF'}
}
$expectedNonClaims=@('actual-gameplay-balance','all-Bob-recipes-or-machine-stages','Angel-or-combined-Bob-Angel-admission','F200','upgrade-or-migration','infinite-continuation','human-playtest','release-readiness','full-BA-07-or-PROG-01')
function Assert-Exact([string]$Name,$Actual,$Expected){if($null -eq $Actual -and $null -eq $Expected){return};if($null -eq $Actual -or $null -eq $Expected -or $Actual -cne $Expected){throw "Bob Tin machine-matrix $Name differs. Observed '$Actual'; expected '$Expected'."}}
function Assert-Properties([string]$Name,$Object,[string[]]$Expected){if($null -eq $Object){throw "Bob Tin machine-matrix $Name is absent."};$actual=@($Object.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object);if(($actual -join "`n") -cne ($wanted -join "`n")){throw "Bob Tin machine-matrix $Name properties differ."}}
function Assert-StringArray([string]$Name,$Actual,[string[]]$Expected){$values=@($Actual|ForEach-Object{[string]$_});if(($values -join "`n") -cne ($Expected -join "`n")){throw "Bob Tin machine-matrix $Name differs."}}
function Assert-Entry([string]$Name,$Entry,[string]$Type,[string]$Item,[int]$Amount){Assert-Properties $Name $Entry @('type','name','amount');Assert-Exact "$Name.type" $Entry.type $Type;Assert-Exact "$Name.name" $Entry.name $Item;Assert-Exact "$Name.amount" $Entry.amount $Amount}
function Get-MatrixObservation([string]$Text,[string]$Stage){$matches=[regex]::Matches($Text,"\[mir-bob-tin-machine-matrix\] $Stage JSON (?<json>\{[^\r\n]+\})");if($matches.Count -ne 1){throw "Bob Tin machine-matrix requires exactly one $Stage JSON log; observed $($matches.Count)."};try{return $matches[0].Groups['json'].Value|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Tin machine-matrix $Stage JSON is invalid: $($_.Exception.Message)"}}
function Assert-MatrixMachine([string]$Name,$Actual,$Expected,[bool]$Runtime){$properties=@('name','entity_type','place_item','energy_type','crafting_categories');if($Runtime){$properties+=,'levels'};Assert-Properties $Name $Actual $properties;foreach($property in @('name','entity_type','place_item','energy_type')){Assert-Exact "$Name.$property" $Actual.$property $Expected.$property};Assert-StringArray "$Name.crafting_categories" $Actual.crafting_categories @($Expected.crafting_categories);if($Runtime){if(@($Actual.levels).Count -ne @($script:record.production.levels).Count){throw "$Name runtime level count differs."};for($index=0;$index -lt @($script:record.production.levels).Count;$index++){$actualLevel=@($Actual.levels)[$index];$expectedLevel=@($script:record.production.levels)[$index];Assert-Properties "$Name.levels[$index]" $actualLevel @('completed_level','input_ore','input_exhausted','output','bonus','output_drain_observed');Assert-Exact "$Name.levels[$index].completed_level" $actualLevel.completed_level $expectedLevel.completed_level;Assert-Exact "$Name.levels[$index].input_ore" $actualLevel.input_ore $script:record.production.input_ore_per_machine_per_level;Assert-Exact "$Name.levels[$index].input_exhausted" $actualLevel.input_exhausted $script:record.production.requires_input_exhaustion;Assert-Exact "$Name.levels[$index].output" $actualLevel.output $expectedLevel.expected_output;Assert-Exact "$Name.levels[$index].bonus" $actualLevel.bonus $expectedLevel.expected_bonus;Assert-Exact "$Name.levels[$index].output_drain_observed" $actualLevel.output_drain_observed $script:record.production.output_drain_observed}}}
function Assert-MatrixData($Observation,$Dossier){Assert-Properties observed.data $Observation @('recipe','category','owner_count','effect_change','machines','unadmitted_matching_entities');Assert-Exact observed.data.recipe $Observation.recipe $Dossier.route.recipe;Assert-Exact observed.data.category $Observation.category $Dossier.route.category;Assert-Exact observed.data.owner_count $Observation.owner_count $Dossier.mir_owner.exact_owner_count;Assert-Exact observed.data.effect_change $Observation.effect_change $Dossier.mir_owner.effect_change_per_completed_level;Assert-StringArray observed.data.unadmitted_matching_entities $Observation.unadmitted_matching_entities @($Dossier.machine_selection.expected_unadmitted_matching_entities);if(@($Observation.machines).Count -ne @($Dossier.machine_selection.machines).Count){throw 'Bob Tin machine-matrix data machine count differs.'};for($index=0;$index -lt @($Dossier.machine_selection.machines).Count;$index++){Assert-MatrixMachine "observed.data.machines[$index]" @($Observation.machines)[$index] @($Dossier.machine_selection.machines)[$index] $false}}
function Assert-MatrixRuntime($Observation,$Dossier){Assert-Properties observed.runtime $Observation @('raw_direct','mirset1_imported','effective','no_level_4','input_ore_per_machine_per_level','machines');Assert-Exact observed.runtime.raw_direct $Observation.raw_direct $Dossier.cap_transport.raw_direct_max_level;Assert-Exact observed.runtime.mirset1_imported $Observation.mirset1_imported $Dossier.cap_transport.mirset1_imported_max_level;Assert-Exact observed.runtime.effective $Observation.effective $Dossier.cap_transport.effective_max_level;Assert-Exact observed.runtime.no_level_4 $Observation.no_level_4 $Dossier.cap_transport.no_level_4;Assert-Exact observed.runtime.input_ore $Observation.input_ore_per_machine_per_level $Dossier.production.input_ore_per_machine_per_level;if(@($Observation.machines).Count -ne @($Dossier.machine_selection.machines).Count){throw 'Bob Tin machine-matrix runtime machine count differs.'};for($index=0;$index -lt @($Dossier.machine_selection.machines).Count;$index++){Assert-MatrixMachine "observed.runtime.machines[$index]" @($Observation.machines)[$index] @($Dossier.machine_selection.machines)[$index] $true}}
function Assert-MatrixDriftControls($Dossier){
  $data=[pscustomobject]@{recipe=$Dossier.route.recipe;category=$Dossier.route.category;owner_count=1;effect_change=0.02;machines=@($Dossier.machine_selection.machines|ForEach-Object{$_|ConvertTo-Json -Depth 6|ConvertFrom-Json});unadmitted_matching_entities=@()}
  $data.machines[1].energy_type='steam';$caught=$false;try{Assert-MatrixData $data $Dossier}catch{$caught=$true};if(-not $caught){throw 'Bob Tin machine-matrix data-stage drift control was accepted.'}
  $runtimeMachines=@()
  foreach($machine in @($Dossier.machine_selection.machines)){
    $levels=@()
    foreach($level in @($Dossier.production.levels)){$levels += [pscustomobject]@{completed_level=$level.completed_level;input_ore=100;input_exhausted=$true;output=$level.expected_output;bonus=$level.expected_bonus;output_drain_observed=$true}}
    $runtimeMachines += [pscustomobject]@{name=$machine.name;entity_type=$machine.entity_type;place_item=$machine.place_item;energy_type=$machine.energy_type;crafting_categories=@($machine.crafting_categories);levels=$levels}
  }
  $runtime=[pscustomobject]@{raw_direct=2;mirset1_imported=3;effective=3;no_level_4=$true;input_ore_per_machine_per_level=100;machines=$runtimeMachines}
  $runtime.machines[3].levels[2].output=105;$caught=$false;try{Assert-MatrixRuntime $runtime $Dossier}catch{$caught=$true};if(-not $caught){throw 'Bob Tin machine-matrix runtime dynamic drift control was accepted.'}
  $dataSource=Get-Content -Raw -LiteralPath (Join-Path $script:fixture 'data-final-fixes.lua');$controlSource=Get-Content -Raw -LiteralPath (Join-Path $script:fixture 'control.lua')
  foreach($sentinel in @('data.raw[entity_type]','item.place_result == name','#unadmitted ~= 0')){if(-not $dataSource.Contains($sentinel)){throw "Bob Tin machine-matrix data source sentinel is absent: $sentinel"}}
  foreach($sentinel in @('get_inventory(defines.inventory.crafter_output)','entity.energy = 1000000000','output.remove')){if(-not $controlSource.Contains($sentinel)){throw "Bob Tin machine-matrix runtime source sentinel is absent: $sentinel"}}
}

$engineSha256=(Get-FileHash -LiteralPath $engine -Algorithm SHA256).Hash
if($engineSha256 -cne $expectedEngineSha256){throw "Bob Tin machine-matrix requires exact F210 engine SHA-256 $expectedEngineSha256."}
$version=(& $engine --version|Out-String);if($LASTEXITCODE -ne 0 -or $version -notmatch 'Version: 2[.]1[.]17'){throw 'Bob Tin machine-matrix requires exact Steam F210 2.1.17.'};$engineVersion=([regex]::Match($version,'Version:\s+2[.]1[.]17[^\r\n]*').Value).Trim()
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim();$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim();if($sourceCommit -notmatch '^[0-9a-f]{40}$' -or $sourceTree -notmatch '^[0-9a-f]{40}$'){throw 'Bob Tin machine-matrix requires exact source commit/tree bindings.'}
$sourceChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod);if($sourceChanges.Count -ne 0){throw "Bob Tin machine-matrix refuses a changed package-source root: $($sourceChanges -join '; ')"}

$script:fixture=Join-Path $repo 'fixtures/assert-bob-tin-machine-matrix';$dossier=Join-Path $script:fixture 'machine-matrix-dossier.json';$packageSource=Join-Path $repo 'src/mod/package-source.json'
try{$script:record=Get-Content -Raw -LiteralPath $dossier|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Tin machine-matrix dossier JSON is invalid: $($_.Exception.Message)"}
Assert-Properties root $record @('schema','kind','scope','target','official_mod_closure','route','mir_owner','machine_selection','runtime_energy_provisioning','runtime_recipe_assignment','cap_transport','production','evidence_role','explicit_non_claims');Assert-Exact schema $record.schema 1;Assert-Exact kind $record.kind 'MIR4BobTinManufacturingMachineMatrixV1';Assert-Exact scope $record.scope 'F210 Bob-only finite Tin manufacturing-machine matrix diagnostic; package-excluded evidence';Assert-Exact evidence_role $record.evidence_role 'bounded manufacturing-machine diagnostic input to A06 BA-07 A17 and PROG-01; not completion authority';Assert-StringArray explicit_non_claims $record.explicit_non_claims $expectedNonClaims
Assert-Properties target $record.target @('factorio_line','factorio_version','engine_sha256','boblibrary','bobores','bobplates');Assert-Exact target.line $record.target.factorio_line '2.1';Assert-Exact target.version $record.target.factorio_version '2.1.17';Assert-Exact target.engine $record.target.engine_sha256 $expectedEngineSha256;foreach($name in $expectedArchives.Keys){Assert-Properties "target.$name" $record.target.$name @('version','sha256');Assert-Exact "target.$name.version" $record.target.$name.version $expectedArchives[$name].version;Assert-Exact "target.$name.sha256" $record.target.$name.sha256 $expectedArchives[$name].sha256}
if(@($record.official_mod_closure).Count -ne 5){throw 'Bob Tin machine-matrix official closure count differs.'};$expectedOfficial=@(@{name='base';enabled=$true},@{name='elevated-rails';enabled=$false},@{name='quality';enabled=$false},@{name='recycler';enabled=$false},@{name='space-age';enabled=$false});for($index=0;$index -lt 5;$index++){Assert-Properties "official_mod_closure[$index]" @($record.official_mod_closure)[$index] @('name','enabled');Assert-Exact "official_mod_closure[$index].name" @($record.official_mod_closure)[$index].name $expectedOfficial[$index].name;Assert-Exact "official_mod_closure[$index].enabled" @($record.official_mod_closure)[$index].enabled $expectedOfficial[$index].enabled}
Assert-Properties route $record.route @('recipe','category','input','output','allow_productivity','auto_recycle');Assert-Exact route.recipe $record.route.recipe 'bob-tin-plate';Assert-Exact route.category $record.route.category 'smelting';Assert-Entry route.input $record.route.input item bob-tin-ore 1;Assert-Entry route.output $record.route.output item bob-tin-plate 1;Assert-Exact route.productivity $record.route.allow_productivity $true;Assert-Exact route.recycle $record.route.auto_recycle $false
Assert-Properties mir_owner $record.mir_owner @('stream_key','technology','effect_type','effect_recipe','effect_change_per_completed_level','exact_owner_count','prototype_max_level');Assert-Exact owner.stream $record.mir_owner.stream_key 'research_material_tin';Assert-Exact owner.technology $record.mir_owner.technology 'recipe-prod-research_material_tin-1';Assert-Exact owner.type $record.mir_owner.effect_type 'change-recipe-productivity';Assert-Exact owner.recipe $record.mir_owner.effect_recipe 'bob-tin-plate';Assert-Exact owner.change $record.mir_owner.effect_change_per_completed_level 0.02;Assert-Exact owner.count $record.mir_owner.exact_owner_count 1;Assert-Exact owner.max $record.mir_owner.prototype_max_level 'infinite'
Assert-Properties selection $record.machine_selection @('entity_types_scanned','required_crafting_category','required_place_item_rule','supported_runtime_energy_types','runtime_category_validation_rule','expected_unadmitted_matching_entities','machines');Assert-StringArray selection.types $record.machine_selection.entity_types_scanned @('assembling-machine','furnace');Assert-Exact selection.category $record.machine_selection.required_crafting_category 'smelting';Assert-Exact selection.place_rule $record.machine_selection.required_place_item_rule 'item-place-result-equals-entity-name';Assert-StringArray selection.energy $record.machine_selection.supported_runtime_energy_types @('burner','electric');Assert-Exact selection.runtime_category_validation_rule $record.machine_selection.runtime_category_validation_rule 'contains-exact-data-stage-categories-plus-entity-type-specific-recipe-assignment';Assert-StringArray selection.unadmitted $record.machine_selection.expected_unadmitted_matching_entities @();if(@($record.machine_selection.machines).Count -ne 6){throw 'Bob Tin machine-matrix must bind exactly six admitted machines.'};for($index=0;$index -lt 6;$index++){Assert-MatrixMachine "selection.machines[$index]" @($record.machine_selection.machines)[$index] @($record.machine_selection.machines)[$index] $false}
Assert-Properties energy $record.runtime_energy_provisioning @('burner','electric');Assert-Exact energy.burner $record.runtime_energy_provisioning.burner 'solid-fuel-in-crafter-fuel-inventory';Assert-Exact energy.electric $record.runtime_energy_provisioning.electric 'verified-per-tick-electric-buffer'
Assert-Properties recipe_assignment $record.runtime_recipe_assignment @('assembling-machine','furnace');Assert-Exact recipe_assignment.assembler $record.runtime_recipe_assignment.'assembling-machine' 'direct-set-recipe-bob-tin-plate';Assert-Exact recipe_assignment.furnace $record.runtime_recipe_assignment.furnace 'automatic-smelting-selection-validated-by-bob-tin-plate-output'
Assert-Properties caps $record.cap_transport @('raw_direct_max_level','mirset1_imported_max_level','effective_max_level','no_level_4');Assert-Exact caps.raw $record.cap_transport.raw_direct_max_level 2;Assert-Exact caps.imported $record.cap_transport.mirset1_imported_max_level 3;Assert-Exact caps.effective $record.cap_transport.effective_max_level 3;Assert-Exact caps.no4 $record.cap_transport.no_level_4 $true
Assert-Properties production $record.production @('input_ore_per_machine_per_level','output_drain_observed','requires_input_exhaustion','levels');Assert-Exact production.input $record.production.input_ore_per_machine_per_level 100;Assert-Exact production.drain $record.production.output_drain_observed $true;Assert-Exact production.exhaustion $record.production.requires_input_exhaustion $true;if(@($record.production.levels).Count -ne 4){throw 'Bob Tin machine-matrix production level count differs.'};for($index=0;$index -lt 4;$index++){$row=@($record.production.levels)[$index];Assert-Properties "production.levels[$index]" $row @('completed_level','expected_output','expected_bonus');Assert-Exact "production.levels[$index].completed_level" $row.completed_level $index;Assert-Exact "production.levels[$index].expected_output" $row.expected_output (100+2*$index);Assert-Exact "production.levels[$index].expected_bonus" $row.expected_bonus (2*$index)}
Assert-MatrixDriftControls $record

. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1')
. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1')
. (Join-Path $repo 'tools/lib/validation/SettingsOverrides.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)){$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('BOB-TIN-MACHINE-MATRIX-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/bob-tin-machine-matrix/packages';$CandidateZip=[string]$candidate.archive_path}
$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try{$forbidden=@($zip.Entries|Where-Object {$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "Candidate includes package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';New-Item -ItemType Directory -Force -Path $mods,(Join-Path $run 'userdata')|Out-Null;Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveHashes=[ordered]@{};foreach($name in $expectedArchives.Keys){$path=Join-Path $bobMods $expectedArchives[$name].file;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Bob Tin machine-matrix archive is absent $path"};$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;if($hash -cne $expectedArchives[$name].sha256){throw "Bob Tin machine-matrix archive hash differs $name"};$archiveHashes[$name]=$hash;Copy-Item -LiteralPath $path -Destination $mods}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-bob-tin-machine-matrix' -Version '0.1.0' -ModsDir $mods|Out-Null
Initialize-MIRSettingsOverrideMod -ModsDir $mods -FactorioVersion '2.1';Set-CopiedStartupSettingDefaults -ModsDir $mods -Overrides @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=2};Set-CopiedMIRSettingsProfileDefault -ModsDir $mods -Settings @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=3};Complete-MIRSettingsOverrideMod -ModsDir $mods
@{mods=@(@{name='base';enabled=$true},@{name='space-age';enabled=$false},@{name='elevated-rails';enabled=$false},@{name='quality';enabled=$false},@{name='recycler';enabled=$false},@{name='more-infinite-research';enabled=$true},@{name='boblibrary';enabled=$true},@{name='bobores';enabled=$true},@{name='bobplates';enabled=$true},@{name='mir-fixture-assert-bob-tin-machine-matrix';enabled=$true},@{name='mir-validation-settings-overrides';enabled=$true})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $mods 'mod-list.json') -Encoding utf8
$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false))
function Invoke-MatrixEngine([string]$Name,[string[]]$Arguments){$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--mod-directory',$mods)+$Arguments){[void]$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(180000)){$process.Kill($true);throw "Bob Tin machine-matrix engine timeout: $run"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run "engine-$Name.log"),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "Bob Tin machine-matrix engine failed during ${Name}: $run`n$($text.Substring([Math]::Max(0,$text.Length-3000)))"}}finally{$process.Dispose()};$factorioLog=Join-Path $run 'userdata/factorio-current.log';if(-not(Test-Path -LiteralPath $factorioLog -PathType Leaf)){throw "Bob Tin machine-matrix Factorio log is absent after $Name."};$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
$save=Join-Path $run 'bob-tin-machine-matrix.zip';$createLog=Invoke-MatrixEngine -Name create -Arguments @('--create',$save);if(-not(Test-Path -LiteralPath $save -PathType Leaf)){throw 'Bob Tin machine-matrix save was not created.'};$dataObservation=Get-MatrixObservation (Get-Content -Raw -LiteralPath $createLog) 'DATA';Assert-MatrixData $dataObservation $record
$runtimeLog=Invoke-MatrixEngine -Name runtime -Arguments @('--benchmark',$save,'--benchmark-ticks','30000','--benchmark-runs','1');$runtimeObservation=Get-MatrixObservation (Get-Content -Raw -LiteralPath $runtimeLog) 'RUNTIME';Assert-MatrixRuntime $runtimeObservation $record
$receipt=[ordered]@{schema=1;status='passed';scope='F210 Bob-only finite Tin manufacturing-machine matrix diagnostic';target='F210';engine_version=$engineVersion;engine_sha256=$engineSha256;source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=(Get-FileHash -LiteralPath $packageSource -Algorithm SHA256).Hash;package_source_roots_clean=$true};candidate_sha256=(Get-FileHash -LiteralPath $candidateZip -Algorithm SHA256).Hash;candidate_package_excludes_fixture_test_docs_mir_build_dist=$true;bob_archive_sha256=$archiveHashes;dossier_sha256=(Get-FileHash -LiteralPath $dossier -Algorithm SHA256).Hash;fixture_hashes=[ordered]@{info=(Get-FileHash (Join-Path $fixture 'info.json') -Algorithm SHA256).Hash;dossier=(Get-FileHash $dossier -Algorithm SHA256).Hash;data_final_fixes=(Get-FileHash (Join-Path $fixture 'data-final-fixes.lua') -Algorithm SHA256).Hash;control=(Get-FileHash (Join-Path $fixture 'control.lua') -Algorithm SHA256).Hash};harness_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;official_mod_closure=$record.official_mod_closure;data_observation=$dataObservation;cap_transport=[ordered]@{raw_direct=$runtimeObservation.raw_direct;mirset1_imported=$runtimeObservation.mirset1_imported;effective=$runtimeObservation.effective;no_level_4=$runtimeObservation.no_level_4};production=$runtimeObservation.machines;logs=[ordered]@{create=(Get-FileHash -LiteralPath $createLog -Algorithm SHA256).Hash;runtime=(Get-FileHash -LiteralPath $runtimeLog -Algorithm SHA256).Hash};non_claims=$expectedNonClaims}
$receipt|ConvertTo-Json -Depth 16|Set-Content -LiteralPath (Join-Path $run 'result.json') -Encoding utf8
$receipt|ConvertTo-Json -Depth 16
Write-Output "Evidence: $run"
