# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]
param(
  [string]$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path,
  [string]$FactorioBin='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',
  [string]$CandidateZip='',
  [string]$BobModsDir='C:\Projects\Factorio\testmods\2.1',
  [string]$OutputRoot='build/tests/mir42-bob-tin-persisted-state'
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$repo=(Resolve-Path -LiteralPath $RepoRoot).Path
$engine=(Resolve-Path -LiteralPath $FactorioBin).Path
$bobMods=(Resolve-Path -LiteralPath $BobModsDir).Path
$output=[IO.Path]::GetFullPath((Join-Path $repo $OutputRoot))
if(-not $output.StartsWith((Join-Path $repo 'build')+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'Bob Tin persisted-state outputs must be under build.'}
$expectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8'
$expectedArchives=[ordered]@{
  boblibrary=[ordered]@{file='boblibrary_3.0.0.zip';version='3.0.0';sha256='49EAE2D4D8E58EBD28BAFDB7E71D5307CBCE2077E0642440ED7EC527D466FFC4'}
  bobores=[ordered]@{file='bobores_3.0.0.zip';version='3.0.0';sha256='7F8E33E35F59BB3F2CD72E3AB2FED30D1C2AE9C117E3731324AC307D9965082B'}
  bobplates=[ordered]@{file='bobplates_3.0.1.zip';version='3.0.1';sha256='503D7BF6E88DA1F99463AC00CEC959C2003B2701D80DC4A564CF2EC3920AC8AF'}
}
$expectedOfficialMods=@('base','elevated-rails','quality','recycler','space-age')
$expectedNonClaims=@('older-candidate-upgrade-or-migration','future-companion-or-infinite-continuation','F200','Angel-or-combined-Bob-Angel-admission','multiplayer-or-second-force-isolation','research-browser','route-safety-or-balance','science-frontier-or-progression-completion','full-BA-07-or-PROG-01','release-readiness')
function Assert-Exact([string]$Name,$Actual,$Expected){if($null -eq $Actual -and $null -eq $Expected){return};if($null -eq $Actual -or $null -eq $Expected -or $Actual -cne $Expected){throw "Bob Tin persisted-state $Name differs: expected '$Expected', actual '$Actual'."}}
function Assert-Double([string]$Name,$Actual,$Expected){if([Math]::Abs(([double]$Actual)-([double]$Expected)) -gt 0.000001){throw "Bob Tin persisted-state $Name differs: expected '$Expected', actual '$Actual'."}}
function Assert-Props([string]$Name,$Object,[string[]]$Expected){if($null -eq $Object){throw "Bob Tin persisted-state $Name is absent."};$actual=@($Object.PSObject.Properties.Name|Sort-Object);$wanted=@($Expected|Sort-Object);if(($actual -join "`n") -cne ($wanted -join "`n")){throw "Bob Tin persisted-state $Name properties differ."}}
function Assert-Array([string]$Name,$Actual,[string[]]$Expected){$values=@($Actual|ForEach-Object{[string]$_});if(($values -join "`n") -cne ($Expected -join "`n")){throw "Bob Tin persisted-state $Name differs."}}
function ConvertTo-Canonical($Value){if($null -eq $Value){return $null};if($Value -is [string]){return [string]$Value};if($Value -is [System.Collections.IDictionary]){$out=[ordered]@{};foreach($key in @($Value.Keys|ForEach-Object{[string]$_}|Sort-Object)){$out[$key]=ConvertTo-Canonical $Value[$key]};return $out};if($Value -is [pscustomobject]){$out=[ordered]@{};foreach($property in @($Value.PSObject.Properties.Name|Sort-Object)){$out[$property]=ConvertTo-Canonical $Value.$property};return $out};if($Value -is [System.Collections.IEnumerable]){$items=@($Value|ForEach-Object{ConvertTo-Canonical $_});return ,$items};return $Value}
function Copy-Observation($Value){return (ConvertTo-Canonical $Value|ConvertTo-Json -Depth 30|ConvertFrom-Json)}
function Read-Observation([string]$Text,[string]$Stage){$matches=[regex]::Matches($Text,"\[mir-bob-tin-persisted-state\] $Stage JSON (?<json>\{[^\r\n]+\})");if($matches.Count -ne 1){throw "Bob Tin persisted-state requires exactly one $Stage JSON record; observed $($matches.Count)."};try{return $matches[0].Groups['json'].Value|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Tin persisted-state $Stage JSON is invalid: $($_.Exception.Message)"}}

$fixture=Join-Path $repo 'fixtures/assert-bob-tin-persisted-state'
$dossierPath=Join-Path $fixture 'persisted-state-dossier.json'
try{$dossier=Get-Content -Raw -LiteralPath $dossierPath|ConvertFrom-Json -ErrorAction Stop}catch{throw "Bob Tin persisted-state dossier is invalid JSON: $($_.Exception.Message)"}
Assert-Props dossier $dossier @('schema','kind','scope','target','official_mod_closure','archive_closure','anchor','cap_transport','persisted_state','serial_cycles','evidence_role','explicit_non_claims')
Assert-Exact dossier.schema $dossier.schema 1
Assert-Exact dossier.kind $dossier.kind 'MIR4BobTinPersistedResearchStateV1'
Assert-Exact dossier.scope $dossier.scope 'F210 Bob-only current-candidate Tin persisted force research state across two serialized reload/save cycles; package-excluded fixture evidence'
Assert-Props dossier.target $dossier.target @('factorio_line','factorio_version','engine_sha256')
Assert-Exact dossier.target.factorio_line $dossier.target.factorio_line '2.1';Assert-Exact dossier.target.factorio_version $dossier.target.factorio_version '2.1.17';Assert-Exact dossier.target.engine_sha256 $dossier.target.engine_sha256 $expectedEngineSha256
if(@($dossier.official_mod_closure).Count -ne $expectedOfficialMods.Count){throw 'Bob Tin persisted-state official closure count differs.'};for($index=0;$index -lt $expectedOfficialMods.Count;$index++){$row=@($dossier.official_mod_closure)[$index];Assert-Props "official_mod_closure[$index]" $row @('name','enabled');Assert-Exact "official_mod_closure[$index].name" $row.name $expectedOfficialMods[$index];Assert-Exact "official_mod_closure[$index].enabled" $row.enabled $true}
if(@($dossier.archive_closure).Count -ne $expectedArchives.Count){throw 'Bob Tin persisted-state archive closure count differs.'};for($index=0;$index -lt @($dossier.archive_closure).Count;$index++){$row=@($dossier.archive_closure)[$index];Assert-Props "archive_closure[$index]" $row @('name','version','sha256');$name=[string]$row.name;if(-not $expectedArchives.Contains($name)){throw "Bob Tin persisted-state unexpected archive $name"};Assert-Exact "archive.$name.version" $row.version $expectedArchives[$name].version;Assert-Exact "archive.$name.sha256" $row.sha256 $expectedArchives[$name].sha256}
Assert-Props dossier.anchor $dossier.anchor @('stream_key','technology','effect_type','effect_recipe','effect_change_per_completed_level','exact_owner_count','prototype_max_level');Assert-Exact anchor.stream $dossier.anchor.stream_key 'research_material_tin';Assert-Exact anchor.technology $dossier.anchor.technology 'recipe-prod-research_material_tin-1';Assert-Exact anchor.effect_type $dossier.anchor.effect_type 'change-recipe-productivity';Assert-Exact anchor.effect_recipe $dossier.anchor.effect_recipe 'bob-tin-plate';Assert-Double anchor.effect_change $dossier.anchor.effect_change_per_completed_level 0.02;Assert-Exact anchor.owner_count $dossier.anchor.exact_owner_count 1;Assert-Exact anchor.prototype_max_level $dossier.anchor.prototype_max_level 'infinite'
Assert-Props dossier.cap_transport $dossier.cap_transport @('raw_direct_max_level','mirset1_imported_max_level','effective_max_level','maximum_level_policy_binding_count','maximum_level_policy_setting');Assert-Exact cap.raw $dossier.cap_transport.raw_direct_max_level 2;Assert-Exact cap.imported $dossier.cap_transport.mirset1_imported_max_level 3;Assert-Exact cap.effective $dossier.cap_transport.effective_max_level 3;Assert-Exact cap.binding_count $dossier.cap_transport.maximum_level_policy_binding_count 1;Assert-Exact cap.setting $dossier.cap_transport.maximum_level_policy_setting 'ips-max-level-research_material_tin'
Assert-Props dossier.persisted_state $dossier.persisted_state @('completed_levels','current_research_technology_level','current_research','queue','fractional_progress','derived_earned_modifier_rule','derived_earned_modifier');Assert-Exact state.completed $dossier.persisted_state.completed_levels 2;Assert-Exact state.current_level $dossier.persisted_state.current_research_technology_level 3;Assert-Exact state.current $dossier.persisted_state.current_research $dossier.anchor.technology;Assert-Array state.queue $dossier.persisted_state.queue @($dossier.anchor.technology);Assert-Double state.progress $dossier.persisted_state.fractional_progress 0.42;Assert-Exact state.derivation $dossier.persisted_state.derived_earned_modifier_rule 'completed_levels-times-runtime-observed-anchor-effect';Assert-Double state.derived $dossier.persisted_state.derived_earned_modifier 0.04
Assert-Props dossier.serial_cycles $dossier.serial_cycles @('initial_generation','cycle_one_predecessor_generation','cycle_one_generation','cycle_two_predecessor_generation','cycle_two_generation','terminal_generation');foreach($pair in @{initial_generation=0;cycle_one_predecessor_generation=0;cycle_one_generation=1;cycle_two_predecessor_generation=1;cycle_two_generation=2;terminal_generation=2}.GetEnumerator()){Assert-Exact "serial.$($pair.Key)" $dossier.serial_cycles.$($pair.Key) $pair.Value}
Assert-Exact dossier.evidence_role $dossier.evidence_role 'bounded current-candidate persisted-state diagnostic input to X04 BA-07 and PROG-01; not migration or progression completion authority';Assert-Array dossier.non_claims $dossier.explicit_non_claims $expectedNonClaims

function Assert-DataObservation($Observation){Assert-Props data $Observation @('technology','recipe','owner_count','effect_change','prototype_max_level');Assert-Exact data.technology $Observation.technology $dossier.anchor.technology;Assert-Exact data.recipe $Observation.recipe $dossier.anchor.effect_recipe;Assert-Exact data.owner_count $Observation.owner_count $dossier.anchor.exact_owner_count;Assert-Double data.effect_change $Observation.effect_change $dossier.anchor.effect_change_per_completed_level;Assert-Exact data.prototype_max_level $Observation.prototype_max_level $dossier.anchor.prototype_max_level}
function Assert-StateObservation($Observation,[string]$ExpectedStage,[int]$ExpectedGeneration,[int]$ExpectedPredecessor){Assert-Props "observation.$ExpectedStage" $Observation @('stage','generation','predecessor_generation','completed_levels','current_research_technology_level','current_research','queue','fractional_progress','observed_effect_change','derived_earned_modifier','raw_direct_max_level','mirset1_imported_max_level','effective_max_level','policy_binding_count','policy_setting','policy_technology');Assert-Exact "$ExpectedStage.stage" $Observation.stage ($ExpectedStage.ToLowerInvariant());Assert-Exact "$ExpectedStage.generation" $Observation.generation $ExpectedGeneration;Assert-Exact "$ExpectedStage.predecessor" $Observation.predecessor_generation $ExpectedPredecessor;Assert-Exact "$ExpectedStage.completed" $Observation.completed_levels $dossier.persisted_state.completed_levels;Assert-Exact "$ExpectedStage.current_level" $Observation.current_research_technology_level $dossier.persisted_state.current_research_technology_level;Assert-Exact "$ExpectedStage.current" $Observation.current_research $dossier.persisted_state.current_research;Assert-Array "$ExpectedStage.queue" $Observation.queue @($dossier.persisted_state.queue);Assert-Double "$ExpectedStage.progress" $Observation.fractional_progress $dossier.persisted_state.fractional_progress;Assert-Double "$ExpectedStage.effect" $Observation.observed_effect_change $dossier.anchor.effect_change_per_completed_level;Assert-Double "$ExpectedStage.derived" $Observation.derived_earned_modifier $dossier.persisted_state.derived_earned_modifier;Assert-Double "$ExpectedStage.derived formula" $Observation.derived_earned_modifier ($Observation.completed_levels*$Observation.observed_effect_change);Assert-Exact "$ExpectedStage.raw" $Observation.raw_direct_max_level $dossier.cap_transport.raw_direct_max_level;Assert-Exact "$ExpectedStage.imported" $Observation.mirset1_imported_max_level $dossier.cap_transport.mirset1_imported_max_level;Assert-Exact "$ExpectedStage.effective" $Observation.effective_max_level $dossier.cap_transport.effective_max_level;Assert-Exact "$ExpectedStage.policy count" $Observation.policy_binding_count $dossier.cap_transport.maximum_level_policy_binding_count;Assert-Exact "$ExpectedStage.policy setting" $Observation.policy_setting $dossier.cap_transport.maximum_level_policy_setting;Assert-Exact "$ExpectedStage.policy technology" $Observation.policy_technology $dossier.anchor.technology}
function Assert-CanonicalStateRecord($Record,[string]$Name){if($Record.queue -isnot [System.Array]){throw "Bob Tin persisted-state canonical $Name queue is not an array."};Assert-Array "canonical.$Name.queue" $Record.queue @($dossier.persisted_state.queue)}
function Assert-DriftNegatives($Initial,$CycleOne,$CycleTwo,$Terminal){$drifts=@(@{value=(Copy-Observation $Initial);property='fractional_progress';replacement=0.41;stage='INITIAL';generation=0;predecessor=-1},@{value=(Copy-Observation $CycleOne);property='generation';replacement=2;stage='CYCLE';generation=1;predecessor=0},@{value=(Copy-Observation $CycleTwo);property='policy_binding_count';replacement=2;stage='CYCLE';generation=2;predecessor=1},@{value=(Copy-Observation $Terminal);property='queue';replacement=@('unexpected');stage='TERMINAL';generation=2;predecessor=1});foreach($drift in $drifts){$drift.value.($drift.property)=$drift.replacement;$caught=$false;try{Assert-StateObservation $drift.value $drift.stage $drift.generation $drift.predecessor}catch{$caught=$true};if(-not $caught){throw "Bob Tin persisted-state drift negative for $($drift.property) was accepted."}};$control=Get-Content -Raw -LiteralPath (Join-Path $fixture 'control.lua');if($control -notmatch 'game[.]server_save\(save_name\)' -or $control -notmatch 'loaded_generation = state and state[.]generation or nil' -or $control -notmatch 'state[.]generation ~= loaded_generation' -or $control -notmatch 'loaded_generation == 0' -or $control -notmatch 'loaded_generation == 1'){throw 'Bob Tin persisted-state one-transition-per-process guard is absent.'}}

$engineSha256=(Get-FileHash -LiteralPath $engine -Algorithm SHA256).Hash;if($engineSha256 -cne $expectedEngineSha256){throw "Bob Tin persisted-state requires exact F210 engine SHA-256 $expectedEngineSha256."};$engineVersion=(& $engine --version|Out-String);if($LASTEXITCODE -ne 0 -or $engineVersion -notmatch 'Version: 2[.]1[.]17'){throw 'Bob Tin persisted-state requires exact Steam F210 2.1.17 engine.'}
$sourceCommit=(& git -C $repo rev-parse HEAD).Trim();$sourceTree=(& git -C $repo rev-parse 'HEAD^{tree}').Trim();if($sourceCommit -notmatch '^[0-9a-f]{40}$' -or $sourceTree -notmatch '^[0-9a-f]{40}$'){throw 'Bob Tin persisted-state cannot bind source commit/tree.'};$sourceRootChanges=@(& git -C $repo status --porcelain --untracked-files=all -- src/mod);if($sourceRootChanges.Count -ne 0){throw "Bob Tin persisted-state refuses changed package-source root: $($sourceRootChanges -join '; ')"};$packageSource=Join-Path $repo 'src/mod/package-source.json'
. (Join-Path $repo 'tools/mir/application/package/TargetMaterializer.ps1');. (Join-Path $repo 'tools/lib/validation/FactorioProcess.ps1');. (Join-Path $repo 'tools/lib/validation/SettingsOverrides.ps1')
if([string]::IsNullOrWhiteSpace($CandidateZip)){$candidate=New-MIR4TargetPackage -RepoRoot $repo -Target f210 -CandidateId ('BOB-TIN-PERSISTED-STATE-'+[guid]::NewGuid().ToString('N').Substring(0,8).ToUpperInvariant()) -SourceVersion '4.2.0' -DistributionVersion '4.2.21000' -OutputRoot 'build/bob-tin-persisted-state/packages';$CandidateZip=[string]$candidate.archive_path};$candidateZip=(Resolve-Path -LiteralPath $CandidateZip).Path
Add-Type -AssemblyName System.IO.Compression.FileSystem;$zip=[IO.Compression.ZipFile]::OpenRead($candidateZip);try{$forbidden=@($zip.Entries|Where-Object {$_.FullName -match '(^|/)(fixtures|tests|docs|[.]mir|build|dist)(/|$)'});if($forbidden.Count -ne 0){throw "Candidate includes package-excluded path $($forbidden[0].FullName)"}}finally{$zip.Dispose()}
$run=Join-Path $output ([guid]::NewGuid().ToString('N'));$mods=Join-Path $run 'mods';$userdata=Join-Path $run 'userdata';New-Item -ItemType Directory -Force -Path $mods,$userdata,(Join-Path $userdata 'saves')|Out-Null;Copy-Item -LiteralPath $candidateZip -Destination $mods
$archiveHashes=[ordered]@{};foreach($name in $expectedArchives.Keys){$path=Join-Path $bobMods $expectedArchives[$name].file;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Bob Tin persisted-state archive absent $path"};$hash=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash;if($hash -cne $expectedArchives[$name].sha256){throw "Bob Tin persisted-state archive hash differs $name"};$archiveHashes[$name]=$hash;Copy-Item -LiteralPath $path -Destination $mods}
Publish-MIRModDirectoryArchive -Source $fixture -Name 'mir-fixture-assert-bob-tin-persisted-state' -Version '0.1.0' -ModsDir $mods|Out-Null;Initialize-MIRSettingsOverrideMod -ModsDir $mods -FactorioVersion '2.1';Set-CopiedStartupSettingDefaults -ModsDir $mods -Overrides @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=2};Set-CopiedMIRSettingsProfileDefault -ModsDir $mods -Settings @{'ips-enable-research_material_tin'=$true;'ips-max-level-research_material_tin'=3};Complete-MIRSettingsOverrideMod -ModsDir $mods
@{mods=@(@{name='base';enabled=$true},@{name='space-age';enabled=$true},@{name='elevated-rails';enabled=$true},@{name='quality';enabled=$true},@{name='recycler';enabled=$true},@{name='more-infinite-research';enabled=$true},@{name='boblibrary';enabled=$true},@{name='bobores';enabled=$true},@{name='bobplates';enabled=$true},@{name='mir-fixture-assert-bob-tin-persisted-state';enabled=$true},@{name='mir-validation-settings-overrides';enabled=$true})}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $mods 'mod-list.json') -Encoding utf8
$engineRoot=Split-Path (Split-Path (Split-Path $engine -Parent)-Parent)-Parent;[IO.File]::WriteAllText((Join-Path $run 'config.ini'),"[path]`nread-data=$($engineRoot.Replace('\','/'))/data`nwrite-data=$($run.Replace('\','/'))/userdata`n",[Text.UTF8Encoding]::new($false));@{name='MIR persisted state';description='';tags=@();max_players=1;visibility=@{public=$false;lan=$false};require_user_verification=$false;auto_pause=$false}|ConvertTo-Json -Depth 5|Set-Content -LiteralPath (Join-Path $run 'server-settings.json') -Encoding utf8
function Invoke-PersistedEngine([string]$Name,[string[]]$Arguments){$factorioLog=Join-Path $userdata 'factorio-current.log';if(Test-Path -LiteralPath $factorioLog){Remove-Item -LiteralPath $factorioLog -Force};$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';$start.RedirectStandardOutput=$true;$start.RedirectStandardError=$true;foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--no-log-rotation','--disable-audio','--mod-directory',$mods)+$Arguments){[void]$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);try{$stdout=$process.StandardOutput.ReadToEndAsync();$stderr=$process.StandardError.ReadToEndAsync();if(-not $process.WaitForExit(120000)){$process.Kill($true);throw "Bob Tin persisted-state engine timeout: $run"};$text=$stdout.GetAwaiter().GetResult()+$stderr.GetAwaiter().GetResult();[IO.File]::WriteAllText((Join-Path $run "engine-$Name.log"),$text,[Text.UTF8Encoding]::new($false));if($process.ExitCode -ne 0){throw "Bob Tin persisted-state engine failed during ${Name}: $run`n$($text.Substring([Math]::Max(0,$text.Length-2500)))"}}finally{$process.Dispose()};if(-not(Test-Path -LiteralPath $factorioLog -PathType Leaf)){throw "Bob Tin persisted-state Factorio log absent after $Name"};$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
function Invoke-PersistedServerSave([string]$Name,[string]$InputSave,[string]$SavedMapPath){$factorioLog=Join-Path $userdata 'factorio-current.log';if(Test-Path -LiteralPath $factorioLog){Remove-Item -LiteralPath $factorioLog -Force};$start=[Diagnostics.ProcessStartInfo]::new($engine);$start.UseShellExecute=$false;$start.CreateNoWindow=$true;$start.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$start.Environment['SteamAppId']='427520';$start.Environment['SteamGameId']='427520';foreach($argument in @('--config',(Join-Path $run 'config.ini'),'--no-log-rotation','--disable-audio','--mod-directory',$mods,'--server-settings',(Join-Path $run 'server-settings.json'),'--start-server',$InputSave)){[void]$start.ArgumentList.Add($argument)};$process=[Diagnostics.Process]::Start($start);$ready=$false;try{$deadline=[DateTime]::UtcNow.AddSeconds(45);while([DateTime]::UtcNow -lt $deadline){if($process.HasExited){throw "Bob Tin persisted-state server exited before save during $Name with code $($process.ExitCode)."};if((Test-Path -LiteralPath $factorioLog -PathType Leaf) -and (Test-Path -LiteralPath $SavedMapPath -PathType Leaf)){$text=Get-Content -Raw -LiteralPath $factorioLog;if($text.Contains('[mir-bob-tin-persisted-state] CYCLE JSON') -and $text.Contains('Hosting game') -and $text.Contains('Saving finished')){$ready=$true;break}};Start-Sleep -Milliseconds 200};if(-not $ready){throw "Bob Tin persisted-state server did not materialize successor during ${Name}: $run"}}finally{if(-not $process.HasExited){try{$process.Kill($true)}catch{$process.Kill()}};$process.WaitForExit();$process.Dispose()};$copy=Join-Path $run "factorio-$Name.log";Copy-Item -LiteralPath $factorioLog -Destination $copy;return $copy}
$initialSave=Join-Path $run 'initial-current-candidate.zip';$createLog=Invoke-PersistedEngine create @('--create',$initialSave);if(-not(Test-Path -LiteralPath $initialSave -PathType Leaf)){throw 'Bob Tin persisted-state initial current-candidate save was not created.'};$createText=Get-Content -Raw -LiteralPath $createLog;$dataObservation=Read-Observation $createText 'DATA';Assert-DataObservation $dataObservation;$initialObservation=Read-Observation $createText 'INITIAL';Assert-StateObservation $initialObservation 'INITIAL' 0 -1
$cycleOneSave=Join-Path $userdata 'saves/mir-bob-tin-persisted-cycle-1.zip';$cycleOneLog=Invoke-PersistedServerSave cycle-one $initialSave $cycleOneSave;if(-not(Test-Path -LiteralPath $cycleOneSave -PathType Leaf)){throw 'Bob Tin persisted-state cycle-one successor is absent.'};$cycleOneObservation=Read-Observation (Get-Content -Raw -LiteralPath $cycleOneLog) 'CYCLE';Assert-StateObservation $cycleOneObservation 'CYCLE' 1 0
$cycleTwoSave=Join-Path $userdata 'saves/mir-bob-tin-persisted-cycle-2.zip';$cycleTwoLog=Invoke-PersistedServerSave cycle-two $cycleOneSave $cycleTwoSave;if(-not(Test-Path -LiteralPath $cycleTwoSave -PathType Leaf)){throw 'Bob Tin persisted-state cycle-two successor is absent.'};$cycleTwoObservation=Read-Observation (Get-Content -Raw -LiteralPath $cycleTwoLog) 'CYCLE';Assert-StateObservation $cycleTwoObservation 'CYCLE' 2 1
$terminalLog=Invoke-PersistedEngine terminal @('--benchmark',$cycleTwoSave,'--benchmark-ticks','10','--benchmark-runs','1','--benchmark-sanitize');$terminalObservation=Read-Observation (Get-Content -Raw -LiteralPath $terminalLog) 'TERMINAL';Assert-StateObservation $terminalObservation 'TERMINAL' 2 1;Assert-DriftNegatives $initialObservation $cycleOneObservation $cycleTwoObservation $terminalObservation
$lineage=@([ordered]@{generation=0;save_file=[IO.Path]::GetFileName($initialSave);save_sha256=(Get-FileHash -LiteralPath $initialSave -Algorithm SHA256).Hash;predecessor_generation=$null;predecessor_save_file=$null;predecessor_save_sha256=$null},[ordered]@{generation=1;save_file=[IO.Path]::GetFileName($cycleOneSave);save_sha256=(Get-FileHash -LiteralPath $cycleOneSave -Algorithm SHA256).Hash;predecessor_generation=0;predecessor_save_file=[IO.Path]::GetFileName($initialSave);predecessor_save_sha256=(Get-FileHash -LiteralPath $initialSave -Algorithm SHA256).Hash},[ordered]@{generation=2;save_file=[IO.Path]::GetFileName($cycleTwoSave);save_sha256=(Get-FileHash -LiteralPath $cycleTwoSave -Algorithm SHA256).Hash;predecessor_generation=1;predecessor_save_file=[IO.Path]::GetFileName($cycleOneSave);predecessor_save_sha256=(Get-FileHash -LiteralPath $cycleOneSave -Algorithm SHA256).Hash})
if($lineage[1].predecessor_save_sha256 -cne $lineage[0].save_sha256 -or $lineage[2].predecessor_save_sha256 -cne $lineage[1].save_sha256){throw 'Bob Tin persisted-state save lineage hash binding differs.'}
$canonicalRecords=[ordered]@{initial=(ConvertTo-Canonical $initialObservation);cycle_one=(ConvertTo-Canonical $cycleOneObservation);cycle_two=(ConvertTo-Canonical $cycleTwoObservation);terminal=(ConvertTo-Canonical $terminalObservation)};foreach($entry in $canonicalRecords.GetEnumerator()){Assert-CanonicalStateRecord $entry.Value $entry.Key}
$receipt=[ordered]@{schema=1;status='passed';scope=$dossier.scope;target='F210';engine_version=$engineVersion.Trim();engine_sha256=$engineSha256;source=[ordered]@{commit=$sourceCommit;tree=$sourceTree;package_source_sha256=(Get-FileHash -LiteralPath $packageSource -Algorithm SHA256).Hash;package_source_roots_clean=$true};candidate_sha256=(Get-FileHash -LiteralPath $candidateZip -Algorithm SHA256).Hash;candidate_package_excludes_fixture_test_docs_mir_build_dist=$true;official_mod_closure=$dossier.official_mod_closure;bob_archive_sha256=$archiveHashes;dossier_sha256=(Get-FileHash -LiteralPath $dossierPath -Algorithm SHA256).Hash;fixture_hashes=[ordered]@{info=(Get-FileHash (Join-Path $fixture 'info.json') -Algorithm SHA256).Hash;dossier=(Get-FileHash $dossierPath -Algorithm SHA256).Hash;data_final_fixes=(Get-FileHash (Join-Path $fixture 'data-final-fixes.lua') -Algorithm SHA256).Hash;control=(Get-FileHash (Join-Path $fixture 'control.lua') -Algorithm SHA256).Hash};harness_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;data=$dataObservation;state_records=$canonicalRecords;save_lineage=$lineage;logs=[ordered]@{create=(Get-FileHash -LiteralPath $createLog -Algorithm SHA256).Hash;cycle_one=(Get-FileHash -LiteralPath $cycleOneLog -Algorithm SHA256).Hash;cycle_two=(Get-FileHash -LiteralPath $cycleTwoLog -Algorithm SHA256).Hash;terminal=(Get-FileHash -LiteralPath $terminalLog -Algorithm SHA256).Hash};non_claims=$expectedNonClaims}
$receipt|ConvertTo-Json -Depth 30|Set-Content -LiteralPath (Join-Path $run 'result.json') -Encoding utf8;$receipt|ConvertTo-Json -Depth 30;Write-Output "Evidence: $run"
