# MIR4-CANONICAL-EXECUTABLE-TEST
[CmdletBinding()]param([Parameter(Mandatory=$true)][string]$CandidateArchive,[string]$RepositoryRoot=(Split-Path -Parent (Split-Path -Parent $PSScriptRoot)),[string]$FactorioExe='C:\Program Files\Steam\steamapps\common\Factorio\bin\x64\factorio.exe',[ValidateRange(30,900)][int]$TimeoutSeconds=180)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop';Add-Type -AssemblyName System.IO.Compression.FileSystem
$ExpectedEngineVersion='2.1.17';$ExpectedEngineSha256='710B0278D3049564B122DAFB3CD3D0338D0BDE1CEC3B7417AE1FC3FB37AB85A8';$BrowserRoot='mir_research_browser';$FixtureName='mir-fixture-assert-browser-personal-state-continuity';$FixtureVersion='0.1.0';$MarkerName='mir-fixture-browser-personal-continuity-config-marker';$MarkerVersion='0.1.0';$PlayerAIdentity='mir-browser-player-a';$PlayerBIdentity='mir-browser-player-b';$ExpectedF210ReadmeSha256='1CB4566E6786977E6042C3A66047E2B654B95C8613585346CB19D7A195FA5DF0';$ExpectedPackageRoot='more-infinite-research_4.2.21000'
function Fail([string]$m){throw "MIR browser personal-state continuity: $m"};function Assert-True([bool]$v,[string]$m){if(-not $v){Fail $m}};function Assert-Equal($a,$e,[string]$m){if($a -cne $e){Fail "$m (actual=[$a], expected=[$e])"}}
function Assert-PropertyNames($v,[string[]]$e,[string]$p){Assert-True($null -ne $v)"$p is null";$a=@($v.PSObject.Properties.Name|Sort-Object);$x=@($e|Sort-Object);Assert-Equal($a -join "`n")($x -join "`n")"$p property set differs"}
function Get-Sha256([string]$p){$h=[Security.Cryptography.SHA256]::Create();$s=$null;try{$s=[IO.File]::OpenRead($p);return([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','')}finally{if($null -ne $s){$s.Dispose()};$h.Dispose()}}
function Get-ZipEntry([string]$a,[string]$suffix){$z=[IO.Compression.ZipFile]::OpenRead($a);try{$m=@($z.Entries|Where-Object{$_.FullName.EndsWith($suffix,[StringComparison]::Ordinal)});Assert-Equal $m.Count 1 "archive member count for $suffix";return $m[0].FullName}finally{$z.Dispose()}}
function Get-ZipEntrySha256([string]$a,[string]$n){$z=[IO.Compression.ZipFile]::OpenRead($a);$h=[Security.Cryptography.SHA256]::Create();$s=$null;try{$e=$z.GetEntry($n);Assert-True($null -ne $e)"missing archive entry $n";$s=$e.Open();return([BitConverter]::ToString($h.ComputeHash($s))).Replace('-','')}finally{if($null -ne $s){$s.Dispose()};$h.Dispose();$z.Dispose()}}
function Get-ZipEntryText([string]$a,[string]$n){$z=[IO.Compression.ZipFile]::OpenRead($a);$r=$null;try{$e=$z.GetEntry($n);Assert-True($null -ne $e)"missing archive entry $n";$r=[IO.StreamReader]::new($e.Open());return $r.ReadToEnd()}finally{if($null -ne $r){$r.Dispose()};$z.Dispose()}}
function Normalize-ZipMember([string]$n){$x=$n.Replace('\','/').Trim();Assert-True($x.Length -gt 0)'candidate has an empty archive member name';Assert-True(-not $x.StartsWith('/'))"candidate has absolute archive member: $n";$p=@($x.Split('/',[StringSplitOptions]::RemoveEmptyEntries));Assert-True($p.Count -gt 0)"candidate has empty normalized archive member: $n";foreach($q in $p){Assert-True($q -ne '.' -and $q -ne '..')"candidate has traversal archive member: $n"};return($p -join '/')}
function Test-Candidate([string]$a,[string]$hostPath,[string]$locale,[string]$readmePath){
 Assert-True(Test-Path -LiteralPath $a -PathType Leaf)"candidate archive is absent: $a";$he=Get-ZipEntry $a '/prototypes/mir/runtime/research_browser.lua';$le=Get-ZipEntry $a '/locale/en/more-infinite-research.cfg';$re=Get-ZipEntry $a '/README.md';$normalizedHost=Normalize-ZipMember $he;$normalizedLocale=Normalize-ZipMember $le;$normalizedReadme=Normalize-ZipMember $re;Assert-True($normalizedReadme -cmatch '^[^/]+/README[.]md$')"candidate governed README is not a root member: $normalizedReadme";$hh=Get-ZipEntrySha256 $a $he;$lh=Get-ZipEntrySha256 $a $le;$rh=Get-ZipEntrySha256 $a $re;Assert-Equal $hh(Get-Sha256 $hostPath)'candidate browser host bytes differ from current source';Assert-Equal $lh(Get-Sha256 $locale)'candidate en locale bytes differ from current source';Assert-Equal $rh $ExpectedF210ReadmeSha256 'candidate F210 README differs from expected governed hash';Assert-Equal $rh(Get-Sha256 $readmePath)'candidate F210 README differs from current governed template';$ht=Get-ZipEntryText $a $he;$lt=Get-ZipEntryText $a $le
 foreach($s in @('local function set_hidden(v, force, values)','local function toggle_hidden(v, force, technology)','if options.hidden ~= nil and set_hidden(v, player.force, options.hidden) then','toggle_hidden(v, player.force, tags.technology)','type(index) ~= "number"','index > core.catalogue_limit','type(technology) ~= "string"','type(name) == "string"','button(parent, "toggle-hide"','button(body, "select"','button(queue, "select"','local body = frame.add{type = "scroll-pane"','local has_hidden = false','mir_browser_section = "hidden-recovery"','button(recovery, "show-hidden"','elseif action == "show-hidden"','type(options.page) == "number"','requested_page then v.page = requested_page elseif reset_page then v.page = 1 end')){Assert-True $ht.Contains($s)"host source sentinel missing: $s"};Assert-True($lt -match '(?m)^hide=Hide from my view\r?$')'en locale hide key differs';Assert-True($lt -match '(?m)^show=Show in my view\r?$')'en locale show key differs';Assert-True($lt -match '(?m)^show-hidden=Show all hidden technologies\r?$')'en locale show-hidden key differs'
 $z=[IO.Compression.ZipFile]::OpenRead($a);try{$ms=[Collections.Generic.List[string]]::new();$roots=[Collections.Generic.List[string]]::new();foreach($e in $z.Entries){$m=Normalize-ZipMember $e.FullName;$ms.Add($m)|Out-Null;if(-not $e.FullName.EndsWith('/',[StringComparison]::Ordinal)){$parts=@($m.Split('/'));Assert-True($parts.Count -ge 2)"candidate non-directory member has no package root: $m";$roots.Add($parts[0])|Out-Null};$isGovernedReadme=($m -ceq $normalizedReadme);Assert-True($isGovernedReadme -or ($m -notmatch '(^|/)(fixtures|tests|\.mir|\.codex|\.github|build|dist|docs|scripts|tools)(/|$)|(^|/)(AGENTS\.md|README\.md)$'))"candidate includes excluded repository-only member: $m"};Assert-True($ms.Count -gt 0)'candidate has no archive members';$uniqueRoots=@($roots|Sort-Object -Unique);Assert-Equal $uniqueRoots.Count 1 'candidate package-root count';Assert-Equal $uniqueRoots[0] $ExpectedPackageRoot 'candidate package root';$rootPrefix=$ExpectedPackageRoot+'/';Assert-True($normalizedReadme.StartsWith($rootPrefix,[StringComparison]::Ordinal))'candidate governed README is outside exact package root';Assert-True($normalizedHost.StartsWith($rootPrefix,[StringComparison]::Ordinal))'candidate browser host is outside exact package root';Assert-True($normalizedLocale.StartsWith($rootPrefix,[StringComparison]::Ordinal))'candidate en locale is outside exact package root';return [pscustomobject]@{archive_sha256=Get-Sha256 $a;package_root=$uniqueRoots[0];normalized_members=@($ms|Sort-Object -Unique);host_entry=$he;locale_entry=$le;readme_entry=$re;entry_hashes=[ordered]@{research_browser_lua=$hh;en_locale_cfg=$lh;f210_readme_md=$rh}}}finally{$z.Dispose()}
}
function Write-Utf8NoBom([string]$p,[string]$t){[IO.Directory]::CreateDirectory((Split-Path -Parent $p))|Out-Null;[IO.File]::WriteAllText($p,$t,[Text.UTF8Encoding]::new($false))};function Write-Json([string]$p,$v){Write-Utf8NoBom $p($v|ConvertTo-Json -Depth 32)}
function New-FixtureArchive([string]$s,[string]$n,[string]$v,[string]$b,[string[]]$i){$d=Join-Path $b("$n`_$v");[IO.Directory]::CreateDirectory($d)|Out-Null;foreach($q in $i){$p=Join-Path $s $q;Assert-True(Test-Path -LiteralPath $p)"fixture archive input missing: $p";Copy-Item -LiteralPath $p -Destination $d -Recurse -Force};$a=Join-Path $b("$n`_$v.zip");Compress-Archive -LiteralPath $d -DestinationPath $a -CompressionLevel Optimal;return $a}
function New-FactorioConfig([string]$p,[string]$d){$d=$d.Replace('\','/');Write-Utf8NoBom $p @"
[path]
read-data=__PATH__system-read-data__
write-data=$d
"@}
function Write-PlayerData([string]$d,[string]$i){Write-Json(Join-Path $d 'player-data.json')([ordered]@{'service-username'=$i;'service-token'=''})}
function New-FreeLoopbackPort{$l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,0);try{$l.Start();return([Net.IPEndPoint]$l.LocalEndpoint).Port}finally{$l.Stop()}}
function Write-ModList([string]$d,[string[]]$on){$x=@([pscustomobject]@{name='base';enabled=$true});foreach($n in $on){$x+=[pscustomobject]@{name=$n;enabled=$true}};Write-Json(Join-Path $d 'mod-list.json')([pscustomobject]@{mods=$x})}
$owned=[Collections.Generic.List[object]]::new()
function Start-Owned([string]$stage,[string]$role,[int]$order,[string[]]$arguments){$i=[Diagnostics.ProcessStartInfo]::new();$i.FileName=$FactorioExe;$i.UseShellExecute=$false;$i.CreateNoWindow=$true;$i.WindowStyle=[Diagnostics.ProcessWindowStyle]::Hidden;$i.EnvironmentVariables['SteamAppId']='427520';$i.EnvironmentVariables['SteamGameId']='427520';foreach($a in $arguments){[void]$i.ArgumentList.Add($a)};$p=[Diagnostics.Process]::Start($i);Assert-True($null -ne $p)"failed to start owned $role process";$o=[pscustomobject]@{stage=$stage;role=$role;pid=$p.Id;stop_order=$order;process=$p;disposed=$false;exit_disposition='running';exit_code=$null};$owned.Add($o)|Out-Null;return $o}
function Assert-OwnedAlive([object[]]$items,[string]$what){foreach($i in $items){if(-not $i.disposed -and $i.process.HasExited){Fail "owned $($i.role) PID $($i.pid) exited unexpectedly while waiting for $what"}}}
function Wait-Until([scriptblock]$predicate,[string]$what,[object[]]$items){$end=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);while([DateTime]::UtcNow -lt $end){Assert-OwnedAlive $items $what;if(& $predicate){return};Start-Sleep -Milliseconds 250};Assert-OwnedAlive $items $what;Fail "timed out waiting for $what under $RunRoot"}
function Stop-Owned([string]$stage){foreach($i in @($owned|Where-Object{$_.stage -eq $stage -and -not $_.disposed}|Sort-Object stop_order)){if($i.process.HasExited){$i.exit_disposition='already-exited'}else{$i.process.Kill($true);Assert-True($i.process.WaitForExit(15000))"owned $($i.role) PID $($i.pid) did not terminate";$i.exit_disposition='terminated-by-harness'};$i.exit_code=$i.process.ExitCode;$i.process.Dispose();$i.disposed=$true}}
function Stop-AllOwned{foreach($s in @($owned|Where-Object{-not $_.disposed}|Select-Object -ExpandProperty stage -Unique)){Stop-Owned $s}}
function Get-LogText([string]$p){if(-not(Test-Path -LiteralPath $p -PathType Leaf)){return ''};$s=$null;$r=$null;try{$s=[IO.FileStream]::new($p,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::ReadWrite);$r=[IO.StreamReader]::new($s,[Text.UTF8Encoding]::new($false),$true);return $r.ReadToEnd()}finally{if($null -ne $r){$r.Dispose()}elseif($null -ne $s){$s.Dispose()}}}
function Wait-NewServerReady([string]$p,[object]$s){Wait-Until{(Test-Path -LiteralPath $p -PathType Leaf) -and ((Get-LogText $p) -match '(?m)Hosting game')}'a newly-created server log containing Hosting game' @($s)}
function Wait-Result([string]$p,[object[]]$i){Wait-Until{if(-not(Test-Path -LiteralPath $p -PathType Leaf)){return $false};try{$x=Get-Content -LiteralPath $p -Raw|ConvertFrom-Json;return $null -ne $x -and $x.schema -eq 1}catch{return $false}}"fixture result $p" $i;return(Get-Content -LiteralPath $p -Raw|ConvertFrom-Json)}
function Wait-SuccessorSave([string]$p,[string]$log,[int]$offset,[object[]]$i){Wait-Until{Test-Path -LiteralPath $p -PathType Leaf}"successor autosave $p" $i;Wait-Until{$t=Get-LogText $log;if($t.Length -le $offset){return $false};return $t.Substring($offset) -match '(?m)Saving finished'}'Saving finished after fixture result' $i}
function Start-Stage([string]$stage,[string]$save,[int]$port,[string]$serverConfig,[string]$aConfig,[string]$bConfig,[string]$mods,[string]$serverData,[string]$clientAData,[string]$clientBData,[string]$dir){
 $sl=Join-Path $serverData 'factorio-current.log';$al=Join-Path $clientAData 'factorio-current.log';$bl=Join-Path $clientBData 'factorio-current.log';foreach($p in @($sl,$al,$bl)){if(Test-Path -LiteralPath $p -PathType Leaf){Remove-Item -LiteralPath $p -Force}}
 $server=Start-Owned $stage 'server' 3 @('--start-server',$save,'--bind',"127.0.0.1:$port",'--server-settings',(Join-Path $dir 'server-settings.json'),'--config',$serverConfig,'--mod-directory',$mods,'--no-log-rotation','--disable-audio');Wait-NewServerReady $sl $server
 $common=@('--mp-connect',"127.0.0.1:$port",'--mod-directory',$mods,'--no-log-rotation','--disable-audio','--fullscreen','--window-size','1024x768','--graphics-quality','medium','--video-memory-usage','low')
 $a=Start-Owned $stage 'client-a' 1 (@('--config',$aConfig)+$common);$b=Start-Owned $stage 'client-b' 2 (@('--config',$bConfig)+$common)
 return [pscustomobject]@{server=$server;client_a=$a;client_b=$b;server_log=$sl;client_a_log=$al;client_b_log=$bl}
}
function Assert-FixtureNames($v,[string]$p){Assert-PropertyNames $v @('finite','infinite','queued')$p;Assert-Equal $v.finite 'mir-browser-personal-finite'"$p finite technology";Assert-Equal $v.infinite 'mir-browser-personal-infinite'"$p infinite technology";Assert-Equal $v.queued 'mir-browser-personal-infinite'"$p queued technology"}
function Assert-View($v,[string]$p,$mode,$row,$key,$base){Assert-PropertyNames $v @('force_index','index','main_row_present','mode_selected_index','toggle_caption_key','username') $p;Assert-True($v.index -is [int] -or $v.index -is [long])"$p index is not numeric";Assert-True($v.force_index -is [int] -or $v.force_index -is [long])"$p force index is not numeric";Assert-True($v.username -is [string] -and $v.username.Length -gt 0)"$p username is absent";if($null -ne $mode){Assert-Equal $v.mode_selected_index $mode "$p mode"};if($null -ne $row){Assert-Equal $v.main_row_present $row "$p direct main row"};if($null -ne $key){Assert-Equal $v.toggle_caption_key $key "$p LocalisedString key"};if($null -ne $base){Assert-Equal $v.index $base.index "$p player index changed";Assert-Equal $v.username $base.username "$p service username changed";Assert-Equal $v.force_index $base.force_index "$p force changed"}}
function Assert-FixtureForce($v,[string]$p){Assert-PropertyNames $v @('current_research','research_progress','research_queue','technologies')$p;Assert-Equal $v.current_research 'mir-browser-personal-infinite'"$p current research";Assert-True(($v.research_progress -is [double]) -and [double]::IsFinite([double]$v.research_progress) -and [Math]::Abs(([double]$v.research_progress)-0.42) -le 1e-15) "$p research progress differs";Assert-True($v.research_queue -is [array])"$p queue is not an array";Assert-Equal $v.research_queue.Count 1 "$p queue count";Assert-Equal $v.research_queue[0] 'mir-browser-personal-infinite'"$p queue technology";Assert-PropertyNames $v.technologies @('mir-browser-personal-finite','mir-browser-personal-infinite')"$p technologies";foreach($n in @('mir-browser-personal-finite','mir-browser-personal-infinite')){Assert-PropertyNames $v.technologies.PSObject.Properties[$n].Value @('enabled','level','researched','saved_progress','visible_when_disabled')"$p technologies.$n"}}
function ConvertTo-CanonicalJson($v){if($null -eq $v){return 'null'};if($v -is [string]){return($v|ConvertTo-Json -Compress)};if($v -is [bool]){return $(if($v){'true'}else{'false'})};if($v -is [byte] -or $v -is [int16] -or $v -is [int] -or $v -is [int64] -or $v -is [single] -or $v -is [double] -or $v -is [decimal]){return [Convert]::ToString($v,[Globalization.CultureInfo]::InvariantCulture)};if($v -is [Collections.IEnumerable]){$x=foreach($i in $v){ConvertTo-CanonicalJson $i};return '['+($x -join ',')+']'};$p=@($v.PSObject.Properties);if($p.Count -gt 0){$x=foreach($q in @($p|Sort-Object Name)){(($q.Name|ConvertTo-Json -Compress)+':'+(ConvertTo-CanonicalJson $q.Value))};return '{'+($x -join ',')+'}'};Fail "cannot canonically encode type $($v.GetType().FullName)"}
function Assert-CommonResult($r,[string]$stage,[string[]]$extra,[string]$invariant,$a,$b,$views){$n=@('fixture_force','fixture_technology_names','player_a','player_b','same_force','schema','stage',$invariant)+$extra;Assert-PropertyNames $r $n "result $stage";Assert-Equal $r.schema 1 "result $stage schema";Assert-Equal $r.stage $stage 'result stage';Assert-FixtureNames $r.fixture_technology_names "result $stage fixture names";Assert-Equal $r.same_force $true "result $stage same force";Assert-Equal $r.PSObject.Properties[$invariant].Value $true "result $stage fixture force/queue invariant";Assert-FixtureForce $r.fixture_force "result $stage fixture force";if($views){Assert-View $r.player_a "result $stage player A" 1 $false 'mir-browser.show' $a;Assert-View $r.player_b "result $stage player B" 3 $true 'mir-browser.hide' $b}}
function Assert-InitialResult($r){Assert-CommonResult $r 'initial' @('active_full_force_snapshot_unchanged','hidden_recovery','invalid_hidden_page_preservation','malformed_hidden','valid_replacement_show_roundtrip') 'fixture_owned_force_queue_unchanged' $null $null $true;Assert-Equal $r.active_full_force_snapshot_unchanged $true 'initial full active-force snapshot invariant';Assert-Equal $r.valid_replacement_show_roundtrip $true 'initial valid replacement/show roundtrip';Assert-PropertyNames $r.malformed_hidden @('duplicate_rejected_without_mutation','sparse_rejected_without_mutation','unknown_rejected_without_mutation') 'initial malformed hidden';foreach($n in $r.malformed_hidden.PSObject.Properties.Name){Assert-Equal $r.malformed_hidden.PSObject.Properties[$n].Value $true "initial malformed hidden $n"};Assert-PropertyNames $r.invalid_hidden_page_preservation @('invalid_page_preserved_page_rows','page_one_rows_differ','requested_page','sparse_hidden_preserved_page_rows') 'initial invalid hidden page preservation';Assert-Equal $r.invalid_hidden_page_preservation.requested_page 2 'initial requested page';foreach($n in @('page_one_rows_differ','sparse_hidden_preserved_page_rows','invalid_page_preserved_page_rows')){Assert-Equal $r.invalid_hidden_page_preservation.$n $true "initial page preservation $n"};Assert-PropertyNames $r.hidden_recovery @('direct_row_present_after_clear','direct_row_present_while_hidden','hidden_technology','hidden_technology_is_queued','recovery_action_present_after_navigation','recovery_caption_key','selected_technology') 'initial hidden recovery';Assert-Equal $r.hidden_recovery.hidden_technology 'mir-browser-personal-finite' 'initial recovery hidden technology';Assert-Equal $r.hidden_recovery.selected_technology 'mir-browser-personal-infinite' 'initial recovery selected technology';Assert-Equal $r.hidden_recovery.hidden_technology_is_queued $false 'initial recovery queue boundary';Assert-Equal $r.hidden_recovery.direct_row_present_while_hidden $false 'initial recovery hidden row';Assert-Equal $r.hidden_recovery.recovery_action_present_after_navigation $true 'initial recovery action';Assert-Equal $r.hidden_recovery.recovery_caption_key 'mir-browser.show-hidden' 'initial recovery caption';Assert-Equal $r.hidden_recovery.direct_row_present_after_clear $true 'initial recovery cleared row';Assert-True($r.player_a.index -ne $r.player_b.index) 'players share an index';Assert-True($r.player_a.username -cne $r.player_b.username) 'client identities are not distinct';Assert-Equal $r.player_a.force_index $r.player_b.force_index 'players do not share a force';return [pscustomobject]@{a=$r.player_a;b=$r.player_b;fixture_force_canonical=ConvertTo-CanonicalJson $r.fixture_force}}
function Assert-PersistentResult($r,[string]$stage,$base){Assert-CommonResult $r $stage @('active_full_force_snapshot_unchanged')'fixture_owned_force_queue_unchanged' $base.a $base.b $true;Assert-Equal $r.active_full_force_snapshot_unchanged $true "$stage full active-force snapshot invariant";Assert-Equal(ConvertTo-CanonicalJson $r.fixture_force)$base.fixture_force_canonical "$stage fixture force changed"}
function Assert-RemovalResult($r,$base){Assert-CommonResult $r 'removal' @('browser_interface_present','personal_state_readability','removal_disposition') 'fixture_owned_force_queue_unchanged_during_removal' $null $null $false;Assert-Equal $r.browser_interface_present $false 'removal browser interface disposition';Assert-Equal $r.personal_state_readability 'unavailable-removed-owner-no-interface' 'removal readability disposition';Assert-Equal $r.removal_disposition 'before-after-recorded-no-arbitrary-rollback-claim' 'removal rollback disposition';foreach($role in @('a','b')){$view=$r.PSObject.Properties["player_$role"].Value;$baselineView=$base.PSObject.Properties[$role].Value;Assert-PropertyNames $view @('force_index','frame_still_present','index','username') "removal player $role";Assert-Equal $view.index $baselineView.index "removal player $role index";Assert-Equal $view.username $baselineView.username "removal player $role username";Assert-Equal $view.force_index $baselineView.force_index "removal player $role force";Assert-True($view.frame_still_present -is [bool]) "removal player $role frame disposition is not boolean"};Assert-Equal(ConvertTo-CanonicalJson $r.fixture_force) $base.fixture_force_canonical 'removal canonical fixture force differs from initial'}
function Assert-ReaddResult($r,$base){Assert-CommonResult $r 'readd' @('browser_interface_present','personal_state_disposition') 'fixture_owned_force_queue_unchanged_during_removal' $null $null $false;Assert-Equal $r.browser_interface_present $true 'readd browser interface disposition';Assert-Equal $r.personal_state_disposition 'observed-after-owner-readd-not-arbitrary-rollback-claim' 'readd rollback disposition';Assert-View $r.player_a 'readd player A' $null $null $null $base.a;Assert-View $r.player_b 'readd player B' $null $null $null $base.b;Assert-True(@('mir-browser.show','mir-browser.hide') -contains $r.player_a.toggle_caption_key) 'readd player A toggle key is not an observed F210 key';Assert-True(@('mir-browser.show','mir-browser.hide') -contains $r.player_b.toggle_caption_key) 'readd player B toggle key is not an observed F210 key';Assert-Equal(ConvertTo-CanonicalJson $r.fixture_force) $base.fixture_force_canonical 'readd canonical fixture force differs from initial'}
function Get-RepositorySnapshot([string]$r){return [ordered]@{commit=(& git -C $r rev-parse HEAD).Trim();tree=(& git -C $r rev-parse 'HEAD^{tree}').Trim();status_porcelain=@(& git -C $r status --porcelain=v1)}}
function Assert-Dossier($Dossier) {
  Assert-PropertyNames $Dossier @('boundaries', 'explicit_non_claims', 'fixture_technologies', 'gui_structure', 'player_outcome', 'results', 'schema', 'scope', 'target') 'dossier'
  Assert-Equal $Dossier.schema 1 'dossier schema'
  Assert-Equal $Dossier.scope 'F210 Factorio 2.1.17 localhost two-client browser personal-state continuity; package-excluded evidence' 'dossier scope'
  Assert-PropertyNames $Dossier.target @('engine_sha256', 'factorio_line', 'factorio_version', 'network_scope') 'dossier target'
  Assert-Equal $Dossier.target.factorio_line '2.1' 'dossier Factorio line'
  Assert-Equal $Dossier.target.factorio_version $ExpectedEngineVersion 'dossier Factorio version'
  Assert-Equal $Dossier.target.engine_sha256 $ExpectedEngineSha256 'dossier engine hash'
  Assert-Equal $Dossier.target.network_scope 'two exact localhost client processes connected to one loopback dedicated server' 'dossier network scope'
  Assert-FixtureNames $Dossier.fixture_technologies 'dossier fixture technologies'
  Assert-PropertyNames $Dossier.gui_structure @('frame_name', 'hidden_recovery', 'main_row', 'mode', 'result_body', 'toggle') 'dossier GUI structure'
  Assert-Equal $Dossier.gui_structure.frame_name $BrowserRoot 'dossier GUI root'
  Assert-Equal $Dossier.gui_structure.result_body 'unnamed untagged direct scroll-pane child of mir_research_browser; only its direct select-tagged children are result rows' 'dossier result body binding'
  Assert-Equal $Dossier.gui_structure.main_row 'tags.mir_browser=select and tags.technology=<technology> on a direct body child' 'dossier main row binding'
  Assert-Equal $Dossier.gui_structure.mode 'tags.mir_browser=mode on native drop-down' 'dossier mode binding'
  Assert-Equal $Dossier.gui_structure.toggle 'tags.mir_browser=toggle-hide and exact one-key LocalisedString caption' 'dossier toggle binding'
  Assert-Equal $Dossier.gui_structure.hidden_recovery 'mir_browser_section=hidden-recovery nested flow with mir_browser=show-hidden exact one-key LocalisedString action; constant-size clear-all recovery does not enumerate hidden rows' 'dossier hidden recovery binding'
  Assert-PropertyNames $Dossier.player_outcome @('hidden_recovery', 'player_a', 'player_b', 'queue', 'same_force') 'dossier player outcome'
  Assert-Equal $Dossier.player_outcome.same_force $true 'dossier same force'
  Assert-PropertyNames $Dossier.player_outcome.player_a @('hidden', 'main_row_present', 'mode_selected_index', 'toggle_caption_key') 'dossier player A outcome'
  Assert-PropertyNames $Dossier.player_outcome.player_b @('hidden', 'main_row_present', 'mode_selected_index', 'toggle_caption_key') 'dossier player B outcome'
  Assert-Equal $Dossier.player_outcome.player_a.mode_selected_index 1 'dossier player A mode'
  Assert-Equal $Dossier.player_outcome.player_a.main_row_present $false 'dossier player A row'
  Assert-Equal $Dossier.player_outcome.player_a.toggle_caption_key 'mir-browser.show' 'dossier player A key'
  Assert-Equal ($Dossier.player_outcome.player_a.hidden -join "`n") 'mir-browser-personal-infinite' 'dossier player A hidden'
  Assert-Equal $Dossier.player_outcome.player_b.mode_selected_index 3 'dossier player B mode'
  Assert-Equal $Dossier.player_outcome.player_b.main_row_present $true 'dossier player B row'
  Assert-Equal $Dossier.player_outcome.player_b.toggle_caption_key 'mir-browser.hide' 'dossier player B key'
  Assert-Equal @($Dossier.player_outcome.player_b.hidden).Count 0 'dossier player B hidden'
  Assert-PropertyNames $Dossier.player_outcome.hidden_recovery @('direct_row_present_after_clear', 'direct_row_present_while_hidden', 'hidden_technology', 'hidden_technology_is_queued', 'recovery_action_present_after_navigation', 'recovery_caption_key', 'selected_technology') 'dossier hidden recovery outcome'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.hidden_technology 'mir-browser-personal-finite' 'dossier recovery hidden technology'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.selected_technology 'mir-browser-personal-infinite' 'dossier recovery selected technology'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.hidden_technology_is_queued $false 'dossier recovery queue boundary'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.direct_row_present_while_hidden $false 'dossier recovery hidden row'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.recovery_action_present_after_navigation $true 'dossier recovery action'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.recovery_caption_key 'mir-browser.show-hidden' 'dossier recovery caption'
  Assert-Equal $Dossier.player_outcome.hidden_recovery.direct_row_present_after_clear $true 'dossier recovery cleared row'
  Assert-Equal $Dossier.player_outcome.queue 'The hidden technology remains queued on the shared force.' 'dossier queue meaning'
  Assert-PropertyNames $Dossier.boundaries @('active_force_snapshot', 'configuration_change', 'hidden_recovery', 'mod_readd', 'mod_removal', 'save_reload') 'dossier boundaries'
  Assert-Equal $Dossier.boundaries.hidden_recovery 'The native browser exposes one constant-size clear-all recovery action after navigating away from an unqueued hidden technology; structural/action-state evidence is observed without claiming physical mouse-click synthesis.' 'dossier hidden recovery boundary'
  Assert-Equal $Dossier.boundaries.save_reload 'The saved per-player views and the full active force snapshot are re-observed after a real server save/reload and two reconnects.' 'dossier save/reload boundary'
  Assert-Equal $Dossier.boundaries.configuration_change 'Adding one exact inert local configuration marker triggers Factorio configuration change; the saved per-player views and full active force snapshot are re-observed.' 'dossier configuration boundary'
  Assert-Equal $Dossier.boundaries.mod_removal 'Literal MIR removal records owner interface, GUI presence and fixture-owned force/queue before/after disposition; it never claims that removed-mod GUI/storage is readable or rollback-capable.' 'dossier removal boundary'
  Assert-Equal $Dossier.boundaries.mod_readd 'MIR re-addition opens a selected fixture technology and records observed native presentation only; it does not assert arbitrary restoration of removed-owner personal state.' 'dossier readd boundary'
  Assert-Equal $Dossier.boundaries.active_force_snapshot 'All active force technologies exactly compare enabled, researched, level, visible_when_disabled and saved_progress, plus current research, progress and queue while MIR is active; literal MIR removal/re-add compares only fixture-owned technology/current/progress/queue facts because MIR-owned prototypes legitimately change.' 'dossier force boundary'
  Assert-PropertyNames $Dossier.results @('active_full_force_snapshot_unchanged', 'fixture_owned_force_queue_unchanged', 'fixture_owned_force_queue_unchanged_during_removal', 'hidden_recovery', 'invalid_hidden_page_preservation', 'personal_state_disposition', 'personal_state_readability', 'removal_disposition') 'dossier results'
  Assert-Equal $Dossier.results.hidden_recovery 'The unqueued hidden fixture technology is absent under its exact search while hidden, the bounded native recovery action is present after selecting another technology, and its direct row returns after a valid state clear.' 'dossier hidden recovery result meaning'
  Assert-Equal $Dossier.results.invalid_hidden_page_preservation 'An invalid sparse hidden payload and invalid page zero leave exact page-two direct result rows unchanged.' 'dossier invalid hidden/page result meaning'
  Assert-Equal $Dossier.results.active_full_force_snapshot_unchanged 'True only for initial, save-reload and inert configuration-change phases after exact all-technology comparison.' 'dossier active result meaning'
  Assert-Equal $Dossier.results.fixture_owned_force_queue_unchanged 'True only for MIR-active phases after exact fixture-owned technology/current/progress/queue comparison.' 'dossier active fixture result meaning'
  Assert-Equal $Dossier.results.fixture_owned_force_queue_unchanged_during_removal 'True only for literal MIR-removal and re-add phases after exact fixture-owned comparison; it is not a full active force snapshot claim.' 'dossier removal fixture result meaning'
  Assert-Equal $Dossier.results.personal_state_readability 'unavailable-removed-owner-no-interface' 'dossier readability result meaning'
  Assert-Equal $Dossier.results.removal_disposition 'before-after-recorded-no-arbitrary-rollback-claim' 'dossier removal result meaning'
  Assert-Equal $Dossier.results.personal_state_disposition 'observed-after-owner-readd-not-arbitrary-rollback-claim' 'dossier readd result meaning'
  $nonClaims = @('F200', 'Angel-or-combined-Bob-Angel-route-coverage', 'remote-wide-network-behavior-beyond-observed-two-local-clients', 'native-vanilla-technology-tree-mutation-or-injection', 'queue-ownership-or-reorder', 'physical-mouse-click-synthesis', 'full-PLAT-UI-01-A16-or-X11-closure', 'release-readiness')
  Assert-Equal (@($Dossier.explicit_non_claims) -join "`n") ($nonClaims -join "`n") 'dossier explicit nonclaims'
}
function Invoke-CreateSave([string]$save,[string]$config,[string]$mods){$i=Start-Owned 'create' 'save-create' 3 @('--create',$save,'--config',$config,'--mod-directory',$mods,'--console-log',(Join-Path $RunRoot 'create-current.log'),'--no-log-rotation','--disable-audio');$end=[DateTime]::UtcNow.AddSeconds($TimeoutSeconds);while(-not $i.process.HasExited -and [DateTime]::UtcNow -lt $end){Start-Sleep -Milliseconds 250};if(-not $i.process.HasExited){$i.process.Kill($true);$i.process.WaitForExit(15000)|Out-Null;Fail 'save creation timed out'};$i.exit_code=$i.process.ExitCode;$i.exit_disposition='completed';$i.process.Dispose();$i.disposed=$true;Assert-Equal $i.exit_code 0 'initial save creation exit code';Assert-True(Test-Path -LiteralPath $save -PathType Leaf)'initial save was not created'}
function Invoke-ProofStage([string]$stage,[string]$save,[string]$result,$next,[int]$port,[string]$sc,[string]$ac,[string]$bc,[string]$mods,[string]$serverData,[string]$clientAData,[string]$clientBData){$d=Join-Path $RunRoot(Join-Path 'stages' $stage);[IO.Directory]::CreateDirectory($d)|Out-Null;Write-Json(Join-Path $d 'server-settings.json')([ordered]@{name="MIR browser personal-state $stage";description='';tags=@();max_players=2;visibility=[ordered]@{public=$false;lan=$false};username='';password='';token='';game_password='';require_user_verification=$false;max_upload_in_kilobytes_per_second=0;max_upload_slots=5;minimum_latency_in_ticks=0;ignore_player_limit_for_returning_players=$false;allow_commands='admins-only';autosave_interval=0;autosave_slots=1;afk_autokick_interval=0;auto_pause=$false;only_admins_can_pause_the_game=$false});$rp=Join-Path $serverData(Join-Path 'script-output'(Join-Path 'browser-personal-state'"$result.json"));if(Test-Path -LiteralPath $rp -PathType Leaf){Remove-Item -LiteralPath $rp -Force};if($null -ne $next -and(Test-Path -LiteralPath $next -PathType Leaf)){Remove-Item -LiteralPath $next -Force};$x=Start-Stage $stage $save $port $sc $ac $bc $mods $serverData $clientAData $clientBData $d;$i=@($x.client_a,$x.client_b,$x.server);$r=Wait-Result $rp $i;$o=(Get-LogText $x.server_log).Length;if($null -ne $next){Wait-SuccessorSave $next $x.server_log $o $i};Stop-Owned $stage;$copy=Join-Path $d "server-$stage.log";Copy-Item -LiteralPath $x.server_log -Destination $copy -Force;return [pscustomobject]@{stage=$stage;result=$r;result_sha256=Get-Sha256 $rp;fixture_force_canonical=ConvertTo-CanonicalJson $r.fixture_force;server_log=$copy;server_log_sha256=Get-Sha256 $copy;client_a_log_sha256=Get-Sha256 $x.client_a_log;client_b_log_sha256=Get-Sha256 $x.client_b_log;input_save=$save;input_save_sha256=Get-Sha256 $save;successor_save=$next;successor_save_sha256=if($null -eq $next){$null}else{Get-Sha256 $next}}}
$RepositoryRoot=(Resolve-Path -LiteralPath $RepositoryRoot).Path;$CandidateArchive=(Resolve-Path -LiteralPath $CandidateArchive).Path;$prefix=$RepositoryRoot.TrimEnd('\')+'\';$hostPath=(Resolve-Path -LiteralPath(Join-Path $RepositoryRoot 'src/mod/families/modern/prototypes/mir/runtime/research_browser.lua')).Path;$locale=(Resolve-Path -LiteralPath(Join-Path $RepositoryRoot 'src/mod/families/modern/locale/en/more-infinite-research.cfg')).Path;$dossierPath=(Resolve-Path -LiteralPath(Join-Path $RepositoryRoot 'fixtures/assert-browser-personal-state-continuity/personal-state-continuity-dossier.json')).Path;$readmePath=(Resolve-Path -LiteralPath(Join-Path $RepositoryRoot 'targets/f210/generation/README.md.template')).Path
foreach($p in @($hostPath,$locale,$dossierPath,$readmePath)){Assert-True $p.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase)"source path escapes repository: $p"};Assert-True(Test-Path -LiteralPath $FactorioExe -PathType Leaf)"Factorio executable is absent: $FactorioExe";Assert-Equal(Get-Sha256 $FactorioExe)$ExpectedEngineSha256 'Factorio engine executable SHA-256';Assert-True((& $FactorioExe --version 2>&1|Out-String).Contains($ExpectedEngineVersion))"Factorio version output does not contain $ExpectedEngineVersion";$snapshot=Get-RepositorySnapshot $RepositoryRoot;$candidate=Test-Candidate $CandidateArchive $hostPath $locale $readmePath;$dossier=Get-Content -LiteralPath $dossierPath -Raw|ConvertFrom-Json;Assert-Dossier $dossier
$runId=[guid]::NewGuid().ToString('N');$RunRoot=Join-Path $RepositoryRoot(Join-Path 'build/tests/browser-personal-state-continuity' $runId);$mods=Join-Path $RunRoot 'mods';$sd=Join-Path $RunRoot 'server-userdata';$ad=Join-Path $RunRoot 'client-a-userdata';$bd=Join-Path $RunRoot 'client-b-userdata';foreach($p in @($mods,$sd,$ad,$bd)){[IO.Directory]::CreateDirectory($p)|Out-Null};$fs=Join-Path $RepositoryRoot 'fixtures/assert-browser-personal-state-continuity';$ms=Join-Path $fs 'configuration-marker';$control=Join-Path $fs 'control.lua';$ct=[IO.File]::ReadAllText($control);foreach($s in @('local session_complete=false','if session_complete then return end','helpers.write_file(','force.research_queue={infinite}','recovery_action_present_after_navigation=true','invalid_page_preserved_page_rows=true','s.phase=next_phase; game.auto_save(save_name); session_complete=true')){Assert-True $ct.Contains($s)"fixture control source sentinel missing: $s"}
$fa=New-FixtureArchive $fs $FixtureName $FixtureVersion(Join-Path $RunRoot 'fixture-archive')@('info.json','data.lua','control.lua');$ma=New-FixtureArchive $ms $MarkerName $MarkerVersion(Join-Path $RunRoot 'marker-archive')@('info.json','control.lua');$cc=Join-Path $mods(Split-Path -Leaf $CandidateArchive);Copy-Item -LiteralPath $CandidateArchive -Destination $cc -Force;Copy-Item -LiteralPath $fa -Destination $mods -Force;$sc=Join-Path $RunRoot 'server-config.ini';$ac=Join-Path $RunRoot 'client-a-config.ini';$bc=Join-Path $RunRoot 'client-b-config.ini';New-FactorioConfig $sc $sd;New-FactorioConfig $ac $ad;New-FactorioConfig $bc $bd;Write-PlayerData $ad $PlayerAIdentity;Write-PlayerData $bd $PlayerBIdentity;$apd=Get-Content -LiteralPath(Join-Path $ad 'player-data.json') -Raw|ConvertFrom-Json;$bpd=Get-Content -LiteralPath(Join-Path $bd 'player-data.json') -Raw|ConvertFrom-Json;Assert-PropertyNames $apd @('service-token','service-username') 'client A player-data';Assert-PropertyNames $bpd @('service-token','service-username') 'client B player-data';Assert-Equal $apd.'service-username' $PlayerAIdentity 'client A service username';Assert-Equal $bpd.'service-username' $PlayerBIdentity 'client B service username';Assert-Equal $apd.'service-token' '' 'client A service token is not empty';Assert-Equal $bpd.'service-token' '' 'client B service token is not empty';$port=New-FreeLoopbackPort
$i=Join-Path $sd 'saves/initial.zip';$r=Join-Path $sd 'saves/_autosave-mir-browser-personal-state-continuity.zip';$c=Join-Path $sd 'saves/_autosave-mir-browser-personal-state-continuity-configuration.zip';$m=Join-Path $sd 'saves/_autosave-mir-browser-personal-state-continuity-removal.zip';$re=Join-Path $sd 'saves/_autosave-mir-browser-personal-state-continuity-readd.zip';$st=[Collections.Generic.List[object]]::new()
try{Write-ModList $mods @('more-infinite-research',$FixtureName);Invoke-CreateSave $i $sc $mods;$x=Invoke-ProofStage 'initial' $i 'initial' $r $port $sc $ac $bc $mods $sd $ad $bd;$base=Assert-InitialResult $x.result;Assert-Equal((@($base.a.username,$base.b.username)|Sort-Object)-join "`n")((@($PlayerAIdentity,$PlayerBIdentity)|Sort-Object)-join "`n") 'observed service usernames differ from exact configured identities';$st.Add($x)|Out-Null;$x=Invoke-ProofStage 'save-reload' $r 'save-reload' $c $port $sc $ac $bc $mods $sd $ad $bd;Assert-PersistentResult $x.result 'save-reload' $base;$st.Add($x)|Out-Null
Copy-Item -LiteralPath $ma -Destination $mods -Force;Write-ModList $mods @('more-infinite-research',$FixtureName,$MarkerName);$x=Invoke-ProofStage 'configuration-change' $c 'configuration-change' $m $port $sc $ac $bc $mods $sd $ad $bd;Assert-PersistentResult $x.result 'configuration-change' $base;$st.Add($x)|Out-Null;$mp=(Resolve-Path -LiteralPath $mods).Path.TrimEnd('\')+'\';$rc=(Resolve-Path -LiteralPath $cc).Path;Assert-True $rc.StartsWith($mp,[StringComparison]::OrdinalIgnoreCase)'candidate removal target escapes harness mods directory';Remove-Item -LiteralPath $rc -Force;Write-ModList $mods @($FixtureName,$MarkerName)
$x=Invoke-ProofStage 'removal' $m 'removal' $re $port $sc $ac $bc $mods $sd $ad $bd;Assert-RemovalResult $x.result $base;$st.Add($x)|Out-Null;Copy-Item -LiteralPath $CandidateArchive -Destination $cc -Force;Write-ModList $mods @('more-infinite-research',$FixtureName,$MarkerName);$x=Invoke-ProofStage 'readd' $re 'readd' $null $port $sc $ac $bc $mods $sd $ad $bd;Assert-ReaddResult $x.result $base;$st.Add($x)|Out-Null}finally{Stop-AllOwned}
$receipt=[ordered]@{schema=1;status='passed';execution_id=$runId;scope=$dossier.scope;engine=[ordered]@{version=$ExpectedEngineVersion;exe_sha256=Get-Sha256 $FactorioExe};source=[ordered]@{commit=$snapshot.commit;tree=$snapshot.tree;status_porcelain=$snapshot.status_porcelain;browser_host_sha256=Get-Sha256 $hostPath;en_locale_sha256=Get-Sha256 $locale;dossier_sha256=Get-Sha256 $dossierPath;harness_sha256=Get-Sha256 $PSCommandPath;f210_readme_template_sha256=Get-Sha256 $readmePath};candidate=$candidate;loopback=[ordered]@{address='127.0.0.1';port=$port;server_require_user_verification=$false};configured_identities=@($PlayerAIdentity,$PlayerBIdentity);observed_identities=@($base.a.username,$base.b.username);fixture=[ordered]@{info_sha256=Get-Sha256(Join-Path $fs 'info.json');data_sha256=Get-Sha256(Join-Path $fs 'data.lua');control_sha256=Get-Sha256 $control;marker_info_sha256=Get-Sha256(Join-Path $ms 'info.json');marker_control_sha256=Get-Sha256(Join-Path $ms 'control.lua');archive_sha256=Get-Sha256 $fa;marker_archive_sha256=Get-Sha256 $ma};stages=@($st.ToArray());owned_processes=@($owned|ForEach-Object{[ordered]@{stage=$_.stage;role=$_.role;pid=$_.pid;exit_disposition=$_.exit_disposition;exit_code=$_.exit_code}});non_claims=$dossier.explicit_non_claims}
$receiptPath=Join-Path $RunRoot 'browser-personal-state-continuity-receipt.json';Write-Json $receiptPath $receipt;Write-Output "MIR_BROWSER_PERSONAL_STATE_CONTINUITY_RECEIPT=$receiptPath"
