local function fail(message)
  error("MIR exact-pack family authorization validation failed: " .. message)
end

local assembler = data.raw.technology and data.raw.technology["mir-auto-prod-manufacturing-assembling-machine-1"]
if not assembler then fail("authorized assembling-machine family was not generated") end
local assembler_recipe = false
for _, effect in ipairs(assembler.effects or {}) do
  if effect.type == "change-recipe-productivity" and effect.recipe == "assemble-theta" then assembler_recipe = true end
end
if not assembler_recipe then fail("authorized family output omitted assemble-theta") end

if data.raw.technology and data.raw.technology["mir-auto-prod-manufacturing-lab-1"] then
  fail("unrelated lab family was generated by an assembling-machine authorization")
end

local belt = data.raw.technology and data.raw.technology["recipe-prod-research_belts-1"]
local seeded = false
for _, effect in ipairs((belt and belt.effects) or {}) do
  if effect.type == "change-recipe-productivity" and effect.recipe == "pack-only-recipe" then seeded = true end
end
if not seeded then fail("exact pack candidate seed did not join the safe attachment baseline") end
