# MIR4-CANONICAL-EXECUTABLE-TEST
param([string]$RepoRoot='', [switch]$RequireLocalEvidence, [switch]$AllowActive)
$ErrorActionPreference='Stop'
if(-not$RepoRoot){$RepoRoot=(Resolve-Path(Join-Path $PSScriptRoot '../..')).Path}
$RepoRoot=(Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $RepoRoot 'tools/lib/mir4/BootstrapMaterialization.ps1')
. (Join-Path $RepoRoot 'tools/lib/validation/PackageIdentity.ps1')
. (Join-Path $RepoRoot 'tools/mir/application/assurance/EnvironmentEvidence.ps1')
function Assert-A03Closure{param([bool]$Condition,[string]$Code)if(-not$Condition){throw $Code}}
function Get-A03ClosureSha256{param([string]$Path)(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToUpperInvariant()}
function Resolve-A03ClosurePath{param([string]$RelativePath,[bool]$Required=$false)
  Assert-A03Closure($RelativePath-cmatch'^[A-Za-z0-9._/-]+$'-and$RelativePath-notmatch'(^|/)\.\.(/|$)')"[mir4-a03-closure-relative-path] $RelativePath"
  $path=[IO.Path]::GetFullPath((Join-Path $RepoRoot $RelativePath));$prefix=$RepoRoot.TrimEnd([IO.Path]::DirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar
  Assert-A03Closure($path.StartsWith($prefix,[StringComparison]::OrdinalIgnoreCase))"[mir4-a03-closure-path-escape] $RelativePath"
  if($Required){Assert-A03Closure(Test-Path -LiteralPath $path -PathType Leaf)"[mir4-a03-closure-evidence-missing] $RelativePath"};$path
}
function Get-A03ClosureRecord{param([string]$RelativePath,[string]$SchemaPath)
  $path=Resolve-A03ClosurePath $RelativePath $true;$raw=Get-Content -Raw -LiteralPath $path
  Assert-A03Closure($raw|Test-Json -SchemaFile(Join-Path $RepoRoot $SchemaPath))"[mir4-a03-closure-schema] $RelativePath"
  Assert-A03Closure($raw-notmatch'(?i)(?:[A-Z]:[\/]|\\\\)')"[mir4-a03-closure-private-path] $RelativePath"
  $record=$raw|ConvertFrom-Json -Depth 100 -DateKind String;Assert-A03Closure(Test-MIR4BootstrapRecordHash $record)"[mir4-a03-closure-self-hash] $RelativePath";$record
}
function Test-A03HistoricalLineageBindings{param($Dossier)
  try{
    $expected=@(
      [pscustomobject]@{entry=$Dossier.historical_lineage.old_admitted_campaign;field='path';path='spec/programmes/evidence/synthesis-2026-09-06/k2-campaign.json';raw='5D40070E402BFD69680701113281966EAB494FC0E56EB169814C9DE8462A3535'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.pre_engine_failure;field='evidence_path';path='build/results/assurance/evidence/runtime.k2-k2so-f210-intake/760351C4D90774252B768B36AF23EEEB4F3951290CAB6A396976D4F854982344/attempts/20260909T2323468666412Z-3f4e2431d05c48878df4fc6f7d96e52c.json';raw='076312E4D974FD8D2554BB4D7E26FE275F2830C98EAFB0C1755537F41ACE275D'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.superseded_pass;field='evidence_path';path='build/results/assurance/evidence/runtime.k2-k2so-f210-intake/E01A9E6E9CF1A7355F58F29953ED39DFD88B5E78853E93640275AC90DD67570D/attempts/20260909T2331313585529Z-7b7e3832a71e426eb2b30fb778a0a26c.json';raw='A3280AFF8BE3087BFD0AC3E52BE9D67C911B92376D7910188E7CF745CB1F66C7'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.superseded_pass.repaired_projection;field='path';path='build/mir4/a03-k2-intake/runtime/u-c4ab5dd8d8a4/a03-k2-k2so-f210-intake-runtime-result.json';raw='F203EEC4F2BD2AFB326D0E5720D6684A0B77CCD8DC35E560421D0A74BBB2AF37';status='preserved-repaired-projection-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.superseded_pass.pre_selfhash_repair;field='path';path='build/mir4/a03-k2-intake/runtime/u-c4ab5dd8d8a4/a03-k2-k2so-f210-intake-runtime-result.pre-selfhash-repair.json';raw='321E226ED6B1B8BEE6A59F4E63C9C103781AB9D1C670A6DD8EEAF114F2A61670'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.prior_admitted_run.plan;field='path';path='build/results/assurance/a03-k2-k2so-f210-intake-verification-plan-final.json';raw='9A4E4ADD9FE0820117EDF5C51FB91883C35815D0B3292058D628312690625B97';status='preserved-prior-plan-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.prior_admitted_run.summary;field='path';path='build/results/assurance/a03-k2-k2so-f210-intake-verify-summary-final.json';raw='AA6772ADA54C0A2ACF538BD7202F57D2B95046638A9062AC46FA679C10A1EFD6';status='preserved-prior-summary-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.prior_admitted_run.attempt;field='path';path='build/results/assurance/evidence/runtime.k2-k2so-f210-intake/FAF85191FAD19B35C51B75283E41D375BF2B76EC75DCDE0A40B6F7D0258EE080/attempts/20260909T2343359275925Z-e3b351c924c84b629c6875411472358f.json';raw='8C5D823C51AB652F8EF82F077F63685ED6A97365C815802E8B6D98069351C460';status='preserved-prior-attempt-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.prior_admitted_run.runtime;field='path';path='build/mir4/a03-k2-intake/runtime/u-ccf28c38552d/a03-k2-k2so-f210-intake-runtime-result.json';raw='3DA19A13D6988382AE7EAD58CA4FE3F386635702587DA4264B1312642E90E6EC';status='preserved-prior-runtime-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.source_tree_correction_superseded_run.plan;field='path';path='build/results/assurance/a03-k2-k2so-f210-intake-verification-plan-current.json';raw='70F8F961160FCD6537E432215CA20114FF2A767B995DB16FFF115F3F0218C978';status='preserved-wrong-tree-plan-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.source_tree_correction_superseded_run.summary;field='path';path='build/results/assurance/a03-k2-k2so-f210-intake-verify-summary-current.json';raw='3CBBC4342FEB733091D3CA20A81F943CAA6412AA5FCC4206D9412EC36EA90EB0';status='preserved-wrong-tree-summary-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.source_tree_correction_superseded_run.attempt;field='path';path='build/results/assurance/evidence/runtime.k2-k2so-f210-intake/8413557C3260D543319F6E15C672C7B17BA2B00DFC0A4A4FBCB38C65F18A816D/attempts/20260910T0313004731692Z-bf65d6df55134d31a1549c7032247890.json';raw='9AD0FA4BE576C07294BFDED1AE42D81923DDDDA9F99287ED579EDD118A4C732E';status='preserved-wrong-tree-attempt-not-current-proof'},
      [pscustomobject]@{entry=$Dossier.historical_lineage.source_tree_correction_superseded_run.runtime;field='path';path='build/mir4/a03-k2-intake/runtime/u-82322507f137/a03-k2-k2so-f210-intake-runtime-result.json';raw='AF3075AFC685F99721CB4F3B3F3294A62AF44D387D8A6397AF8B132068E81C21';status='preserved-wrong-tree-runtime-not-current-proof'}
    )
    foreach($row in $expected){$property=$row.entry.PSObject.Properties[$row.field];if($null-eq$row.entry-or$null-eq$property-or[string]$property.Value-cne[string]$row.path-or[string]$row.entry.raw_sha256-cne[string]$row.raw-or($row.PSObject.Properties['status']-and[string]$row.entry.status-cne[string]$row.status)){return $false}}
    return $true
  }catch{return $false}
}
function Test-A03CoreBindings{param($A00,$Lock,$Proof,$Dossier,$Receipt)
  try{
    if(-not(Test-A03HistoricalLineageBindings $Dossier)){return $false}
    $input=[string]$Proof.execution.plan.input_key
    if([string]$Proof.authority_observation.path-cne'spec/programmes/evidence/synthesis-2026-09-10/a00-current-authority-observation.json'-or[string]$Proof.environment_lock.path-cne'spec/programmes/evidence/synthesis-2026-09-10/a03-k2-k2so-f210-current.lock.json'-or[string]$Dossier.authority_observation.path-cne[string]$Proof.authority_observation.path-or[string]$Dossier.environment_lock.path-cne[string]$Proof.environment_lock.path-or[string]$Dossier.execution_proof.path-cne'spec/programmes/evidence/synthesis-2026-09-10/a03-k2-k2so-f210-execution-proof.json'-or[string]$Receipt.authority_observation.path-cne[string]$Proof.authority_observation.path-or[string]$Receipt.environment_lock.path-cne[string]$Proof.environment_lock.path-or[string]$Receipt.execution_proof.path-cne[string]$Dossier.execution_proof.path-or[string]$Receipt.dossier.path-cne'spec/programmes/evidence/synthesis-2026-09-10/a03-k2-k2so-f210-intake-dossier.json'){return $false}
    if([string]$Proof.authority_observation.record_sha256-cne[string]$A00.record_sha256-or[string]$Proof.environment_lock.digest-cne[string]$Lock.digest){return $false}
    if([string]$Proof.candidate.archive_sha256-cne[string]$A00.current_candidate.sha256-or[string]$Proof.candidate.archive_sha256-cne'99C020CBA2800179FF2D76EE35F58B27A97CF2A7D89993CFFE06403DC140090E'-or[string]$Proof.candidate.content_sha256-cne'2C6829889A140B95BF999D013ADE6A0B651A71FFCE2A52489D2C815ABE872735'-or[long]$Proof.candidate.bytes-ne1103729-or[int]$Proof.candidate.entries-ne337-or[string]$Proof.candidate.source_commit-cne[string]$A00.base.origin_dev-or[string]$Proof.candidate.source_commit-cne[string]$Lock.mir.source_commit-or[string]$Proof.candidate.source_tree-cne[string]$A00.base.tree-or[string]$Proof.candidate.source_tree-cne[string]$Lock.mir.source_tree){return $false}
    if([string]$Proof.engine.version-cne[string]$Lock.engine.version-or[string]$Proof.engine.executable_sha256-cne([string]$Lock.engine.executable_sha256).Substring(7).ToUpperInvariant()){return $false}
    if([string]$Proof.execution.summary.input_key-cne$input-or[string]$Proof.execution.attempt.input_key-cne$input-or[string]$Proof.execution.runtime.record_sha256-cnotmatch'^[A-F0-9]{64}$'){return $false}
    if([string]$Proof.execution.attempt.stdout_sha256-cne[string]$Proof.execution.attempt.executor_stdout.sha256-or[string]$Proof.execution.attempt.stderr_sha256-cne[string]$Proof.execution.attempt.executor_stderr.sha256){return $false}
    if([string]$Proof.observation.canonical_sha256-cne(Get-MIR4Sha256String(ConvertTo-MIR4BootstrapCanonicalJson $Proof.observation.value))){return $false}
    $expectedMods=@('base','elevated-rails','quality','recycler','space-age','flib','k2so-assets','Krastorio2','Krastorio2-spaced-out','Krastorio2Assets','Krastorio2MenuSimulations','mir-validation-settings-overrides','more-infinite-research','xy-k2so-enhancements-nulls-fork','mir4-a03-k2-intake-observer')|Sort-Object -CaseSensitive
    $actualMods=@($Proof.configuration.enabled_mods|ForEach-Object{[string]$_})|Sort-Object -CaseSensitive
    if($actualMods.Count-ne15-or@($actualMods|Sort-Object -CaseSensitive -Unique).Count-ne15-or($actualMods-join'|')-cne($expectedMods-join'|')-or@($Proof.closure_files).Count-ne12){return $false}
    $expectedClosureNames=@('Krastorio2-spaced-out_2.0.13.zip','Krastorio2Assets_2.1.0.zip','Krastorio2MenuSimulations_2.1.0.zip','Krastorio2_2.1.2.zip','flib_0.17.2.zip','k2so-assets_1.0.7.zip','mir-validation-settings-overrides_0.1.0.zip','mir4-a03-k2-intake-observer_0.1.0.zip','mod-list.json','mod-settings.dat','more-infinite-research_4.2.21000.zip','xy-k2so-enhancements-nulls-fork_0.8.3.zip')|Sort-Object -CaseSensitive
    if((@($Proof.closure_files.name)-join'|')-cne($expectedClosureNames-join'|')){return $false}
    foreach($mod in @($Lock.mods)){$name="$($mod.name)_$($mod.version).zip";$row=@($Proof.closure_files|Where-Object name -CEQ $name);if($row.Count-ne1-or[string]$row[0].sha256-cne([string]$mod.sha256).Substring(7).ToUpperInvariant()){return $false}}
    if([string](@($Proof.closure_files|Where-Object name -CEQ 'more-infinite-research_4.2.21000.zip'))[0].sha256-cne[string]$Proof.candidate.archive_sha256-or[string](@($Proof.closure_files|Where-Object name -CEQ 'mod-list.json'))[0].sha256-cne[string]$Proof.configuration.launch_mod_list.sha256-or[string](@($Proof.closure_files|Where-Object name -CEQ 'mod-settings.dat'))[0].sha256-cne[string]$Proof.configuration.post_engine_mod_settings.sha256){return $false}
    if([string]$Proof.configuration.source_mod_list.sha256-cne'FC7D944550AE7C4DEABAC91EF20CD2CC8E1ABFEDA0F96953284CDBFAB608FCAD'-or[string]$Proof.configuration.source_mod_settings.sha256-cne'6AF4D7F55D19D9F105BCD540FFCA61267613843BC7AFEB457241BFB3703977A4'){return $false}
    if([string]$Proof.configuration.settings_helper.archive_sha256-cne'0A6AAA9E8D89DDCC9E421F8AB065124554531588C4E4F91EC5E4D52EC0E10E26'-or[string]$Proof.configuration.settings_helper.source_sha256.info-cne'CDFBA732F66D8F2949B5AC9E957FE7996E32B6A8FF0D564C498A336FEF9A5ECD'-or[string]$Proof.configuration.settings_helper.source_sha256.settings_updates-cne'FAB0CB98489DC830DAA38A02E81F9BC3CD646B58BE18EEDB92F6EA5851AC246D'){return $false}
    if([string]$Proof.configuration.governed_observer.archive_sha256-cne'8031F2310B30E7B66A33EDD125AA86137B9ABA0B9DBFF1E23CD3C31435BE8D31'-or[string]$Proof.configuration.governed_observer.source_sha256.data_final_fixes-cne'2489A898D771B6C2991076E83F4C3F9376EE7FE2B2327654566DC0DAA3313B78'-or[string]$Proof.configuration.governed_observer.source_sha256.info-cne'74C59AB562F9249D9800EDACF71A71F5D62E04BB7BFE8E1B4B6DB532F0E8E4ED'){return $false}
    if([string]$Proof.execution.plan.digest_policy_ids.text-cne'utf8-nfc-lf-final-newline-v1'-or[string]$Proof.execution.plan.digest_policy_ids.json-cne'json-sorted-properties-utf8-nfc-lf-final-newline-v1'){return $false}
    if(@($Proof.invariants.PSObject.Properties|Where-Object{$_.Name-match'authorized$'-and[bool]$_.Value}).Count-ne0){return $false}
    if([string]$Dossier.authority_observation.record_sha256-cne[string]$A00.record_sha256-or(ConvertTo-MIR4BootstrapCanonicalJson $Dossier.environment_lock)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.environment_lock)-or[string]$Dossier.environment_lock.digest-cne[string]$Lock.digest-or[string]$Dossier.execution_proof.record_sha256-cne[string]$Proof.record_sha256){return $false}
    if((ConvertTo-MIR4BootstrapCanonicalJson $Dossier.runtime_result.file)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.execution.runtime.result_file)-or[string]$Dossier.runtime_result.record_sha256-cne[string]$Proof.execution.runtime.record_sha256-or(ConvertTo-MIR4BootstrapCanonicalJson $Dossier.runtime_result.factorio_log)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.execution.runtime.factorio_log)-or(ConvertTo-MIR4BootstrapCanonicalJson $Dossier.runtime_result.save)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.execution.runtime.save)-or[string]$Dossier.observation.canonical_sha256-cne[string]$Proof.observation.canonical_sha256-or(ConvertTo-MIR4BootstrapCanonicalJson $Dossier.observation.value)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.observation.value)){return $false}
    if([string]$Dossier.initial_observation_artifacts.observer_archive_sha256-cne'D8547266E67E5C9E3CA1B1CDCAF1830EF3DEB9A4E706776189663FE0F9478F8B'-or[string]$Dossier.initial_observation_artifacts.observer_source_sha256.data_final_fixes-cne'A67CCA976BFA5F6DD02447954C3D1587E8D19814BDEF64734216801A2EDB9E71'-or[string]$Dossier.initial_observation_artifacts.observer_source_sha256.info-cne'74C59AB562F9249D9800EDACF71A71F5D62E04BB7BFE8E1B4B6DB532F0E8E4ED'-or[string]$Dossier.governed_run_observer.archive_sha256-cne[string]$Proof.configuration.governed_observer.archive_sha256-or(ConvertTo-MIR4BootstrapCanonicalJson $Dossier.governed_run_observer.source_sha256)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.configuration.governed_observer.source_sha256)){return $false}
    if([string]$Receipt.authority_observation.record_sha256-cne[string]$A00.record_sha256-or[string]$Receipt.dossier.record_sha256-cne[string]$Dossier.record_sha256-or(ConvertTo-MIR4BootstrapCanonicalJson $Receipt.environment_lock)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.environment_lock)-or[string]$Receipt.environment_lock.digest-cne[string]$Lock.digest-or[string]$Receipt.execution_proof.record_sha256-cne[string]$Proof.record_sha256){return $false}
    if((ConvertTo-MIR4BootstrapCanonicalJson $Receipt.candidate_binding)-cne(ConvertTo-MIR4BootstrapCanonicalJson $Proof.candidate)-or[string]$Receipt.engine.version-cne[string]$Proof.engine.version-or[string]$Receipt.engine.executable_sha256-cne[string]$Proof.engine.executable_sha256){return $false}
    foreach($name in @('plan','summary','attempt')){if([string]$Receipt.execution.$name.path-cne[string]$Proof.execution.$name.path-or[string]$Receipt.execution.$name.raw_sha256-cne[string]$Proof.execution.$name.raw_sha256-or[string]$Receipt.execution.$name.input_key-cne$input){return $false}}
    if([string]$Receipt.execution.runtime.path-cne[string]$Proof.execution.runtime.result_file.path-or[string]$Receipt.execution.runtime.raw_sha256-cne[string]$Proof.execution.runtime.result_file.sha256-or[string]$Receipt.execution.runtime.record_sha256-cne[string]$Proof.execution.runtime.record_sha256-or[string]$Receipt.execution.runtime.input_key-cne$input){return $false}
    if([bool]$Receipt.release_authority-or[bool]$Receipt.public_support_authority){return $false};return $true
  }catch{return $false}
}
function Assert-A03Artifact{param($Artifact)
  $path=Resolve-A03ClosurePath([string]$Artifact.path)$true;Assert-A03Closure((Get-A03ClosureSha256 $path)-ceq[string]$Artifact.sha256-and[long](Get-Item -LiteralPath $path).Length-eq[long]$Artifact.bytes)"[mir4-a03-closure-artifact] $($Artifact.path)"
}
$root='spec/programmes/evidence/synthesis-2026-09-10';$a00Relative="$root/a00-current-authority-observation.json";$lockRelative="$root/a03-k2-k2so-f210-current.lock.json";$proofRelative="$root/a03-k2-k2so-f210-execution-proof.json";$dossierRelative="$root/a03-k2-k2so-f210-intake-dossier.json";$receiptRelative="$root/a03-k2-k2so-f210-intake-receipt.json"
$a00=Get-A03ClosureRecord $a00Relative 'spec/schemas/mir4-a00-current-authority-observation-v1.schema.json'
$lockPath=Resolve-A03ClosurePath $lockRelative $true;$lockRaw=Get-Content -Raw -LiteralPath $lockPath;Assert-A03Closure($lockRaw|Test-Json -SchemaFile(Join-Path $RepoRoot 'spec/schemas/preview/mir4-environment-lock-v1.schema.json'))'[mir4-a03-closure-lock-schema]';$lock=$lockRaw|ConvertFrom-Json -Depth 100 -DateKind String;Assert-A03Closure(Test-MIR4EnvironmentLockV1 $lock)'[mir4-a03-closure-lock]'
Assert-A03Closure([string]$lock.capture-ceq'engine-post-finalizer-exact'-and[string]$lock.digest-ceq'sha256:93f96b639310a3e6a10e721eaf7f4db7b3ec5f15ccb877dee1dc847dcb3baf1f'-and@($lock.mods).Count-eq9)'[mir4-a03-closure-lock-binding]'
$proof=Get-A03ClosureRecord $proofRelative 'spec/schemas/mir4-a03-k2-k2so-execution-proof-v1.schema.json';$dossier=Get-A03ClosureRecord $dossierRelative 'spec/schemas/mir4-a03-k2-k2so-intake-dossier-v1.schema.json';$receipt=Get-A03ClosureRecord $receiptRelative 'spec/schemas/mir4-a03-k2-k2so-intake-receipt-v1.schema.json'
Assert-A03Closure(Test-A03CoreBindings $a00 $lock $proof $dossier $receipt)'[mir4-a03-closure-cross-bindings]'
$expectedObservation=Get-Content -Raw -LiteralPath(Join-Path $RepoRoot 'fixtures/assert-k2-k2so-f210-intake/expected-observation.json')|ConvertFrom-Json -Depth 100 -DateKind String;Assert-A03Closure((ConvertTo-MIR4BootstrapCanonicalJson $proof.observation.value)-ceq(ConvertTo-MIR4BootstrapCanonicalJson $expectedObservation))'[mir4-a03-closure-exact-observation]'
Assert-A03Closure((@($dossier.explicit_non_claims)-join'|')-ceq'A04 science-phase behavior|progression qualification|upgrade or reload qualification|public compatibility support|release qualification')'[mir4-a03-closure-nonclaims]'
Assert-A03Closure([string]$dossier.historical_lineage.status-ceq'preserved-separate-not-current-proof'-and[string]$dossier.historical_lineage.old_admitted_campaign.status-ceq'preserved-old-admitted-campaign-not-current-proof'-and[string]$dossier.historical_lineage.pre_engine_failure.status-ceq'preserved-pre-engine-failure-not-gameplay-proof'-and[string]$dossier.historical_lineage.superseded_pass.status-ceq'superseded-by-final-runner-fingerprint-not-current-proof'-and[string]$dossier.historical_lineage.prior_admitted_run.status-ceq'superseded-by-current-lock-and-runner-fingerprint-not-current-proof'-and[string]$dossier.historical_lineage.source_tree_correction_superseded_run.status-ceq'superseded-by-corrected-source-tree-lock-not-current-proof'-and(Test-A03HistoricalLineageBindings $dossier))'[mir4-a03-closure-lineage]'
if($RequireLocalEvidence){
  Assert-A03Closure((Get-A03ClosureSha256 $lockPath)-ceq[string]$proof.environment_lock.raw_sha256)'[mir4-a03-closure-lock-raw]'
  foreach($artifact in @($proof.configuration.source_mod_list,$proof.configuration.launch_mod_list,$proof.configuration.source_mod_settings,$proof.configuration.post_engine_mod_settings,$proof.execution.attempt.structured_result,$proof.execution.attempt.executor_stdout,$proof.execution.attempt.executor_stderr,$proof.execution.runtime.result_file,$proof.execution.runtime.stdout,$proof.execution.runtime.stderr,$proof.execution.runtime.factorio_log,$proof.execution.runtime.save)){Assert-A03Artifact $artifact}
  foreach($name in @('plan','summary','attempt')){$binding=$proof.execution.$name;$path=Resolve-A03ClosurePath([string]$binding.path)$true;Assert-A03Closure((Get-A03ClosureSha256 $path)-ceq[string]$binding.raw_sha256)"[mir4-a03-closure-execution-raw] $name"}
  $runtimePath=Resolve-A03ClosurePath([string]$proof.execution.runtime.result_file.path)$true;$runtime=Get-Content -Raw -LiteralPath $runtimePath|ConvertFrom-Json -Depth 100 -DateKind String;Assert-A03Closure((Test-MIR4BootstrapRecordHash $runtime)-and([string]$runtime.record_sha256-ceq[string]$proof.execution.runtime.record_sha256))'[mir4-a03-closure-runtime-record]'
  $runtimeRoot=Split-Path -Parent $runtimePath;foreach($row in @($proof.closure_files)){$path=Join-Path(Join-Path $runtimeRoot 'mods')([string]$row.name);Assert-A03Closure((Test-Path -LiteralPath $path -PathType Leaf)-and((Get-A03ClosureSha256 $path)-ceq[string]$row.sha256))"[mir4-a03-closure-file] $($row.name)"}
  foreach($entry in @($dossier.historical_lineage.old_admitted_campaign,$dossier.historical_lineage.pre_engine_failure,$dossier.historical_lineage.superseded_pass,$dossier.historical_lineage.superseded_pass.repaired_projection,$dossier.historical_lineage.superseded_pass.pre_selfhash_repair,$dossier.historical_lineage.prior_admitted_run.plan,$dossier.historical_lineage.prior_admitted_run.summary,$dossier.historical_lineage.prior_admitted_run.attempt,$dossier.historical_lineage.prior_admitted_run.runtime,$dossier.historical_lineage.source_tree_correction_superseded_run.plan,$dossier.historical_lineage.source_tree_correction_superseded_run.summary,$dossier.historical_lineage.source_tree_correction_superseded_run.attempt,$dossier.historical_lineage.source_tree_correction_superseded_run.runtime)){$pathValue=if($entry.PSObject.Properties['evidence_path']){[string]$entry.evidence_path}else{[string]$entry.path};$path=Resolve-A03ClosurePath $pathValue $true;Assert-A03Closure((Get-A03ClosureSha256 $path)-ceq[string]$entry.raw_sha256)"[mir4-a03-closure-lineage-raw] $pathValue"}
}
$programme=Get-Content -Raw -LiteralPath(Join-Path $RepoRoot 'spec/programmes/mir4-4x-operating-programme-v1.json')|ConvertFrom-Json -Depth 100 -DateKind String;$task=@($programme.synthesis.tasks|Where-Object id -CEQ 'A03');Assert-A03Closure($task.Count-eq1)'[mir4-a03-closure-programme-task]';$states=if($AllowActive){@('active','complete')}else{@('complete')};Assert-A03Closure([string]$task[0].state-in$states)'[mir4-a03-closure-programme-state]';Assert-A03Closure((@($task[0].evidence)-join'|')-ceq"$lockRelative|$proofRelative|$dossierRelative|$receiptRelative")'[mir4-a03-closure-programme-evidence]'
$tampered=$proof|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tampered.candidate.source_commit='0'*40;Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $tampered $dossier $receipt))'[mir4-a03-closure-source-tamper]'
$tamperedProof=$proof|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedProof.candidate.content_sha256='0'*64;$tamperedProof.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedProof
$tamperedDossier=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedDossier.execution_proof.record_sha256=[string]$tamperedProof.record_sha256;$tamperedDossier.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedDossier
$tamperedReceipt=$receipt|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedReceipt.execution_proof.record_sha256=[string]$tamperedProof.record_sha256;$tamperedReceipt.dossier.record_sha256=[string]$tamperedDossier.record_sha256;$tamperedReceipt.candidate_binding.content_sha256='0'*64;$tamperedReceipt.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedReceipt
Assert-A03Closure((Test-MIR4BootstrapRecordHash $tamperedProof)-and(Test-MIR4BootstrapRecordHash $tamperedDossier)-and(Test-MIR4BootstrapRecordHash $tamperedReceipt))'[mir4-a03-closure-paired-candidate-tamper-hashes]'
Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $tamperedProof $tamperedDossier $tamperedReceipt))'[mir4-a03-closure-paired-candidate-tamper]'
$tampered=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tampered.execution_proof.path='build/missing-proof.json';Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $proof $tampered $receipt))'[mir4-a03-closure-missing-proof-tamper]'
$tampered=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tampered.observation.canonical_sha256='0'*64;Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $proof $tampered $receipt))'[mir4-a03-closure-observation-tamper]'
$tamperedDossier=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedDossier.runtime_result.factorio_log.sha256='0'*64;$tamperedDossier.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedDossier
$tamperedReceipt=$receipt|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedReceipt.dossier.record_sha256=[string]$tamperedDossier.record_sha256;$tamperedReceipt.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedReceipt
Assert-A03Closure((Test-MIR4BootstrapRecordHash $tamperedDossier)-and(Test-MIR4BootstrapRecordHash $tamperedReceipt))'[mir4-a03-closure-paired-runtime-tamper-hashes]'
Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $proof $tamperedDossier $tamperedReceipt))'[mir4-a03-closure-paired-runtime-tamper]'
$tamperedDossier=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedDossier.historical_lineage.source_tree_correction_superseded_run.runtime.raw_sha256='0'*64;$tamperedDossier.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedDossier
$tamperedReceipt=$receipt|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedReceipt.dossier.record_sha256=[string]$tamperedDossier.record_sha256;$tamperedReceipt.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedReceipt
Assert-A03Closure((Test-MIR4BootstrapRecordHash $tamperedDossier)-and(Test-MIR4BootstrapRecordHash $tamperedReceipt))'[mir4-a03-closure-paired-lineage-tamper-hashes]'
Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $proof $tamperedDossier $tamperedReceipt))'[mir4-a03-closure-paired-lineage-tamper]'
$tamperedDossier=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedDossier.historical_lineage.prior_admitted_run.plan.status='release-qualified';$tamperedDossier.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedDossier
$tamperedReceipt=$receipt|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedReceipt.dossier.record_sha256=[string]$tamperedDossier.record_sha256;$tamperedReceipt.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedReceipt
Assert-A03Closure((Test-MIR4BootstrapRecordHash $tamperedDossier)-and(Test-MIR4BootstrapRecordHash $tamperedReceipt))'[mir4-a03-closure-paired-lineage-status-tamper-hashes]'
Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $proof $tamperedDossier $tamperedReceipt))'[mir4-a03-closure-paired-lineage-status-tamper]'
$tampered=$proof|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;(@($tampered.closure_files|Where-Object name -CEQ 'mir4-a03-k2-intake-observer_0.1.0.zip'))[0].sha256='0'*64;Assert-A03Closure(-not(Test-A03CoreBindings $a00 $lock $tampered $dossier $receipt))'[mir4-a03-closure-archive-tamper]'
$tampered=$receipt|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tampered.release_authority=$true;Assert-A03Closure(-not(Test-MIR4BootstrapRecordHash $tampered))'[mir4-a03-closure-selfhash-tamper]'
$tamperedProof=$proof|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedProof.observation.value.package_visible=$true;$tamperedProof.observation.canonical_sha256=Get-MIR4Sha256String(ConvertTo-MIR4BootstrapCanonicalJson $tamperedProof.observation.value);$tamperedProof.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedProof
$tamperedDossier=$dossier|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedDossier.execution_proof.record_sha256=[string]$tamperedProof.record_sha256;$tamperedDossier.observation.value.package_visible=$true;$tamperedDossier.observation.canonical_sha256=[string]$tamperedProof.observation.canonical_sha256;$tamperedDossier.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedDossier
$tamperedReceipt=$receipt|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedReceipt.execution_proof.record_sha256=[string]$tamperedProof.record_sha256;$tamperedReceipt.dossier.record_sha256=[string]$tamperedDossier.record_sha256;$tamperedReceipt.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedReceipt
Assert-A03Closure((Test-A03CoreBindings $a00 $lock $tamperedProof $tamperedDossier $tamperedReceipt))'[mir4-a03-closure-paired-observation-relational-control]'
Assert-A03Closure((ConvertTo-MIR4BootstrapCanonicalJson $tamperedProof.observation.value)-cne(ConvertTo-MIR4BootstrapCanonicalJson $expectedObservation))'[mir4-a03-closure-paired-observation-exact-rejection]'
$tamperedProof=$proof|ConvertTo-Json -Depth 100|ConvertFrom-Json -Depth 100 -DateKind String;$tamperedProof.execution.plan.digest_policy_ids.text='untrusted-policy';$tamperedProof.record_sha256=Get-MIR4BootstrapRecordSha256 $tamperedProof
Assert-A03Closure(Test-MIR4BootstrapRecordHash $tamperedProof)'[mir4-a03-closure-policy-tamper-hash]'
$policyTamperSchemaValid=$false
try{$policyTamperSchemaValid=($tamperedProof|ConvertTo-Json -Depth 100)|Test-Json -SchemaFile(Join-Path $RepoRoot 'spec/schemas/mir4-a03-k2-k2so-execution-proof-v1.schema.json')}catch{$policyTamperSchemaValid=$false}
Assert-A03Closure(-not$policyTamperSchemaValid)'[mir4-a03-closure-policy-tamper-schema]'
Write-Host '[ok] MIR4 A03 K2/K2SO intake closure is exact, path-safe, history-preserving, and authority-denying.'
