param(
  [Parameter(Mandatory)][string]$Release,
  [Parameter(Mandatory)][string]$FactorioBin,
  [string]$RepoRoot = "",
  [string]$OutputPath = "",
  [string]$WorkRoot = "",
  [int]$TimeoutSeconds = 300
)

$ErrorActionPreference = "Stop"
if (-not $RepoRoot) { $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path }
if (-not $OutputPath) { $OutputPath = Join-Path $RepoRoot ".mir\evidence\terminal\baselines\$Release-engine-observation.json" }
if (-not $WorkRoot) { $WorkRoot = Join-Path $RepoRoot "build\terminal\engine-observations\$Release" }

. (Join-Path $RepoRoot "tools\lib\terminal\TerminalEngineObservation.ps1")
. (Join-Path $RepoRoot "tools\lib\assurance\Core.ps1")

function Write-MIRTerminalJson([string]$Path, $Value) {
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
  $json = (($Value | ConvertTo-Json -Depth 100) -replace "`r`n", "`n") + "`n"
  [IO.File]::WriteAllText($Path, $json, [Text.UTF8Encoding]::new($false))
}

$wavePath = Join-Path $RepoRoot "docs\releases\archive\MIR-3.5-WAVE-INDEX.json"
$verificationPath = Join-Path $RepoRoot "docs\releases\archive\MIR-3.5-PUBLIC-ASSET-VERIFICATION.json"
$queuePath = Join-Path $RepoRoot ".mir\releases\terminal\MIR3-Terminal-Baseline-Capture-QueueV1.json"
$wave = Get-Content -Raw -LiteralPath $wavePath | ConvertFrom-Json -Depth 100
$verification = Get-Content -Raw -LiteralPath $verificationPath | ConvertFrom-Json -Depth 100
$queue = Get-Content -Raw -LiteralPath $queuePath | ConvertFrom-Json -Depth 100
$waveRows = @($wave.releases | Where-Object version -eq $Release)
$verifyRows = @($verification.releases | Where-Object version -eq $Release)
$queueRows = @($queue.rows | Where-Object baseline_release -eq $Release)
if ($waveRows.Count -ne 1 -or $verifyRows.Count -ne 1 -or $queueRows.Count -ne 1) {
  throw "Release is not one exact terminal .5 baseline: $Release"
}
$waveRow = $waveRows[0]
$verifyRow = $verifyRows[0]
$queueRow = $queueRows[0]
$zipPath = Join-Path $RepoRoot ([string]$waveRow.dist)
$zipSha256 = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash
if ($zipSha256 -ne [string]$waveRow.archive_sha256) { throw "Frozen public ZIP identity mismatch for $Release." }
$factorioPath = (Resolve-Path -LiteralPath $FactorioBin).Path
$factorioSha256 = (Get-FileHash -LiteralPath $factorioPath -Algorithm SHA256).Hash
if ($factorioSha256 -ne [string]$verifyRow.factorio_executable_sha256) { throw "Exact engine identity mismatch for $Release." }

$resolvedBuild = (Resolve-Path -LiteralPath (Join-Path $RepoRoot "build")).Path.TrimEnd('\') + '\'
if (Test-Path -LiteralPath $WorkRoot) {
  $resolvedWork = (Resolve-Path -LiteralPath $WorkRoot).Path
  if (-not $resolvedWork.StartsWith($resolvedBuild, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to replace engine-observation work outside build/."
  }
  Remove-Item -LiteralPath $resolvedWork -Recurse -Force
}
$userRoot = Join-Path $WorkRoot "user"
$modsRoot = Join-Path $userRoot "mods"
New-Item -ItemType Directory -Force -Path $modsRoot | Out-Null
Copy-Item -LiteralPath $zipPath -Destination (Join-Path $modsRoot ([IO.Path]::GetFileName($zipPath)))
$modList = [ordered]@{mods=@([ordered]@{name="base";enabled=$true},[ordered]@{name="more-infinite-research";enabled=$true})}
Write-MIRTerminalJson (Join-Path $modsRoot "mod-list.json") $modList

$installation = Get-MIRAssuranceFactorioInstallationFingerprint -FactorioPath $factorioPath
$readData = Join-Path ([string]$installation.root) "data"
$configPath = Join-Path $WorkRoot "factorio-config.ini"
$config = "; Generated by MIR terminal exact-engine observation.`n[path]`nread-data=$($readData.Replace('\','/'))`nwrite-data=$($userRoot.Replace('\','/'))`n`n[general]`nlocale=en`n`n[other]`nenable-steam-networking=false`n"
[IO.File]::WriteAllText($configPath, $config, [Text.UTF8Encoding]::new($false))

$stdoutPath = Join-Path $WorkRoot "stdout.txt"
$stderrPath = Join-Path $WorkRoot "stderr.txt"
$processInfo = [Diagnostics.ProcessStartInfo]::new()
$processInfo.FileName = $factorioPath
$processInfo.UseShellExecute = $false
$processInfo.CreateNoWindow = $true
$processInfo.WindowStyle = [Diagnostics.ProcessWindowStyle]::Hidden
$processInfo.RedirectStandardOutput = $true
$processInfo.RedirectStandardError = $true
foreach ($argument in @("--config", $configPath, "--mod-directory", $modsRoot, "--dump-data")) {
  [void]$processInfo.ArgumentList.Add($argument)
}
$process = [Diagnostics.Process]::Start($processInfo)
$stdoutTask = $process.StandardOutput.ReadToEndAsync()
$stderrTask = $process.StandardError.ReadToEndAsync()
if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
  try { $process.Kill($true) } catch { $process.Kill() }
  throw "Factorio data dump timed out after $TimeoutSeconds seconds for $Release."
}
$stdout = $stdoutTask.GetAwaiter().GetResult()
$stderr = $stderrTask.GetAwaiter().GetResult()
[IO.File]::WriteAllText($stdoutPath, $stdout, [Text.UTF8Encoding]::new($false))
[IO.File]::WriteAllText($stderrPath, $stderr, [Text.UTF8Encoding]::new($false))
if ($process.ExitCode -ne 0) { throw "Factorio data dump failed for $Release with exit code $($process.ExitCode): $stderr $stdout" }

$dumpCandidates = @(
  (Join-Path $userRoot "script-output\data-raw-dump.json"),
  (Join-Path $WorkRoot "script-output\data-raw-dump.json"),
  (Join-Path $RepoRoot "script-output\data-raw-dump.json")
)
$dumpPath = $dumpCandidates | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } | Select-Object -First 1
if (-not $dumpPath) { throw "Factorio did not produce data-raw-dump.json for $Release." }
$dataRaw = Get-Content -Raw -LiteralPath $dumpPath | ConvertFrom-Json -Depth 100
$declaredPath = Join-Path $RepoRoot ".mir\releases\terminal\baselines\$Release\declared\technologies.json"
$declared = Get-Content -Raw -LiteralPath $declaredPath | ConvertFrom-Json -Depth 100
$technologyNames = @($declared.items | ForEach-Object {
  $attribute = @($_.attributes | Where-Object name -eq "generated_technology")
  if ($attribute.Count -eq 1 -and -not [string]::IsNullOrWhiteSpace([string]$attribute[0].value)) { [string]$attribute[0].value }
} | Sort-Object -Unique)
$evidenceRelative = [IO.Path]::GetRelativePath($RepoRoot, $OutputPath).Replace('\','/')
$inventory = Get-MIRTerminalEngineInventory -DataRaw $dataRaw -Release $Release -Target ([string]$queueRow.target) -DeclaredTechnologyNames $technologyNames -EvidencePath $evidenceRelative
$logPath = Join-Path $userRoot "factorio-current.log"
$logSha256 = if (Test-Path -LiteralPath $logPath) { (Get-FileHash -LiteralPath $logPath -Algorithm SHA256).Hash } else { $null }
$record = [ordered]@{
  schema=1; kind="MIR3TerminalEngineObservationV1"; release=$Release; target=[string]$queueRow.target;
  archive_sha256=$zipSha256; executable_sha256=$factorioSha256;
  official_data_file_count=[int]$installation.official_data.file_count;
  official_data_sha256=[string]$installation.official_data.sha256;
  installation_sha256=[string]$installation.installation_sha256;
  dump_sha256=(Get-FileHash -LiteralPath $dumpPath -Algorithm SHA256).Hash;
  log_sha256=$logSha256; mode="base-only-data-raw-after-data-final-fixes";
  technologies=@($inventory.technologies); effects_and_owners=@($inventory.effects_and_owners); settings=@($inventory.settings);
  capability_omissions=@(
    [ordered]@{field="runtime-save-state";reason="Data-stage dump cannot observe per-save runtime state."},
    [ordered]@{field="optional-mod-compatibility-realization";reason="Base-only dump does not substitute for named ecosystem closures."}
  )
}
Write-MIRTerminalJson $OutputPath $record
[pscustomobject][ordered]@{release=$Release;output=(Resolve-Path -LiteralPath $OutputPath).Path;technologies=@($inventory.technologies).Count;effects=@($inventory.effects_and_owners).Count;settings=@($inventory.settings).Count;archive_sha256=$zipSha256;engine_sha256=$factorioSha256;official_data_sha256=[string]$installation.official_data.sha256} | ConvertTo-Json -Depth 10
