param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")),
  [switch]$Check
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path -LiteralPath $RepoRoot).Path
. (Join-Path $repo "scripts\validation\TargetProfiles.ps1")

function ConvertTo-MIRLuaString {
  param([string]$Value)
  $escaped = $Value.Replace("\", "\\").Replace('"', '\"').Replace("`r", "\r").Replace("`n", "\n")
  return '"' + $escaped + '"'
}

function ConvertTo-MIRLuaLiteral {
  param(
    [AllowNull()]$Value,
    [int]$Indent = 0
  )

  if ($null -eq $Value) { return "nil" }
  if ($Value -is [bool]) { return $(if ($Value) { "true" } else { "false" }) }
  if ($Value -is [string]) { return ConvertTo-MIRLuaString -Value $Value }
  if ($Value -is [byte] -or $Value -is [int16] -or $Value -is [int32] -or $Value -is [int64] -or $Value -is [single] -or $Value -is [double] -or $Value -is [decimal]) {
    return [string]::Format([Globalization.CultureInfo]::InvariantCulture, "{0}", $Value)
  }

  $padding = " " * $Indent
  $childPadding = " " * ($Indent + 2)
  if ($Value -is [System.Collections.IEnumerable] -and $Value -isnot [pscustomobject]) {
    $items = @($Value)
    if ($items.Count -eq 0) { return "{}" }
    $rendered = @($items | ForEach-Object { $childPadding + (ConvertTo-MIRLuaLiteral -Value $_ -Indent ($Indent + 2)) })
    return "{`n" + ($rendered -join ",`n") + "`n$padding}"
  }

  $properties = @($Value.PSObject.Properties)
  if ($properties.Count -eq 0) { return "{}" }
  $rows = foreach ($property in $properties) {
    $key = if ($property.Name -match '^[A-Za-z_][A-Za-z0-9_]*$') {
      $property.Name
    } else {
      "[" + (ConvertTo-MIRLuaString -Value $property.Name) + "]"
    }
    $childPadding + $key + " = " + (ConvertTo-MIRLuaLiteral -Value $property.Value -Indent ($Indent + 2))
  }
  return "{`n" + ($rows -join ",`n") + "`n$padding}"
}

$manifest = Get-MIRTargetManifest -RepoRoot $repo
$info = Get-Content -Raw -LiteralPath (Join-Path $repo "info.json") | ConvertFrom-Json
$null = Get-MIRTargetProfile -RepoRoot $repo -FactorioVersion $info.factorio_version

$profilesLua = ConvertTo-MIRLuaLiteral -Value $manifest.profiles -Indent 2
$content = @"
-- Generated by scripts/Sync-MIRTargetProfiles.ps1 from .mir/targets.json.
-- Do not edit this file directly.
local M = {
  schema = $($manifest.schema),
  current_factorio_version = "$($info.factorio_version)",
  profiles = $profilesLua
}

function M.current()
  local profile = M.profiles[M.current_factorio_version]
  if not profile then
    error("MIR target profile is missing for Factorio " .. tostring(M.current_factorio_version) .. ".", 2)
  end
  return profile
end

return M
"@
$content = $content.Replace("`r`n", "`n").TrimEnd() + "`n"
$outputPath = Join-Path $repo "prototypes\mir\platform\factorio\target_profiles.lua"

if ($Check) {
  if (-not (Test-Path -LiteralPath $outputPath -PathType Leaf)) {
    throw "Generated target profile Lua is missing: $outputPath"
  }
  $existing = (Get-Content -Raw -LiteralPath $outputPath).Replace("`r`n", "`n")
  if ($existing -ne $content) {
    throw "Generated target profile Lua is stale. Run scripts/Sync-MIRTargetProfiles.ps1."
  }
  Write-Host "[ok] MIR target profile Lua matches .mir/targets.json and info.json."
  exit 0
}

[IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Generated $outputPath"
