param(
  [Parameter(Mandatory)]
  [ValidateSet("0.12", "0.11", "0.10", "0.9", "0.8", "0.7", "0.6")]
  [string]$FactorioVersion,
  [ValidateSet("directory", "zip")]
  [string]$PackageMode = "directory",
  [switch]$OneTechnology,
  [switch]$Reload,
  [string]$PackagePath = "",
  [int]$TimeoutSeconds = 180,
  [string]$EvidenceRoot = ""
)

$ErrorActionPreference = "Stop"
$repo = Resolve-Path (Join-Path $PSScriptRoot "..")
Import-Module (Join-Path $PSScriptRoot "Museum\MuseumCompiler.psm1") -Force
$catalog = Get-MIRMuseumCatalog -Path (Join-Path $repo ".mir\museum-targets.json")
$target = Get-MIRMuseumTarget -Catalog $catalog -FactorioVersion $FactorioVersion
$validation = Test-MIRMuseumTarget -Catalog $catalog -Target $target -RequireExactPatch
if (-not $validation.passed) { throw ($validation.errors -join "`n") }

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
if ([string]::IsNullOrWhiteSpace($EvidenceRoot)) { $EvidenceRoot = Join-Path $repo "build\museum-runtime\$FactorioVersion\$stamp-$PackageMode" }
if (-not [IO.Path]::IsPathRooted($EvidenceRoot)) { $EvidenceRoot = Join-Path $repo $EvidenceRoot }
if (Test-Path -LiteralPath $EvidenceRoot) { Remove-Item -LiteralPath $EvidenceRoot -Recurse -Force }
New-Item -ItemType Directory -Force -Path $EvidenceRoot | Out-Null
$userDir = Join-Path $EvidenceRoot "user"
$modsDir = Join-Path $userDir "mods"
New-Item -ItemType Directory -Force -Path $modsDir, $userDir | Out-Null

$packageName = "$($catalog.mod_name)_$($target.version)"
if ($PackageMode -eq "zip") {
  if ([string]::IsNullOrWhiteSpace($PackagePath)) {
    $built = New-MIRMuseumPackage -Catalog $catalog -Target $target -RepoRoot $repo -OutputDir "build\museum-runtime\packages"
    $PackagePath = $built.path
  }
  if (-not (Test-Path -LiteralPath $PackagePath -PathType Leaf)) { throw "Package not found: $PackagePath" }
  Copy-Item -LiteralPath $PackagePath -Destination (Join-Path $modsDir "$packageName.zip")
} else {
  $modRoot = Join-Path $modsDir $packageName
  New-MIRMuseumTargetSource -Catalog $catalog -Target $target -OutputRoot $modRoot | Out-Null
  Remove-Item -LiteralPath (Join-Path $modsDir "stream-manifest.json"), (Join-Path $modsDir "balance.json") -Force -ErrorAction SilentlyContinue
  if ($OneTechnology) {
    $families = @($target.families)
    $config = @("-- One-technology runtime probe generated by the museum harness.", "mir_config = {")
    for ($i = 0; $i -lt $families.Count; $i++) {
      $family = $families[$i]
      $enabled = if ($i -eq 0) { "true" } else { "false" }
      $levels = if ($i -eq 0) { 1 } else { 0 }
      $comma = if ($i -lt $families.Count - 1) { "," } else { "" }
      $config += ('  ["{0}"] = {{ enabled = {1}, levels = {2} }}{3}' -f $family.id, $enabled, $levels, $comma)
    }
    $config += "}"
    Set-MIRUtf8Text -Path (Join-Path $modRoot "config.lua") -Text (($config -join "`n") + "`n")
  }
}

$readData = Split-Path -Parent ([string]$target.base_data).Replace('/', '\')
$configPath = Join-Path $EvidenceRoot "factorio-config.ini"
$configText = @"
; Generated by More Infinite Research museum validation.
[path]
read-data=$readData
write-data=$userDir

[general]
locale=en

[other]
enable-steam-networking=false
"@
Set-MIRUtf8Text -Path $configPath -Text ($configText + "`n")
$binary = ([string]$target.binary).Replace('/', '\')

# Factorio 0.11 and earlier predate the --create/--start-server CLI used by the
# 0.12 proof. Prove those releases through two bounded GUI startups instead:
# the exact executable must discover the candidate ZIP, finish its data-stage
# load without an error, and remain healthy at the main menu until the harness
# terminates it. Old releases also require an explicit mod-list.json.
if ($FactorioVersion -ne "0.12") {
  $modList = [ordered]@{
    mods = @(
      [ordered]@{ name = "base"; enabled = "true" },
      [ordered]@{ name = [string]$catalog.mod_name; enabled = "true" }
    )
  }
  Set-MIRUtf8Text -Path (Join-Path $modsDir "mod-list.json") -Text (($modList | ConvertTo-Json -Depth 5) + "`n")

  function Invoke-MIRLegacyStartup {
    param([Parameter(Mandatory)][string]$Name)
    $currentLog = Join-Path $userDir "factorio-current.log"
    Remove-Item -LiteralPath $currentLog -Force -ErrorAction SilentlyContinue
    $started = Get-Date
    $processInfo = [Diagnostics.ProcessStartInfo]::new()
    $processInfo.FileName = $binary
    $processInfo.UseShellExecute = $false
    $processInfo.CreateNoWindow = $true
    $processInfo.WindowStyle = [Diagnostics.ProcessWindowStyle]::Hidden
    [void]$processInfo.ArgumentList.Add("--config")
    [void]$processInfo.ArgumentList.Add($configPath)
    $process = [Diagnostics.Process]::Start($processInfo)
    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    $loadedAt = $null
    $lastObservedWrite = $null
    $quietSince = $null
    $logText = ""
    while ((Get-Date) -lt $deadline) {
      Start-Sleep -Milliseconds 200
      if (Test-Path -LiteralPath $currentLog -PathType Leaf) {
        $item = Get-Item -LiteralPath $currentLog
        if ($lastObservedWrite -ne $item.LastWriteTimeUtc) {
          $lastObservedWrite = $item.LastWriteTimeUtc
          $quietSince = Get-Date
          $logText = Get-Content -Raw -LiteralPath $currentLog
        }
        if (-not $loadedAt -and $logText -match [regex]::Escape("Loading mod $($catalog.mod_name) $($target.version) (data.lua)")) {
          $loadedAt = Get-Date
        }
        if ($logText -match '(?im)(^|\s)(Error|Failed to load mods|Failed to load mod|Invalid Mod|Couldn.t load|stack traceback)') {
          if (-not $process.HasExited) { try { $process.Kill($true) } catch { $process.Kill() } }
          throw "Factorio $FactorioVersion $Name log contains a load failure. Log: $currentLog"
        }
        if ($loadedAt -and $quietSince -and ((Get-Date) - $quietSince).TotalSeconds -ge 2 -and -not $process.HasExited) { break }
      }
      if ($process.HasExited) {
        throw "Factorio $FactorioVersion $Name exited before reaching a proven loaded startup state (exit $($process.ExitCode)). Log: $currentLog"
      }
    }
    if (-not $loadedAt -or $process.HasExited) {
      if (-not $process.HasExited) { try { $process.Kill($true) } catch { $process.Kill() } }
      throw "Factorio $FactorioVersion $Name did not reach a proven loaded startup state within $TimeoutSeconds seconds. Log: $currentLog"
    }
    $logText = Get-Content -Raw -LiteralPath $currentLog
    if ($logText -notmatch [regex]::Escape("Factorio $($target.exact_patch)")) {
      try { $process.Kill($true) } catch { $process.Kill() }
      throw "Runtime log does not prove exact Factorio patch $($target.exact_patch). Log: $currentLog"
    }
    try { $process.Kill($true) } catch { $process.Kill() }
    [void]$process.WaitForExit(10000)
    $proofLog = Join-Path $EvidenceRoot "$Name.log"
    Copy-Item -LiteralPath $currentLog -Destination $proofLog -Force
    return [pscustomobject][ordered]@{
      status = "passed-bounded-startup-load"
      duration_seconds = [math]::Round(((Get-Date) - $started).TotalSeconds, 3)
      command = @($binary, "--config", $configPath)
      terminated_after_proof = $true
      process_exit_code = $process.ExitCode
      log_path = (Resolve-Path -LiteralPath $proofLog).Path
      log_sha256 = Get-MIRSha256 $proofLog
    }
  }

  $first = Invoke-MIRLegacyStartup -Name "fresh-start"
  $second = if ($Reload) { Invoke-MIRLegacyStartup -Name "second-start" } else { $null }
  $record = [ordered]@{
    schema = 1
    status = "passed"
    factorio = $FactorioVersion
    exact_patch = [string]$target.exact_patch
    binary = (Resolve-Path -LiteralPath $binary).Path
    binary_sha256 = Get-MIRSha256 $binary
    binary_architecture = "win64-x64"
    package_mode = $PackageMode
    package_path = if ($PackageMode -eq "zip") { (Resolve-Path -LiteralPath (Join-Path $modsDir "$packageName.zip")).Path } else { (Resolve-Path -LiteralPath (Join-Path $modsDir $packageName)).Path }
    one_technology = [bool]$OneTechnology
    runtime_mode = "bounded-gui-startup-load"
    fresh_start = $first
    second_start = $second
    reload = if ($second) { "passed-bounded-second-startup" } else { "not_run" }
    save_proof = "not_available_on_target_cli"
  }
  $recordPath = Join-Path $EvidenceRoot "runtime-proof.json"
  Set-MIRUtf8Text -Path $recordPath -Text (($record | ConvertTo-Json -Depth 10) + "`n")
  $record | ConvertTo-Json -Depth 10
  return
}

$saveName = "fresh-create"
$savePath = Join-Path $userDir "saves\$saveName.zip"
$arguments = @("--config", $configPath, "--create", $saveName)
$started = Get-Date
$processInfo = [Diagnostics.ProcessStartInfo]::new()
$processInfo.FileName = $binary
$processInfo.UseShellExecute = $false
$processInfo.CreateNoWindow = $true
$processInfo.WindowStyle = [Diagnostics.ProcessWindowStyle]::Hidden
$processInfo.RedirectStandardOutput = $true
$processInfo.RedirectStandardError = $true
foreach ($argument in $arguments) { [void]$processInfo.ArgumentList.Add($argument) }
$process = [Diagnostics.Process]::Start($processInfo)
$stdoutTask = $process.StandardOutput.ReadToEndAsync()
$stderrTask = $process.StandardError.ReadToEndAsync()
if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
  try { $process.Kill($true) } catch { $process.Kill() }
  throw "Factorio $FactorioVersion runtime probe timed out after $TimeoutSeconds seconds."
}
$exitCode = $process.ExitCode
$stdout = $stdoutTask.GetAwaiter().GetResult()
$stderr = $stderrTask.GetAwaiter().GetResult()
Set-MIRUtf8Text -Path (Join-Path $EvidenceRoot "stdout.txt") -Text $stdout
Set-MIRUtf8Text -Path (Join-Path $EvidenceRoot "stderr.txt") -Text $stderr
$duration = [math]::Round(((Get-Date) - $started).TotalSeconds, 3)
$logCandidates = @(
  (Join-Path $userDir "factorio-current.log"),
  (Join-Path $userDir "factorio.log"),
  (Join-Path $EvidenceRoot "factorio-current.log")
)
$logPath = $logCandidates | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } | Select-Object -First 1
$logText = if ($logPath) { Get-Content -Raw -LiteralPath $logPath } else { "" }
if ($exitCode -ne 0) { throw "Factorio $FactorioVersion runtime probe exited with code $exitCode. stderr: $stderr stdout: $stdout Log: $logPath" }
if (-not (Test-Path -LiteralPath $savePath -PathType Leaf)) { throw "Factorio $FactorioVersion did not create the expected save. Log: $logPath" }
if ($logText -match '(?im)(^|\s)(Error|Failed to load mods|Failed to load mod|Invalid Mod|Couldn.t load|stack traceback)') { throw "Factorio $FactorioVersion log contains a load failure. Log: $logPath" }
if ($logText -notmatch [regex]::Escape("Factorio $($target.exact_patch)")) { throw "Runtime log does not prove exact Factorio patch $($target.exact_patch). Log: $logPath" }
if ($logText -notmatch [regex]::Escape("Loading mod $($catalog.mod_name) $($target.version) (data.lua)")) { throw "Runtime log does not prove that the candidate mod loaded. Log: $logPath" }
$createLogPath = Join-Path $EvidenceRoot "fresh-create.log"
Copy-Item -LiteralPath $logPath -Destination $createLogPath -Force
$reloadStatus = "not_run"
$reloadLogPath = ""
$reloadLogSha256 = ""
if ($Reload) {
  $reloadArguments = @("--config", $configPath, "--start-server", $saveName)
  $reloadInfo = [Diagnostics.ProcessStartInfo]::new()
  $reloadInfo.FileName = $binary
  $reloadInfo.UseShellExecute = $false
  $reloadInfo.CreateNoWindow = $true
  $reloadInfo.WindowStyle = [Diagnostics.ProcessWindowStyle]::Hidden
  $reloadInfo.RedirectStandardOutput = $true
  $reloadInfo.RedirectStandardError = $true
  foreach ($argument in $reloadArguments) { [void]$reloadInfo.ArgumentList.Add($argument) }
  $reloadProcess = [Diagnostics.Process]::Start($reloadInfo)
  $reloadStdoutTask = $reloadProcess.StandardOutput.ReadToEndAsync()
  $reloadStderrTask = $reloadProcess.StandardError.ReadToEndAsync()
  $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
  $reloadHealthy = $false
  while ((Get-Date) -lt $deadline -and -not $reloadProcess.HasExited) {
    Start-Sleep -Milliseconds 200
    if (Test-Path -LiteralPath (Join-Path $userDir "factorio-current.log")) {
      $candidateLog = Get-Content -Raw -LiteralPath (Join-Path $userDir "factorio-current.log")
      if ($candidateLog -match '(?im)(^|\s)(Error|Failed to load mods|Failed to load mod|Invalid Mod|Couldn.t load|stack traceback)') {
        try { $reloadProcess.Kill($true) } catch { $reloadProcess.Kill() }
        throw "Factorio $FactorioVersion reload log contains a failure."
      }
      if ($candidateLog -match [regex]::Escape("Loading mod $($catalog.mod_name) $($target.version) (data.lua)") -and
          $candidateLog -match [regex]::Escape("Map version $($target.exact_patch)-0")) {
        $reloadHealthy = $true
        break
      }
    }
  }
  if (-not $reloadHealthy) {
    if (-not $reloadProcess.HasExited) { try { $reloadProcess.Kill($true) } catch { $reloadProcess.Kill() } }
    throw "Factorio $FactorioVersion reload did not reach a proven loaded-map state within $TimeoutSeconds seconds."
  }
  try { $reloadProcess.Kill($true) } catch { $reloadProcess.Kill() }
  [void]$reloadProcess.WaitForExit(10000)
  $reloadStdout = $reloadStdoutTask.GetAwaiter().GetResult()
  $reloadStderr = $reloadStderrTask.GetAwaiter().GetResult()
  Set-MIRUtf8Text -Path (Join-Path $EvidenceRoot "reload-stdout.txt") -Text $reloadStdout
  Set-MIRUtf8Text -Path (Join-Path $EvidenceRoot "reload-stderr.txt") -Text $reloadStderr
  $reloadLogPath = Join-Path $EvidenceRoot "fresh-reload.log"
  Copy-Item -LiteralPath (Join-Path $userDir "factorio-current.log") -Destination $reloadLogPath -Force
  $reloadLogSha256 = Get-MIRSha256 $reloadLogPath
  $reloadStatus = "passed-bounded-server-load"
}

$record = [ordered]@{
  schema = 1
  status = "passed"
  factorio = $FactorioVersion
  exact_patch = [string]$target.exact_patch
  binary = (Resolve-Path -LiteralPath $binary).Path
  binary_sha256 = Get-MIRSha256 $binary
  binary_architecture = "win64-x64"
  package_mode = $PackageMode
  package_path = if ($PackageMode -eq "zip") { (Resolve-Path -LiteralPath (Join-Path $modsDir "$packageName.zip")).Path } else { (Resolve-Path -LiteralPath (Join-Path $modsDir $packageName)).Path }
  one_technology = [bool]$OneTechnology
  command = @($binary) + $arguments
  exit_code = $exitCode
  stdout_sha256 = Get-MIRSha256 (Join-Path $EvidenceRoot "stdout.txt")
  stderr_sha256 = Get-MIRSha256 (Join-Path $EvidenceRoot "stderr.txt")
  duration_seconds = $duration
  save_path = (Resolve-Path -LiteralPath $savePath).Path
  save_sha256 = Get-MIRSha256 $savePath
  log_path = (Resolve-Path -LiteralPath $createLogPath).Path
  log_sha256 = Get-MIRSha256 $createLogPath
  fresh_create = "passed"
  reload = $reloadStatus
  reload_log_path = if ($reloadLogPath) { (Resolve-Path -LiteralPath $reloadLogPath).Path } else { "" }
  reload_log_sha256 = $reloadLogSha256
}
$recordPath = Join-Path $EvidenceRoot "runtime-proof.json"
Set-MIRUtf8Text -Path $recordPath -Text (($record | ConvertTo-Json -Depth 10) + "`n")
$record | ConvertTo-Json -Depth 10
