param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")),
  [switch]$Check
)

$ErrorActionPreference = "Stop"
$sourcePath = Join-Path $RepoRoot ".mir\technology-governance.json"
$outputPath = Join-Path $RepoRoot "prototypes\mir\domain\technology\generated_promotion_registry.lua"

function ConvertTo-MIRLuaString([string]$Value) {
  return '"' + $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n') + '"'
}

function Test-MIRLuaIdentifier([string]$Value) { return $Value -match '^[A-Za-z_][A-Za-z0-9_]*$' }

function ConvertTo-MIRLua($Value, [int]$Depth = 0) {
  if ($null -eq $Value) { return "nil" }
  if ($Value -is [bool]) { return $Value.ToString().ToLowerInvariant() }
  if ($Value -is [string]) { return ConvertTo-MIRLuaString $Value }
  if ($Value -is [ValueType]) { return [Convert]::ToString($Value, [Globalization.CultureInfo]::InvariantCulture) }
  $indent = "  " * $Depth
  $childIndent = "  " * ($Depth + 1)
  if ($Value -is [System.Collections.IEnumerable] -and $Value -isnot [pscustomobject] -and $Value -isnot [System.Collections.IDictionary]) {
    $rows = @($Value | ForEach-Object { $childIndent + (ConvertTo-MIRLua $_ ($Depth + 1)) })
    if ($rows.Count -eq 0) { return "{}" }
    return "{`n" + ($rows -join ",`n") + "`n$indent}"
  }
  $properties = if ($Value -is [System.Collections.IDictionary]) {
    @($Value.Keys | Sort-Object | ForEach-Object { [pscustomobject]@{Name=[string]$_; Value=$Value[$_]} })
  } else { @($Value.PSObject.Properties | Sort-Object Name) }
  $rows = foreach ($property in $properties) {
    $key = if (Test-MIRLuaIdentifier $property.Name) { $property.Name } else { "[" + (ConvertTo-MIRLuaString $property.Name) + "]" }
    $childIndent + $key + " = " + (ConvertTo-MIRLua $property.Value ($Depth + 1))
  }
  if (@($rows).Count -eq 0) { return "{}" }
  return "{`n" + (@($rows) -join ",`n") + "`n$indent}"
}

$authority = Get-Content -Raw -LiteralPath $sourcePath | ConvertFrom-Json
if ([int]$authority.schema -ne 1 -or [string]$authority.authority -ne "mir-technology-governance-v1") {
  throw "Technology governance authority schema is invalid."
}
foreach ($field in @("authorizations", "approvals", "promotions", "applicability_envelopes", "migrations")) {
  if ($null -eq $authority.PSObject.Properties[$field]) { throw "Technology governance field is required: $field" }
}
$seen = @{}
foreach ($record in @($authority.authorizations)) {
  if ([string]::IsNullOrWhiteSpace([string]$record.authorization_id) -or $seen.ContainsKey([string]$record.authorization_id)) {
    throw "Technology governance authorization id is invalid or duplicated: $($record.authorization_id)"
  }
  $seen[[string]$record.authorization_id] = $true
}
$content = "-- Generated by scripts/Update-MIRTechnologyGovernance.ps1. Do not edit by hand.`nreturn " + (ConvertTo-MIRLua $authority) + "`n"
if ($Check) {
  $existing = Get-Content -Raw -LiteralPath $outputPath
  if ($existing.Replace("`r`n", "`n") -ne $content.Replace("`r`n", "`n")) { throw "Generated promotion registry is stale." }
} else {
  Set-Content -LiteralPath $outputPath -Value $content -Encoding UTF8 -NoNewline
}
Write-Host "[ok] technology governance source and generated promotion registry are aligned."
