Initialize-MIRValidationResult `
  -OutputPath $ValidationSummaryPath `
  -FactorioVersion $repoInfo.factorio_version `
  -RequiredGroups $requiredGroupsForRun `
  -MirVersion $repoInfo.version `
  -GitCommit (Get-MIRGitCommit -RepoRoot $repo) `
  -TargetProfileSha256 (Get-MIRTargetProfileFingerprint -Profile $targetProfile) `
  -RequiredGroupsSha256 (Get-MIRRequiredGroupsFingerprint -RequiredGroups $requiredGroupsForRun) `
  -PackageSourceSha256 (Get-MIRPackageSourceFingerprint -RepoRoot $repo) `
  -ValidationPackageSha256 (Get-MIRFileSha256 -Path $script:ValidationPackageZipPath) `
  -ValidationPackageContentSha256 (Get-MIRZipContentFingerprint -Path $script:ValidationPackageZipPath) `
  -FactorioBinaryVersion (Get-MIRFactorioBinaryVersion -Path $FactorioBin) `
  -PackageSourceGitDirty (Test-MIRPackageSourceGitDirty -RepoRoot $repo) `
  -ValidationHarnessSha256 (Get-MIRValidationHarnessFingerprint -RepoRoot $repo) `
  -ValidationHarnessGitDirty (Test-MIRValidationHarnessGitDirty -RepoRoot $repo) `
  -ExpectedScenariosSha256 (Get-MIRFileContentSha256 -Path $expectedScenariosPath -RelativePath "validation/scenarios/runtime.json") `
  -ExpectedScenarios $expectedScenarios | Out-Null
if (-not $ScenarioWorker) {
  $staticDeclaration = Resolve-MIRScenarioDeclaration -Registry $scenarioRegistry -ScenarioName "static-validation" -Kind "gate"
  $packageBuildDeclaration = Resolve-MIRScenarioDeclaration -Registry $scenarioRegistry -ScenarioName "package-build" -Kind "gate"
  $runtimeStateDeclaration = Resolve-MIRScenarioDeclaration -Registry $scenarioRegistry -ScenarioName "runtime-state-contract" -Kind "gate"
  Add-MIRValidationCompletedScenario -Name $staticDeclaration.name -Group $staticDeclaration.group -EvidencePaths @("scripts/Invoke-MIRValidation.ps1")
  Add-MIRValidationCompletedScenario -Name $packageBuildDeclaration.name -Group $packageBuildDeclaration.group -EvidencePaths @("build/validation-dist")
  Add-MIRValidationCompletedScenario -Name $runtimeStateDeclaration.name -Group $runtimeStateDeclaration.group -EvidencePaths @("prototypes/mir/platform/factorio/runtime_state.lua")
}

$usesGeneratedUserDataDir = [string]::IsNullOrWhiteSpace($UserDataDir)
if ($usesGeneratedUserDataDir) {
  $generatedUserDataRoot = Join-Path $repo "build\validation-userdata"
  New-Item -ItemType Directory -Force -Path $generatedUserDataRoot | Out-Null
  $UserDataDir = Join-Path $generatedUserDataRoot ("u-" + [guid]::NewGuid().ToString("N").Substring(0, 16))
}
$validationRoot = (New-Item -ItemType Directory -Force -Path $UserDataDir).FullName
$validationRootWithSeparator = $validationRoot.TrimEnd("\") + "\"

function Remove-MIRGeneratedValidationUserData {
  if (-not $usesGeneratedUserDataDir -or -not (Test-Path -LiteralPath $validationRoot)) { return }
  $resolvedGeneratedRoot = (Resolve-Path -LiteralPath $generatedUserDataRoot).Path.TrimEnd("\") + "\"
  $resolvedValidationRoot = (Resolve-Path -LiteralPath $validationRoot).Path
  if (-not $resolvedValidationRoot.StartsWith($resolvedGeneratedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "Refusing to remove generated validation userdata outside its build root: $resolvedValidationRoot"
  }
  Remove-Item -LiteralPath $resolvedValidationRoot -Recurse -Force
}

$factorioBinResolved = (Resolve-Path -LiteralPath $FactorioBin).Path
$factorioRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $factorioBinResolved))
$factorioReadData = Join-Path $factorioRoot "data"
if (-not (Test-Path -LiteralPath $factorioReadData)) {
  throw "Unable to find Factorio read-data directory for validation config: $factorioReadData"
}
$factorioConfigPath = Join-Path $validationRoot "mir-validation-config.ini"
$factorioConfigText = @"
; Generated by More Infinite Research validation.
[path]
read-data=$factorioReadData
write-data=$validationRoot

[general]
locale=auto

[other]
enable-steam-networking=false
disable-blueprint-storage=true
"@
Set-Content -LiteralPath $factorioConfigPath -Value $factorioConfigText -Encoding UTF8

$fixtureRoot = Join-Path $repo "fixtures"
if (-not (Test-Path -LiteralPath $fixtureRoot)) {
  throw "Fixture directory not found: $fixtureRoot"
}

$nonModFixtureDirs = @("compat-matrix", "golden-plans", "mir4-api-v0", "mir4-mep-v0", "mir4-process-ir-v0", "museum", "run-profiles")

$postMirAssertionFixtures = @(
  "mir-fixture-assert-aai-loader-belt-productivity",
  "mir-fixture-assert-air-scrubbing-clean-filter",
  "mir-fixture-assert-atan-ash-separation",
  "mir-fixture-assert-atan-nuclear-science-productivity",
  "mir-fixture-assert-better-bot-battery-skip",
  "mir-fixture-assert-big-mining-drill-productivity",
  "mir-fixture-assert-compiler-contracts",
  "mir-fixture-assert-semantic-family-attach",
  "mir-fixture-assert-semantic-family-generate",
  "mir-fixture-assert-capability-negative-cases",
  "mir-fixture-assert-synthetic-scale-graph",
  "mir-fixture-assert-synthetic-scale-recipes",
  "mir-fixture-assert-generation-integrity",
  "mir-fixture-assert-generated-prerequisite-safety",
  "mir-fixture-assert-final-recipe-effect-integrity",
  "mir-fixture-external-technology-cycle",
  "mir-fixture-rigor-late-recipe-removal",
  "mir-fixture-assert-hidden-setting-readability",
  "mir-fixture-assert-science-pack-productivity",
  "mir-fixture-assert-lab-skip-policy",
  "mir-fixture-assert-lab-productivity-owner-skip",
  "mir-fixture-assert-legacy-effect-icons",
  "mir-fixture-assert-base-extension-boundary",
  "mir-fixture-assert-base-competitor-transaction",
  "mir-fixture-assert-cargo-logistics",
  "mir-fixture-assert-fluid-productivity",
  "mir-fixture-assert-omega-drill-productivity",
  "mir-fixture-assert-pipeline-extent",
  "mir-fixture-assert-plates-n-circuit-productivity",
  "mir-fixture-assert-plates-n-circuit-productivity-blocked",
  "mir-fixture-assert-plates-n-circuit-productivity-change-mismatch",
  "mir-fixture-assert-prototype-limits",
  "mir-fixture-assert-reduced-settings-surface",
  "mir-fixture-assert-settings-profile-roundtrip",
  "mir-fixture-assert-scripted-runtime-lifecycle",
  "mir-fixture-assert-vanilla-family-adoption",
  "mir-fixture-assert-vanilla-family-exact-owner",
  "mir-fixture-assert-vanilla-family-mixed-owner",
  "mir-fixture-assert-vanilla-family-owner-prepatched",
  "mir-fixture-assert-weapon-speed-safety"
)

function Get-FixtureInfos {
  $infos = @()
  foreach ($fixture in Get-ChildItem -LiteralPath $fixtureRoot -Directory) {
    if ($nonModFixtureDirs -contains $fixture.Name) { continue }
    $infoPath = Join-Path $fixture.FullName "info.json"
    if (-not (Test-Path -LiteralPath $infoPath -PathType Leaf)) { continue }
    $info = Get-Content -Raw $infoPath | ConvertFrom-Json
    $infos += [pscustomobject]@{
      Name = $info.name
      Version = $info.version
      Path = $fixture.FullName
    }
  }
  return $infos
}

